In [1]:
# ============================================================
# PHASE 6.5 — CELL 1
# CLIP ↔ SOURCE ALIGNMENT VERIFICATION
#
# READ ONLY
#
# Purpose:
#   Verify Phase 6 v4 outputs before creating new annotations.
#
# IMPORTANT:
#   - DOES NOT modify Phase 6 files
#   - DOES NOT modify NPZ
#   - DOES NOT modify clip_metadata.csv
#   - DOES NOT create labels
#   - DOES NOT create transcript
#   - DOES NOT guess annotations
# ============================================================

from pathlib import Path
import json
import re
import numpy as np
import pandas as pd


print("=" * 78)
print("PHASE 6.5 — CLIP ↔ SOURCE ALIGNMENT VERIFICATION")
print("=" * 78)
print()
print("MODE : READ ONLY")
print()


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(r"C:\LipReadingSSL")

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "output"
)

PHASE65_ROOT = (
    OUTPUT_ROOT
    / "phase6.5"
)

REPORT_ROOT = (
    PHASE65_ROOT
    / "reports"
)


# ============================================================
# VIDEO CONFIGURATION
# ============================================================

VIDEO_IDS = [
    "video001",
    "video002",
    "video003",
]


# Expected Phase 6 v4 clip counts
EXPECTED_CLIP_COUNTS = {
    "video001": 40076,
    "video002": 31662,
    "video003": 26273,
}


EXPECTED_TOTAL_CLIPS = sum(
    EXPECTED_CLIP_COUNTS.values()
)


# ============================================================
# SOURCE SEARCH ROOTS
# ============================================================

SOURCE_SEARCH_ROOTS = [
    PROJECT_ROOT,
]


# ============================================================
# CREATE REPORT DIRECTORY ONLY
# ============================================================

REPORT_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


print("Project root :", PROJECT_ROOT)
print("Output root  :", OUTPUT_ROOT)
print("Report root  :", REPORT_ROOT)
print()
print("Videos       :", VIDEO_IDS)
print()
print(
    "Expected total Phase 6 clips :",
    f"{EXPECTED_TOTAL_CLIPS:,}"
)

print()
print("=" * 78)
print("CELL 1 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CLIP ↔ SOURCE ALIGNMENT VERIFICATION
==============================================================================

MODE : READ ONLY

Project root : C:\LipReadingSSL
Output root  : C:\LipReadingSSL\output
Report root  : C:\LipReadingSSL\output\phase6.5\reports

Videos       : ['video001', 'video002', 'video003']

Expected total Phase 6 clips : 98,011

==============================================================================
CELL 1 COMPLETE — READ ONLY
==============================================================================

In [2]:
# ============================================================
# PHASE 6.5 — CELL 2
# VERIFY PHASE 6 DIRECTORY STRUCTURE
#
# READ ONLY
# ============================================================

print("=" * 78)
print("PHASE 6.5 — CELL 2")
print("VERIFY PHASE 6 DIRECTORY STRUCTURE")
print("=" * 78)


PHASE6_PATHS = {}


for video_id in VIDEO_IDS:

    output_dir = (
        OUTPUT_ROOT
        / video_id
    )

    metadata_path = (
        output_dir
        / "clip_metadata.csv"
    )

    shard_dir = (
        output_dir
        / "clip_npy"
    )

    PHASE6_PATHS[video_id] = {
        "output_dir": output_dir,
        "metadata_path": metadata_path,
        "shard_dir": shard_dir,
    }

    print()
    print("-" * 78)
    print(f"VIDEO : {video_id}")
    print("-" * 78)

    print(
        "Output directory :",
        output_dir
    )

    print(
        "Exists           :",
        output_dir.exists()
    )

    print(
        "Metadata         :",
        metadata_path
    )

    print(
        "Metadata exists  :",
        metadata_path.exists()
    )

    print(
        "Shard directory  :",
        shard_dir
    )

    print(
        "Shard dir exists :",
        shard_dir.exists()
    )


print()
print("=" * 78)
print("CELL 2 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 2
VERIFY PHASE 6 DIRECTORY STRUCTURE
==============================================================================

------------------------------------------------------------------------------
VIDEO : video001
------------------------------------------------------------------------------
Output directory : C:\LipReadingSSL\output\video001
Exists           : True
Metadata         : C:\LipReadingSSL\output\video001\clip_metadata.csv
Metadata exists  : True
Shard directory  : C:\LipReadingSSL\output\video001\clip_npy
Shard dir exists : True

------------------------------------------------------------------------------
VIDEO : video002
------------------------------------------------------------------------------
Output directory : C:\LipReadingSSL\output\video002
Exists           : True
Metadata         : C:\LipReadingSSL\output\video002\clip_metadata.csv
Metadata exists  : True
Shard directory  : C:\LipReadingSSL\output\video002\clip_npy
Shard dir exists : True

------------------------------------------------------------------------------
VIDEO : video003
------------------------------------------------------------------------------
Output directory : C:\LipReadingSSL\output\video003
Exists           : True
Metadata         : C:\LipReadingSSL\output\video003\clip_metadata.csv
Metadata exists  : True
Shard directory  : C:\LipReadingSSL\output\video003\clip_npy
Shard dir exists : True

==============================================================================
CELL 2 COMPLETE — READ ONLY
==============================================================================

In [3]:
# ============================================================
# PHASE 6.5 — CELL 3
# LOAD PHASE 6 V4 CLIP METADATA
#
# READ ONLY
# ============================================================

print("=" * 78)
print("PHASE 6.5 — CELL 3")
print("LOAD PHASE 6 V4 CLIP METADATA")
print("=" * 78)


PHASE65_METADATA = {}

for video_id in VIDEO_IDS:

    metadata_path = PHASE6_PATHS[
        video_id
    ][
        "metadata_path"
    ]

    if not metadata_path.exists():

        raise FileNotFoundError(
            f"Missing Phase 6 metadata:\n"
            f"{metadata_path}"
        )

    df = pd.read_csv(
        metadata_path,
        low_memory=False
    )

    PHASE65_METADATA[
        video_id
    ] = df

    print()
    print(
        f"{video_id}: "
        f"{len(df):,} rows"
    )

    print(
        "Columns:"
    )

    for column in df.columns:
        print(
            f"  - {column}"
        )


print()
print("=" * 78)
print("CELL 3 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 3
LOAD PHASE 6 V4 CLIP METADATA
==============================================================================

video001: 40,076 rows
Columns:
  - clip_id
  - video
  - shard
  - shard_index
  - start_frame
  - end_frame

video002: 31,662 rows
Columns:
  - clip_id
  - video
  - shard
  - shard_index
  - start_frame
  - end_frame

video003: 26,273 rows
Columns:
  - clip_id
  - video
  - shard
  - shard_index
  - start_frame
  - end_frame

==============================================================================
CELL 3 COMPLETE — READ ONLY
==============================================================================

In [4]:
# ============================================================
# PHASE 6.5 — CELL 4
# VALIDATE PHASE 6 CLIP COUNTS
#
# READ ONLY
# ============================================================

print("=" * 78)
print("PHASE 6.5 — CELL 4")
print("VALIDATE PHASE 6 CLIP COUNTS")
print("=" * 78)


count_results = []


for video_id in VIDEO_IDS:

    df = PHASE65_METADATA[
        video_id
    ]

    actual_count = len(df)

    expected_count = (
        EXPECTED_CLIP_COUNTS[
            video_id
        ]
    )

    passed = (
        actual_count
        == expected_count
    )

    count_results.append({
        "video_id": video_id,
        "expected_clips": expected_count,
        "actual_clips": actual_count,
        "difference": actual_count - expected_count,
        "status": "PASS" if passed else "FAIL",
    })

    print(
        f"{video_id}: "
        f"expected={expected_count:,} | "
        f"actual={actual_count:,} | "
        f"status={'PASS' if passed else 'FAIL'}"
    )


count_df = pd.DataFrame(
    count_results
)


actual_total = int(
    count_df[
        "actual_clips"
    ].sum()
)


print()
print(
    "Expected total :",
    f"{EXPECTED_TOTAL_CLIPS:,}"
)

print(
    "Actual total   :",
    f"{actual_total:,}"
)

print(
    "Total status   :",
    "PASS"
    if actual_total == EXPECTED_TOTAL_CLIPS
    else "FAIL"
)


if (
    actual_total
    != EXPECTED_TOTAL_CLIPS
):

    raise RuntimeError(
        "Phase 6.5 STOP:\n"
        "Phase 6 clip count does not match "
        "expected 98,011 clips."
    )


print()
print("=" * 78)
print("CELL 4 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 4
VALIDATE PHASE 6 CLIP COUNTS
==============================================================================
video001: expected=40,076 | actual=40,076 | status=PASS
video002: expected=31,662 | actual=31,662 | status=PASS
video003: expected=26,273 | actual=26,273 | status=PASS

Expected total : 98,011
Actual total   : 98,011
Total status   : PASS

==============================================================================
CELL 4 COMPLETE — READ ONLY
==============================================================================

In [7]:
# ==============================================================================
# PHASE 6.5 — CELL 5
# VALIDATE PHASE 6 v4 METADATA SCHEMA — READ ONLY
# ==============================================================================
#
# IMPORTANT:
# - READ ONLY
# - ไม่แก้ clip_metadata.csv
# - ไม่แก้ NPZ
# - ไม่สร้าง dataset
# - ไม่สร้าง label
# - ตรวจ schema ที่ Phase 6 v4 สร้างจริง
#
# Phase 6 v4 schema:
#   clip_id
#   video
#   shard
#   shard_index
#   start_frame
#   end_frame
#
# ==============================================================================

from pathlib import Path
import pandas as pd
import numpy as np


print("=" * 78)
print("PHASE 6.5 — CELL 5 VALIDATE PHASE 6 v4 METADATA SCHEMA")
print("=" * 78)


# ==============================================================================
# 1. CONFIG
# ==============================================================================

PROJECT_ROOT = Path(r"C:\LipReadingSSL")
OUTPUT_ROOT = PROJECT_ROOT / "output"

VIDEO_IDS = [
    "video001",
    "video002",
    "video003",
]


# ==============================================================================
# 2. PHASE 6 v4 REQUIRED SCHEMA
# ==============================================================================

# นี่คือ schema ที่ตรงกับ metadata จริงจาก Phase 6 v4
REQUIRED_COLUMNS = [
    "clip_id",
    "video",
    "shard",
    "shard_index",
    "start_frame",
    "end_frame",
]


# ==============================================================================
# 3. OPTIONAL / NOT REQUIRED COLUMNS
# ==============================================================================

# ถ้ามี column อื่นเพิ่มมา ไม่ถือว่า error
OPTIONAL_COLUMNS = [
    "num_frames",
    "video_id",
    "clip_index",
    "shard_id",
    "dtype",
    "height",
    "width",
    "storage",
]


# ==============================================================================
# 4. HELPER
# ==============================================================================

def validate_integer_column(df, column):
    """
    ตรวจว่าคอลัมน์เป็น numeric และไม่มีค่า invalid
    """
    if column not in df.columns:
        return 0

    values = pd.to_numeric(df[column], errors="coerce")

    return int(values.isna().sum())


# ==============================================================================
# 5. VALIDATE EACH VIDEO
# ==============================================================================

all_pass = True

summary_rows = []


for video_id in VIDEO_IDS:

    print()
    print("-" * 78)
    print(video_id)
    print("-" * 78)

    metadata_path = (
        OUTPUT_ROOT
        / video_id
        / "clip_metadata.csv"
    )

    print("Metadata path :", metadata_path)
    print("Exists        :", metadata_path.exists())

    # --------------------------------------------------------------------------
    # File existence
    # --------------------------------------------------------------------------

    if not metadata_path.exists():

        print("❌ Metadata file NOT FOUND")

        all_pass = False

        summary_rows.append({
            "video_id": video_id,
            "rows": 0,
            "missing_columns": "FILE_NOT_FOUND",
            "null_required": -1,
            "invalid_numeric": -1,
            "invalid_frame_range": -1,
            "video_mismatch": -1,
            "duplicate_clip_id": -1,
            "status": "FAIL",
        })

        continue


    # --------------------------------------------------------------------------
    # Load — READ ONLY
    # --------------------------------------------------------------------------

    df = pd.read_csv(metadata_path)

    print("Rows :", f"{len(df):,}")
    print("Columns:")

    for column in df.columns:
        print("  -", column)


    # --------------------------------------------------------------------------
    # Schema validation
    # --------------------------------------------------------------------------

    missing_columns = [
        column
        for column in REQUIRED_COLUMNS
        if column not in df.columns
    ]

    if missing_columns:

        print()
        print("❌ Schema status : FAIL")
        print("Missing required columns :", missing_columns)

        all_pass = False

        summary_rows.append({
            "video_id": video_id,
            "rows": len(df),
            "missing_columns": ",".join(missing_columns),
            "null_required": -1,
            "invalid_numeric": -1,
            "invalid_frame_range": -1,
            "video_mismatch": -1,
            "duplicate_clip_id": -1,
            "status": "FAIL",
        })

        continue


    print("Schema status : PASS")


    # ==============================================================================
    # 6. NULL CHECK
    # ==============================================================================

    null_required = int(
        df[REQUIRED_COLUMNS]
        .isna()
        .any(axis=1)
        .sum()
    )

    print()
    print("Null required rows :", f"{null_required:,}")


    # ==============================================================================
    # 7. NUMERIC CHECK
    # ==============================================================================

    numeric_columns = [
        "shard_index",
        "start_frame",
        "end_frame",
    ]

    invalid_numeric = 0

    numeric_details = {}

    for column in numeric_columns:

        invalid_count = validate_integer_column(
            df,
            column
        )

        numeric_details[column] = invalid_count
        invalid_numeric += invalid_count

    print()
    print("Invalid numeric values :", f"{invalid_numeric:,}")

    for column, count in numeric_details.items():
        print(
            f"  {column:15s}: {count:,}"
        )


    # ==============================================================================
    # 8. FRAME RANGE CHECK
    # ==============================================================================

    start = pd.to_numeric(
        df["start_frame"],
        errors="coerce"
    )

    end = pd.to_numeric(
        df["end_frame"],
        errors="coerce"
    )

    invalid_frame_range = int(
        (
            start.notna()
            & end.notna()
            & (
                (start < 0)
                | (end < 0)
                | (end < start)
            )
        ).sum()
    )

    print()
    print(
        "Invalid frame ranges :",
        f"{invalid_frame_range:,}"
    )


    # ==============================================================================
    # 9. VIDEO CONSISTENCY
    # ==============================================================================

    video_mismatch = 0

    if "video" in df.columns:

        video_values = (
            df["video"]
            .astype(str)
            .str.strip()
        )

        video_mismatch = int(
            (video_values != video_id).sum()
        )

    print()
    print(
        "Video consistency :",
        "PASS" if video_mismatch == 0 else "FAIL"
    )

    if video_mismatch:
        print(
            "  Mismatched rows :",
            f"{video_mismatch:,}"
        )


    # ==============================================================================
    # 10. DUPLICATE CLIP ID
    # ==============================================================================

    duplicate_clip_id = int(
        df["clip_id"]
        .duplicated()
        .sum()
    )

    print()
    print(
        "Duplicate clip_id :",
        f"{duplicate_clip_id:,}"
    )


    # ==============================================================================
    # 11. CLIP ID EMPTY CHECK
    # ==============================================================================

    empty_clip_id = int(
        df["clip_id"]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(
        "Empty clip_id     :",
        f"{empty_clip_id:,}"
    )


    # ==============================================================================
    # 12. SHARD VALUE CHECK
    # ==============================================================================

    empty_shard = int(
        df["shard"]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print()
    print(
        "Empty shard       :",
        f"{empty_shard:,}"
    )


    # ==============================================================================
    # 13. SHARD INDEX CHECK
    # ==============================================================================

    shard_index = pd.to_numeric(
        df["shard_index"],
        errors="coerce"
    )

    invalid_shard_index = int(
        (
            shard_index.notna()
            & (shard_index < 0)
        ).sum()
    )

    print(
        "Invalid shard_index :",
        f"{invalid_shard_index:,}"
    )


    # ==============================================================================
    # 14. FINAL VIDEO STATUS
    # ==============================================================================

    video_pass = (
        len(missing_columns) == 0
        and null_required == 0
        and invalid_numeric == 0
        and invalid_frame_range == 0
        and video_mismatch == 0
        and duplicate_clip_id == 0
        and empty_clip_id == 0
        and empty_shard == 0
        and invalid_shard_index == 0
    )

    status = "PASS" if video_pass else "FAIL"

    print()
    print(
        f"{'✅' if video_pass else '❌'} {video_id} : {status}"
    )


    if not video_pass:
        all_pass = False


    summary_rows.append({
        "video_id": video_id,
        "rows": len(df),
        "missing_columns": "",
        "null_required": null_required,
        "invalid_numeric": invalid_numeric,
        "invalid_frame_range": invalid_frame_range,
        "video_mismatch": video_mismatch,
        "duplicate_clip_id": duplicate_clip_id,
        "status": status,
    })


# ==============================================================================
# 15. SUMMARY
# ==============================================================================

print()
print("=" * 78)
print("PHASE 6.5 — CELL 5 SUMMARY")
print("=" * 78)

summary_df = pd.DataFrame(summary_rows)

print(
    summary_df.to_string(index=False)
)


# ==============================================================================
# 16. EXPECTED PHASE 6 CLIP COUNTS
# ==============================================================================

expected_counts = {
    "video001": 40076,
    "video002": 31662,
    "video003": 26273,
}

print()
print("=" * 78)
print("PHASE 6 v4 EXPECTED CLIP COUNTS")
print("=" * 78)

count_check_pass = True

for video_id, expected in expected_counts.items():

    row = summary_df[
        summary_df["video_id"] == video_id
    ]

    if row.empty:
        print(
            f"❌ {video_id}: metadata missing"
        )
        count_check_pass = False
        continue

    actual = int(row.iloc[0]["rows"])

    status = "PASS" if actual == expected else "FAIL"

    print(
        f"{video_id}: "
        f"actual={actual:,} | "
        f"expected={expected:,} | "
        f"{status}"
    )

    if actual != expected:
        count_check_pass = False


# ==============================================================================
# 17. FINAL RESULT
# ==============================================================================

print()
print("=" * 78)
print("CELL 5 FINAL RESULT")
print("=" * 78)

if all_pass and count_check_pass:

    print("✅ CELL 5 READ-ONLY VALIDATION : PASS")
    print()
    print("Phase 6 v4 metadata schema is valid.")
    print("All three videos are present.")
    print("Clip counts match Phase 6 v4 expected counts.")
    print()
    print("Ready for next Phase 6.5 cell.")

else:

    print("❌ CELL 5 READ-ONLY VALIDATION : FAIL")
    print()
    print("Do NOT modify Phase 6 files yet.")
    print("Inspect the reported issue before continuing.")


print()
print("=" * 78)
print("CELL 5 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 5 VALIDATE PHASE 6 v4 METADATA SCHEMA
==============================================================================

------------------------------------------------------------------------------
video001
------------------------------------------------------------------------------
Metadata path : C:\LipReadingSSL\output\video001\clip_metadata.csv
Exists        : True
Rows : 40,076
Columns:
  - clip_id
  - video
  - shard
  - shard_index
  - start_frame
  - end_frame
Schema status : PASS

Null required rows : 0

Invalid numeric values : 0
  shard_index    : 0
  start_frame    : 0
  end_frame      : 0

Invalid frame ranges : 0

Video consistency : PASS

Duplicate clip_id : 0
Empty clip_id     : 0

Empty shard       : 0
Invalid shard_index : 0

✅ video001 : PASS

------------------------------------------------------------------------------
video002
------------------------------------------------------------------------------
Metadata path : C:\LipReadingSSL\output\video002\clip_metadata.csv
Exists        : True
Rows : 31,662
Columns:
  - clip_id
  - video
  - shard
  - shard_index
  - start_frame
  - end_frame
Schema status : PASS

Null required rows : 0

Invalid numeric values : 0
  shard_index    : 0
  start_frame    : 0
  end_frame      : 0

Invalid frame ranges : 0

Video consistency : PASS

Duplicate clip_id : 0
Empty clip_id     : 0

Empty shard       : 0
Invalid shard_index : 0

✅ video002 : PASS

------------------------------------------------------------------------------
video003
------------------------------------------------------------------------------
Metadata path : C:\LipReadingSSL\output\video003\clip_metadata.csv
Exists        : True
Rows : 26,273
Columns:
  - clip_id
  - video
  - shard
  - shard_index
  - start_frame
  - end_frame
Schema status : PASS

Null required rows : 0

Invalid numeric values : 0
  shard_index    : 0
  start_frame    : 0
  end_frame      : 0

Invalid frame ranges : 0

Video consistency : PASS

Duplicate clip_id : 0
Empty clip_id     : 0

Empty shard       : 0
Invalid shard_index : 0

✅ video003 : PASS

==============================================================================
PHASE 6.5 — CELL 5 SUMMARY
==============================================================================
video_id  rows missing_columns  null_required  invalid_numeric  invalid_frame_range  video_mismatch  duplicate_clip_id status
video001 40076                              0                0                    0               0                  0   PASS
video002 31662                              0                0                    0               0                  0   PASS
video003 26273                              0                0                    0               0                  0   PASS

==============================================================================
PHASE 6 v4 EXPECTED CLIP COUNTS
==============================================================================
video001: actual=40,076 | expected=40,076 | PASS
video002: actual=31,662 | expected=31,662 | PASS
video003: actual=26,273 | expected=26,273 | PASS

==============================================================================
CELL 5 FINAL RESULT
==============================================================================
✅ CELL 5 READ-ONLY VALIDATION : PASS

Phase 6 v4 metadata schema is valid.
All three videos are present.
Clip counts match Phase 6 v4 expected counts.

Ready for next Phase 6.5 cell.

==============================================================================
CELL 5 COMPLETE — READ ONLY
==============================================================================

In [8]:
# ============================================================
# PHASE 6.5 — CELL 6
# VALIDATE GLOBAL CLIP ID UNIQUENESS
#
# READ ONLY
# ============================================================

print("=" * 78)
print("PHASE 6.5 — CELL 6")
print("VALIDATE GLOBAL CLIP ID UNIQUENESS")
print("=" * 78)


global_duplicate_results = []


for video_id in VIDEO_IDS:

    df = PHASE65_METADATA[
        video_id
    ].copy()

    duplicate_count = int(
        df[
            "clip_id"
        ]
        .duplicated()
        .sum()
    )


    unique_count = int(
        df[
            "clip_id"
        ]
        .nunique()
    )


    total_count = len(df)


    passed = (
        duplicate_count == 0
        and unique_count == total_count
    )


    global_duplicate_results.append({
        "video_id": video_id,
        "rows": total_count,
        "unique_clip_ids": unique_count,
        "duplicate_clip_ids": duplicate_count,
        "status": "PASS" if passed else "FAIL",
    })


    print()
    print(
        f"{video_id}"
    )

    print(
        "Rows              :",
        f"{total_count:,}"
    )

    print(
        "Unique clip IDs   :",
        f"{unique_count:,}"
    )

    print(
        "Duplicate IDs     :",
        f"{duplicate_count:,}"
    )

    print(
        "Status            :",
        "PASS" if passed else "FAIL"
    )


duplicate_df = pd.DataFrame(
    global_duplicate_results
)


if (
    duplicate_df[
        "status"
    ]
    == "FAIL"
).any():

    raise RuntimeError(
        "Duplicate global clip IDs detected "
        "in Phase 6 metadata."
    )


print()
print("=" * 78)
print("CELL 6 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 6
VALIDATE GLOBAL CLIP ID UNIQUENESS
==============================================================================

video001
Rows              : 40,076
Unique clip IDs   : 40,076
Duplicate IDs     : 0
Status            : PASS

video002
Rows              : 31,662
Unique clip IDs   : 31,662
Duplicate IDs     : 0
Status            : PASS

video003
Rows              : 26,273
Unique clip IDs   : 26,273
Duplicate IDs     : 0
Status            : PASS

==============================================================================
CELL 6 COMPLETE — READ ONLY
==============================================================================

In [10]:
# ==============================================================================
# PHASE 6.5 — CELL 7
# VALIDATE FRAME RANGES — PHASE 6 v4
# READ ONLY
# ==============================================================================
#
# Phase 6 v4 metadata schema:
#   clip_id
#   video
#   shard
#   shard_index
#   start_frame
#   end_frame
#
# IMPORTANT:
# - ไม่มีการอ่าน num_frames จาก CSV
# - คำนวณ num_frames จาก start_frame/end_frame
# - ไม่แก้ไขไฟล์ใด ๆ
# - ไม่สร้างไฟล์ใด ๆ
#
# ==============================================================================

from pathlib import Path
import pandas as pd
import numpy as np


print("=" * 78)
print("PHASE 6.5 — CELL 7")
print("VALIDATE FRAME RANGES — PHASE 6 v4")
print("=" * 78)


# ==============================================================================
# 1. CONFIG
# ==============================================================================

PROJECT_ROOT = Path(r"C:\LipReadingSSL")
OUTPUT_ROOT = PROJECT_ROOT / "output"

VIDEO_IDS = [
    "video001",
    "video002",
    "video003",
]


# ==============================================================================
# 2. EXPECTED CLIP COUNTS
# ==============================================================================

EXPECTED_CLIPS = {
    "video001": 40076,
    "video002": 31662,
    "video003": 26273,
}


# ==============================================================================
# 3. REQUIRED PHASE 6 v4 COLUMNS
# ==============================================================================

REQUIRED_COLUMNS = [
    "clip_id",
    "video",
    "shard",
    "shard_index",
    "start_frame",
    "end_frame",
]


# ==============================================================================
# 4. VALIDATION RESULTS
# ==============================================================================

results = []

all_pass = True


# ==============================================================================
# 5. PROCESS EACH VIDEO
# ==============================================================================

for video_id in VIDEO_IDS:

    print()
    print("-" * 78)
    print(video_id)
    print("-" * 78)

    metadata_path = (
        OUTPUT_ROOT
        / video_id
        / "clip_metadata.csv"
    )

    print("Metadata :", metadata_path)
    print("Exists   :", metadata_path.exists())

    # --------------------------------------------------------------------------
    # File check
    # --------------------------------------------------------------------------

    if not metadata_path.exists():

        print("❌ Metadata file not found")

        results.append({
            "video_id": video_id,
            "rows": 0,
            "negative_start": -1,
            "negative_end": -1,
            "end_before_start": -1,
            "invalid_numeric": -1,
            "duplicate_clip_id": -1,
            "video_mismatch": -1,
            "status": "FAIL",
        })

        all_pass = False

        continue


    # --------------------------------------------------------------------------
    # READ ONLY
    # --------------------------------------------------------------------------

    df = pd.read_csv(metadata_path)


    # --------------------------------------------------------------------------
    # Schema check
    # --------------------------------------------------------------------------

    missing = [
        col
        for col in REQUIRED_COLUMNS
        if col not in df.columns
    ]

    if missing:

        print("❌ Missing required columns:", missing)

        results.append({
            "video_id": video_id,
            "rows": len(df),
            "negative_start": -1,
            "negative_end": -1,
            "end_before_start": -1,
            "invalid_numeric": -1,
            "duplicate_clip_id": -1,
            "video_mismatch": -1,
            "status": "FAIL",
        })

        all_pass = False

        continue


    print("Schema : PASS")


    # ==============================================================================
    # 6. CONVERT FRAME COLUMNS TO NUMERIC
    # ==============================================================================

    start = pd.to_numeric(
        df["start_frame"],
        errors="coerce"
    )

    end = pd.to_numeric(
        df["end_frame"],
        errors="coerce"
    )


    # ==============================================================================
    # 7. INVALID NUMERIC VALUES
    # ==============================================================================

    invalid_numeric = int(
        start.isna().sum()
        +
        end.isna().sum()
    )

    print()
    print(
        "Invalid numeric frame values :",
        f"{invalid_numeric:,}"
    )


    # ==============================================================================
    # 8. NEGATIVE FRAME CHECK
    # ==============================================================================

    negative_start = int(
        (start.notna() & (start < 0)).sum()
    )

    negative_end = int(
        (end.notna() & (end < 0)).sum()
    )

    print(
        "Negative start_frame         :",
        f"{negative_start:,}"
    )

    print(
        "Negative end_frame           :",
        f"{negative_end:,}"
    )


    # ==============================================================================
    # 9. FRAME ORDER CHECK
    # ==============================================================================

    end_before_start = int(
        (
            start.notna()
            &
            end.notna()
            &
            (end < start)
        ).sum()
    )

    print(
        "end_frame < start_frame      :",
        f"{end_before_start:,}"
    )


    # ==============================================================================
    # 10. CALCULATE num_frames
    # ==============================================================================
    #
    # Phase 6 v4 ไม่มี num_frames column
    #
    # ดังนั้น:
    #
    #     num_frames = end_frame - start_frame + 1
    #
    # เช่น:
    #     start=0
    #     end=15
    #
    #     num_frames = 15 - 0 + 1 = 16
    #
    # ==============================================================================

    calculated_num_frames = (
        end - start + 1
    )


    # ==============================================================================
    # 11. INVALID CALCULATED FRAME COUNT
    # ==============================================================================

    invalid_num_frames = int(
        (
            calculated_num_frames.notna()
            &
            (calculated_num_frames <= 0)
        ).sum()
    )

    print(
        "Invalid calculated num_frames :",
        f"{invalid_num_frames:,}"
    )


    # ==============================================================================
    # 12. DUPLICATE CLIP ID
    # ==============================================================================

    duplicate_clip_id = int(
        df["clip_id"]
        .astype(str)
        .str.strip()
        .duplicated()
        .sum()
    )

    print(
        "Duplicate clip_id             :",
        f"{duplicate_clip_id:,}"
    )


    # ==============================================================================
    # 13. VIDEO CONSISTENCY
    # ==============================================================================

    video_values = (
        df["video"]
        .astype(str)
        .str.strip()
    )

    video_mismatch = int(
        (video_values != video_id).sum()
    )

    print(
        "Video mismatch                 :",
        f"{video_mismatch:,}"
    )


    # ==============================================================================
    # 14. CLIP COUNT CHECK
    # ==============================================================================

    actual_count = len(df)

    expected_count = EXPECTED_CLIPS[video_id]

    clip_count_pass = (
        actual_count == expected_count
    )

    print()
    print(
        "Clip count :",
        f"{actual_count:,}",
        "/ expected",
        f"{expected_count:,}",
        ":",
        "PASS" if clip_count_pass else "FAIL"
    )


    # ==============================================================================
    # 15. FINAL VIDEO VALIDATION
    # ==============================================================================

    video_pass = (
        invalid_numeric == 0
        and negative_start == 0
        and negative_end == 0
        and end_before_start == 0
        and invalid_num_frames == 0
        and duplicate_clip_id == 0
        and video_mismatch == 0
        and clip_count_pass
    )

    status = "PASS" if video_pass else "FAIL"

    print()
    print(
        f"{'✅' if video_pass else '❌'} "
        f"{video_id} FRAME RANGE : {status}"
    )


    if not video_pass:
        all_pass = False


    results.append({
        "video_id": video_id,
        "rows": actual_count,
        "negative_start": negative_start,
        "negative_end": negative_end,
        "end_before_start": end_before_start,
        "invalid_numeric": invalid_numeric,
        "invalid_num_frames": invalid_num_frames,
        "duplicate_clip_id": duplicate_clip_id,
        "video_mismatch": video_mismatch,
        "status": status,
    })


# ==============================================================================
# 16. SUMMARY
# ==============================================================================

print()
print("=" * 78)
print("PHASE 6.5 — CELL 7 SUMMARY")
print("=" * 78)

results_df = pd.DataFrame(results)

print(
    results_df.to_string(index=False)
)


# ==============================================================================
# 17. TOTAL DATASET CHECK
# ==============================================================================

print()
print("=" * 78)
print("TOTAL PHASE 6 v4 DATASET")
print("=" * 78)

actual_total = int(
    results_df["rows"].sum()
)

expected_total = sum(
    EXPECTED_CLIPS.values()
)

print(
    "Actual total   :",
    f"{actual_total:,}"
)

print(
    "Expected total :",
    f"{expected_total:,}"
)

total_pass = (
    actual_total == expected_total
)

print(
    "Total count    :",
    "PASS" if total_pass else "FAIL"
)


# ==============================================================================
# 18. FINAL RESULT
# ==============================================================================

print()
print("=" * 78)
print("CELL 7 FINAL RESULT")
print("=" * 78)

if all_pass and total_pass:

    print("✅ CELL 7 FRAME RANGE VALIDATION : PASS")
    print()
    print("All three videos passed.")
    print("All frame ranges are valid.")
    print("num_frames was calculated from start_frame/end_frame.")
    print("No num_frames column is required.")
    print()
    print(
        f"Total clips : {actual_total:,}"
    )

else:

    print("❌ CELL 7 FRAME RANGE VALIDATION : FAIL")
    print()
    print("Review the validation summary above.")
    print("No files were modified.")


print()
print("=" * 78)
print("CELL 7 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 7
VALIDATE FRAME RANGES — PHASE 6 v4
==============================================================================

------------------------------------------------------------------------------
video001
------------------------------------------------------------------------------
Metadata : C:\LipReadingSSL\output\video001\clip_metadata.csv
Exists   : True
Schema : PASS

Invalid numeric frame values : 0
Negative start_frame         : 0
Negative end_frame           : 0
end_frame < start_frame      : 0
Invalid calculated num_frames : 0
Duplicate clip_id             : 0
Video mismatch                 : 0

Clip count : 40,076 / expected 40,076 : PASS

✅ video001 FRAME RANGE : PASS

------------------------------------------------------------------------------
video002
------------------------------------------------------------------------------
Metadata : C:\LipReadingSSL\output\video002\clip_metadata.csv
Exists   : True
Schema : PASS

Invalid numeric frame values : 0
Negative start_frame         : 0
Negative end_frame           : 0
end_frame < start_frame      : 0
Invalid calculated num_frames : 0
Duplicate clip_id             : 0
Video mismatch                 : 0

Clip count : 31,662 / expected 31,662 : PASS

✅ video002 FRAME RANGE : PASS

------------------------------------------------------------------------------
video003
------------------------------------------------------------------------------
Metadata : C:\LipReadingSSL\output\video003\clip_metadata.csv
Exists   : True
Schema : PASS

Invalid numeric frame values : 0
Negative start_frame         : 0
Negative end_frame           : 0
end_frame < start_frame      : 0
Invalid calculated num_frames : 0
Duplicate clip_id             : 0
Video mismatch                 : 0

Clip count : 26,273 / expected 26,273 : PASS

✅ video003 FRAME RANGE : PASS

==============================================================================
PHASE 6.5 — CELL 7 SUMMARY
==============================================================================
video_id  rows  negative_start  negative_end  end_before_start  invalid_numeric  invalid_num_frames  duplicate_clip_id  video_mismatch status
video001 40076               0             0                 0                0                   0                  0               0   PASS
video002 31662               0             0                 0                0                   0                  0               0   PASS
video003 26273               0             0                 0                0                   0                  0               0   PASS

==============================================================================
TOTAL PHASE 6 v4 DATASET
==============================================================================
Actual total   : 98,011
Expected total : 98,011
Total count    : PASS

==============================================================================
CELL 7 FINAL RESULT
==============================================================================
✅ CELL 7 FRAME RANGE VALIDATION : PASS

All three videos passed.
All frame ranges are valid.
num_frames was calculated from start_frame/end_frame.
No num_frames column is required.

Total clips : 98,011

==============================================================================
CELL 7 COMPLETE — READ ONLY
==============================================================================

In [12]:
# ==============================================================================
# PHASE 6.5 — CELL 8
# VALIDATE METADATA SHARD MAPPING — PHASE 6 v4
# READ ONLY
# ==============================================================================
#
# Phase 6 v4 metadata schema:
#
#   clip_id
#   video
#   shard
#   shard_index
#   start_frame
#   end_frame
#
# IMPORTANT:
# - ไม่มี shard_id
# - ใช้ shard
# - ใช้ shard_index
# - ไม่แก้ไข metadata
# - ไม่แก้ไข NPZ
# - ไม่สร้างไฟล์
#
# ==============================================================================

from pathlib import Path
import pandas as pd
import numpy as np


print("=" * 78)
print("PHASE 6.5 — CELL 8")
print("VALIDATE METADATA SHARD MAPPING — PHASE 6 v4")
print("=" * 78)


# ==============================================================================
# 1. CONFIG
# ==============================================================================

PROJECT_ROOT = Path(r"C:\LipReadingSSL")
OUTPUT_ROOT = PROJECT_ROOT / "output"

VIDEO_IDS = [
    "video001",
    "video002",
    "video003",
]


# ==============================================================================
# 2. EXPECTED CLIP COUNTS
# ==============================================================================

EXPECTED_CLIPS = {
    "video001": 40076,
    "video002": 31662,
    "video003": 26273,
}


# ==============================================================================
# 3. REQUIRED PHASE 6 v4 COLUMNS
# ==============================================================================

REQUIRED_COLUMNS = [
    "clip_id",
    "video",
    "shard",
    "shard_index",
    "start_frame",
    "end_frame",
]


# ==============================================================================
# 4. RESULT STORAGE
# ==============================================================================

mapping_results = []

all_pass = True


# ==============================================================================
# 5. PROCESS EACH VIDEO
# ==============================================================================

for video_id in VIDEO_IDS:

    print()
    print("-" * 78)
    print(video_id)
    print("-" * 78)

    video_root = (
        OUTPUT_ROOT
        / video_id
    )

    metadata_path = (
        video_root
        / "clip_metadata.csv"
    )

    shard_dir = (
        video_root
        / "clip_npy"
    )

    print("Metadata :", metadata_path)
    print("Shards   :", shard_dir)

    # ==========================================================================
    # FILE CHECKS
    # ==========================================================================

    if not metadata_path.exists():

        print("❌ Metadata file not found")

        mapping_results.append({
            "video_id": video_id,
            "metadata_rows": 0,
            "shards": 0,
            "invalid_shard": -1,
            "invalid_shard_index": -1,
            "missing_shard_file": -1,
            "shard_index_out_of_range": -1,
            "duplicate_mapping": -1,
            "status": "FAIL",
        })

        all_pass = False
        continue


    if not shard_dir.exists():

        print("❌ Shard directory not found")

        mapping_results.append({
            "video_id": video_id,
            "metadata_rows": 0,
            "shards": 0,
            "invalid_shard": -1,
            "invalid_shard_index": -1,
            "missing_shard_file": -1,
            "shard_index_out_of_range": -1,
            "duplicate_mapping": -1,
            "status": "FAIL",
        })

        all_pass = False
        continue


    # ==========================================================================
    # READ METADATA — READ ONLY
    # ==========================================================================

    df = pd.read_csv(metadata_path)

    print(
        "Metadata rows :",
        f"{len(df):,}"
    )

    print(
        "Expected rows :",
        f"{EXPECTED_CLIPS[video_id]:,}"
    )


    # ==========================================================================
    # SCHEMA CHECK
    # ==========================================================================

    missing = [
        col
        for col in REQUIRED_COLUMNS
        if col not in df.columns
    ]

    if missing:

        print(
            "❌ Missing required columns:",
            missing
        )

        mapping_results.append({
            "video_id": video_id,
            "metadata_rows": len(df),
            "shards": 0,
            "invalid_shard": -1,
            "invalid_shard_index": -1,
            "missing_shard_file": -1,
            "shard_index_out_of_range": -1,
            "duplicate_mapping": -1,
            "status": "FAIL",
        })

        all_pass = False
        continue


    print("Schema : PASS")


    # ==========================================================================
    # 6. LIST ACTUAL SHARD FILES
    # ==========================================================================

    shard_files = sorted(
        shard_dir.glob("*.npz")
    )

    print(
        "Shard files :",
        f"{len(shard_files):,}"
    )

    if len(shard_files) == 0:

        print("❌ No NPZ shard files found")

        mapping_results.append({
            "video_id": video_id,
            "metadata_rows": len(df),
            "shards": 0,
            "invalid_shard": -1,
            "invalid_shard_index": -1,
            "missing_shard_file": -1,
            "shard_index_out_of_range": -1,
            "duplicate_mapping": -1,
            "status": "FAIL",
        })

        all_pass = False
        continue


    # ==========================================================================
    # 7. NORMALIZE SHARD COLUMN
    # ==========================================================================

    shard_values = (
        df["shard"]
        .astype(str)
        .str.strip()
    )


    # ==========================================================================
    # 8. VALIDATE SHARD NAMES
    # ==========================================================================

    actual_shard_names = {
        p.name
        for p in shard_files
    }

    invalid_shard_mask = (
        ~shard_values.isin(actual_shard_names)
    )

    invalid_shard = int(
        invalid_shard_mask.sum()
    )

    print(
        "Invalid shard names :",
        f"{invalid_shard:,}"
    )


    # ==========================================================================
    # 9. NORMALIZE SHARD INDEX
    # ==========================================================================

    shard_index = pd.to_numeric(
        df["shard_index"],
        errors="coerce"
    )


    invalid_shard_index = int(
        shard_index.isna().sum()
    )

    print(
        "Invalid shard_index :",
        f"{invalid_shard_index:,}"
    )


    # ==========================================================================
    # 10. CACHE SHARD CAPACITY
    # ==========================================================================
    #
    # We inspect each NPZ only for validation.
    #
    # No file is modified.
    #
    # The validator attempts to determine the number of clips stored
    # in each shard.
    #
    # ==========================================================================

    shard_capacity = {}

    shard_load_errors = []

    print()
    print("Reading shard capacities...")


    for i, shard_path in enumerate(shard_files, start=1):

        try:

            with np.load(
                shard_path,
                allow_pickle=False
            ) as data:

                # --------------------------------------------------------------
                # Find the clip/frame array.
                #
                # Phase 6 v4 shards are expected to contain the actual clips.
                # We identify the largest array whose first dimension is usable.
                # --------------------------------------------------------------

                candidates = []

                for key in data.files:

                    arr = data[key]

                    if getattr(arr, "ndim", 0) >= 1:

                        candidates.append(
                            (
                                key,
                                int(arr.shape[0])
                            )
                        )

                if not candidates:

                    raise RuntimeError(
                        "No usable array found in NPZ"
                    )


                # Prefer common clip keys if present.

                preferred_keys = [
                    "clips",
                    "frames",
                    "data",
                    "mouth",
                    "video",
                    "x",
                ]

                selected = None

                for preferred in preferred_keys:

                    for key, size in candidates:

                        if key.lower() == preferred.lower():

                            selected = size
                            break

                    if selected is not None:
                        break


                # Fallback:
                # use the largest first dimension.

                if selected is None:

                    selected = max(
                        size
                        for _, size in candidates
                    )


                shard_capacity[
                    shard_path.name
                ] = int(selected)


        except Exception as exc:

            shard_load_errors.append(
                (
                    shard_path.name,
                    str(exc)
                )
            )


    print(
        "Shard capacity records :",
        f"{len(shard_capacity):,}"
    )


    if shard_load_errors:

        print()
        print(
            "❌ Shard read errors :",
            f"{len(shard_load_errors):,}"
        )

        for shard_name, error in shard_load_errors[:10]:

            print(
                " ",
                shard_name,
                "->",
                error
            )


    # ==========================================================================
    # 11. CHECK MISSING SHARD FILE
    # ==========================================================================

    missing_shard_file = int(
        (
            ~shard_values.isin(shard_capacity.keys())
        ).sum()
    )

    print()
    print(
        "Missing / unreadable shard :",
        f"{missing_shard_file:,}"
    )


    # ==========================================================================
    # 12. CHECK SHARD INDEX RANGE
    # ==========================================================================

    out_of_range = 0

    valid_capacity_mask = shard_values.isin(
        shard_capacity.keys()
    )

    valid_index_mask = shard_index.notna()

    rows_to_check = (
        valid_capacity_mask
        &
        valid_index_mask
    )


    if rows_to_check.any():

        capacities = shard_values.map(
            shard_capacity
        )

        out_of_range_mask = (
            rows_to_check
            &
            (
                (shard_index < 0)
                |
                (shard_index >= capacities)
            )
        )

        out_of_range = int(
            out_of_range_mask.sum()
        )


    print(
        "Shard index out of range :",
        f"{out_of_range:,}"
    )


    # ==========================================================================
    # 13. CHECK DUPLICATE SHARD MAPPING
    # ==========================================================================
    #
    # One metadata row should correspond to one:
    #
    #     shard + shard_index
    #
    # pair.
    #
    # ==========================================================================

    mapping_key = (
        shard_values
        + "::"
        + shard_index.astype("Int64")
        .astype(str)
    )

    duplicate_mapping = int(
        mapping_key.duplicated().sum()
    )

    print(
        "Duplicate shard mapping :",
        f"{duplicate_mapping:,}"
    )


    # ==========================================================================
    # 14. CLIP COUNT CHECK
    # ==========================================================================

    actual_rows = len(df)

    expected_rows = EXPECTED_CLIPS[video_id]

    clip_count_pass = (
        actual_rows == expected_rows
    )


    # ==========================================================================
    # 15. FINAL VIDEO RESULT
    # ==========================================================================

    video_pass = (
        clip_count_pass
        and invalid_shard == 0
        and invalid_shard_index == 0
        and missing_shard_file == 0
        and out_of_range == 0
        and duplicate_mapping == 0
        and len(shard_load_errors) == 0
    )

    status = (
        "PASS"
        if video_pass
        else
        "FAIL"
    )


    print()
    print(
        f"{'✅' if video_pass else '❌'} "
        f"{video_id} SHARD MAPPING : {status}"
    )


    if not video_pass:
        all_pass = False


    mapping_results.append({
        "video_id": video_id,
        "metadata_rows": actual_rows,
        "shards": len(shard_files),
        "invalid_shard": invalid_shard,
        "invalid_shard_index": invalid_shard_index,
        "missing_shard_file": missing_shard_file,
        "shard_index_out_of_range": out_of_range,
        "duplicate_mapping": duplicate_mapping,
        "status": status,
    })


# ==============================================================================
# 16. SUMMARY
# ==============================================================================

print()
print("=" * 78)
print("PHASE 6.5 — CELL 8 SUMMARY")
print("=" * 78)

mapping_results_df = pd.DataFrame(
    mapping_results
)

print(
    mapping_results_df.to_string(
        index=False
    )
)


# ==============================================================================
# 17. EXPECTED TOTAL
# ==============================================================================

actual_total = int(
    mapping_results_df["metadata_rows"]
    .sum()
)

expected_total = sum(
    EXPECTED_CLIPS.values()
)

print()
print("=" * 78)
print("TOTAL METADATA")
print("=" * 78)

print(
    "Actual total   :",
    f"{actual_total:,}"
)

print(
    "Expected total :",
    f"{expected_total:,}"
)

print(
    "Total count    :",
    "PASS"
    if actual_total == expected_total
    else
    "FAIL"
)


# ==============================================================================
# 18. FINAL RESULT
# ==============================================================================

print()
print("=" * 78)
print("CELL 8 FINAL RESULT")
print("=" * 78)

if (
    all_pass
    and actual_total == expected_total
):

    print("✅ CELL 8 SHARD MAPPING VALIDATION : PASS")
    print()
    print("All three videos passed.")
    print("Metadata → shard → shard_index mapping is valid.")
    print()
    print(
        f"Total clips : {actual_total:,}"
    )

else:

    print("❌ CELL 8 SHARD MAPPING VALIDATION : FAIL")
    print()
    print("Review the summary above.")
    print("No files were modified.")


print()
print("=" * 78)
print("CELL 8 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 8
VALIDATE METADATA SHARD MAPPING — PHASE 6 v4
==============================================================================

------------------------------------------------------------------------------
video001
------------------------------------------------------------------------------
Metadata : C:\LipReadingSSL\output\video001\clip_metadata.csv
Shards   : C:\LipReadingSSL\output\video001\clip_npy
Metadata rows : 40,076
Expected rows : 40,076
Schema : PASS
Shard files : 79
Invalid shard names : 0
Invalid shard_index : 0

Reading shard capacities...
Shard capacity records : 79

Missing / unreadable shard : 0
Shard index out of range : 0
Duplicate shard mapping : 0

✅ video001 SHARD MAPPING : PASS

------------------------------------------------------------------------------
video002
------------------------------------------------------------------------------
Metadata : C:\LipReadingSSL\output\video002\clip_metadata.csv
Shards   : C:\LipReadingSSL\output\video002\clip_npy
Metadata rows : 31,662
Expected rows : 31,662
Schema : PASS
Shard files : 62
Invalid shard names : 0
Invalid shard_index : 0

Reading shard capacities...
Shard capacity records : 62

Missing / unreadable shard : 0
Shard index out of range : 0
Duplicate shard mapping : 0

✅ video002 SHARD MAPPING : PASS

------------------------------------------------------------------------------
video003
------------------------------------------------------------------------------
Metadata : C:\LipReadingSSL\output\video003\clip_metadata.csv
Shards   : C:\LipReadingSSL\output\video003\clip_npy
Metadata rows : 26,273
Expected rows : 26,273
Schema : PASS
Shard files : 52
Invalid shard names : 0
Invalid shard_index : 0

Reading shard capacities...
Shard capacity records : 52

Missing / unreadable shard : 0
Shard index out of range : 0
Duplicate shard mapping : 0

✅ video003 SHARD MAPPING : PASS

==============================================================================
PHASE 6.5 — CELL 8 SUMMARY
==============================================================================
video_id  metadata_rows  shards  invalid_shard  invalid_shard_index  missing_shard_file  shard_index_out_of_range  duplicate_mapping status
video001          40076      79              0                    0                   0                         0                  0   PASS
video002          31662      62              0                    0                   0                         0                  0   PASS
video003          26273      52              0                    0                   0                         0                  0   PASS

==============================================================================
TOTAL METADATA
==============================================================================
Actual total   : 98,011
Expected total : 98,011
Total count    : PASS

==============================================================================
CELL 8 FINAL RESULT
==============================================================================
✅ CELL 8 SHARD MAPPING VALIDATION : PASS

All three videos passed.
Metadata → shard → shard_index mapping is valid.

Total clips : 98,011

==============================================================================
CELL 8 COMPLETE — READ ONLY
==============================================================================

In [14]:
# ==============================================================================
# PHASE 6.5 — CELL 9
# VALIDATE EVERY NPZ SHARD — PHASE 6 v4
# READ ONLY
# ==============================================================================
#
# Purpose:
#   ตรวจสอบ NPZ ทุก shard ของ video001, video002, video003
#   ว่า:
#
#   1. ไฟล์ NPZ เปิดได้
#   2. มีข้อมูลภายใน
#   3. จำนวน clip ใน NPZ สอดคล้องกับ metadata
#   4. shard_index ใน metadata อยู่ในขอบเขตของ NPZ
#   5. ไม่มี mapping ซ้ำ
#
# Phase 6 v4 metadata schema:
#
#   clip_id
#   video
#   shard
#   shard_index
#   start_frame
#   end_frame
#
# IMPORTANT:
#   - ไม่มี shard_id
#   - ใช้ shard
#   - ใช้ shard_index
#   - READ ONLY
#   - ไม่แก้ metadata
#   - ไม่แก้ NPZ
#   - ไม่สร้าง dataset ใหม่
#
# ==============================================================================

from pathlib import Path
import pandas as pd
import numpy as np


print("=" * 78)
print("PHASE 6.5 — CELL 9")
print("VALIDATE EVERY NPZ SHARD — PHASE 6 v4")
print("=" * 78)


# ==============================================================================
# 1. CONFIGURATION
# ==============================================================================

PROJECT_ROOT = Path(
    r"C:\LipReadingSSL"
)

OUTPUT_ROOT = (
    PROJECT_ROOT / "output"
)

VIDEO_IDS = [
    "video001",
    "video002",
    "video003",
]


# ==============================================================================
# 2. EXPECTED CLIP COUNTS
# ==============================================================================

EXPECTED_CLIPS = {
    "video001": 40076,
    "video002": 31662,
    "video003": 26273,
}


# ==============================================================================
# 3. REQUIRED METADATA SCHEMA
# ==============================================================================

REQUIRED_COLUMNS = [
    "clip_id",
    "video",
    "shard",
    "shard_index",
    "start_frame",
    "end_frame",
]


# ==============================================================================
# 4. HELPER
# ==============================================================================

def detect_clip_count_from_npz(npz_path):
    """
    READ ONLY

    ตรวจจำนวนรายการที่เก็บอยู่ใน NPZ

    Phase 6 v4 อาจใช้ชื่อ array ต่างกันได้
    จึงตรวจจาก first dimension ของ array ที่เหมาะสม
    """

    with np.load(
        npz_path,
        allow_pickle=False
    ) as data:

        keys = list(data.files)

        if len(keys) == 0:

            raise RuntimeError(
                "NPZ contains no arrays"
            )

        # --------------------------------------------------------------
        # Preferred clip-array names
        # --------------------------------------------------------------

        preferred_keys = [
            "clips",
            "frames",
            "data",
            "mouth",
            "video",
            "x",
        ]

        for preferred in preferred_keys:

            for key in keys:

                if key.lower() == preferred.lower():

                    arr = data[key]

                    if getattr(arr, "ndim", 0) >= 1:

                        return {
                            "count": int(arr.shape[0]),
                            "key": key,
                            "keys": keys,
                        }


        # --------------------------------------------------------------
        # Fallback
        # --------------------------------------------------------------

        candidates = []

        for key in keys:

            arr = data[key]

            if getattr(arr, "ndim", 0) >= 1:

                candidates.append(
                    (
                        key,
                        int(arr.shape[0]),
                        tuple(arr.shape),
                    )
                )

        if not candidates:

            raise RuntimeError(
                "No usable array with first dimension found"
            )

        # ใช้ array ที่มี first dimension มากที่สุด
        selected = max(
            candidates,
            key=lambda x: x[1]
        )

        return {
            "count": selected[1],
            "key": selected[0],
            "keys": keys,
        }


# ==============================================================================
# 5. STORAGE
# ==============================================================================

all_results = []

global_pass = True


# ==============================================================================
# 6. PROCESS EACH VIDEO
# ==============================================================================

for video_id in VIDEO_IDS:

    print()
    print("=" * 78)
    print(f"VIDEO : {video_id}")
    print("=" * 78)

    metadata_path = (
        OUTPUT_ROOT
        / video_id
        / "clip_metadata.csv"
    )

    shard_dir = (
        OUTPUT_ROOT
        / video_id
        / "clip_npy"
    )


    print(
        "Metadata :",
        metadata_path
    )

    print(
        "Shard dir:",
        shard_dir
    )


    # ==========================================================================
    # 6.1 FILE CHECK
    # ==========================================================================

    if not metadata_path.exists():

        print("❌ Metadata not found")

        global_pass = False

        continue


    if not shard_dir.exists():

        print("❌ Shard directory not found")

        global_pass = False

        continue


    # ==========================================================================
    # 6.2 READ METADATA
    # ==========================================================================

    df = pd.read_csv(
        metadata_path
    )

    print(
        "Metadata rows :",
        f"{len(df):,}"
    )


    # ==========================================================================
    # 6.3 SCHEMA CHECK
    # ==========================================================================

    missing_columns = [
        col
        for col in REQUIRED_COLUMNS
        if col not in df.columns
    ]


    if missing_columns:

        print(
            "❌ Missing columns:",
            missing_columns
        )

        global_pass = False

        continue


    print(
        "Schema : PASS"
    )


    # ==========================================================================
    # 6.4 NORMALIZE SHARD COLUMN
    # ==========================================================================

    metadata_shard = (
        df["shard"]
        .astype(str)
        .str.strip()
    )


    # ==========================================================================
    # 6.5 NORMALIZE SHARD INDEX
    # ==========================================================================

    metadata_shard_index = pd.to_numeric(
        df["shard_index"],
        errors="coerce"
    )


    invalid_shard_index = int(
        metadata_shard_index.isna().sum()
    )


    if invalid_shard_index:

        print(
            "❌ Invalid shard_index:",
            f"{invalid_shard_index:,}"
        )

        global_pass = False

    else:

        print(
            "shard_index : PASS"
        )


    # ==========================================================================
    # 6.6 LIST NPZ FILES
    # ==========================================================================

    shard_files = sorted(
        shard_dir.glob("*.npz")
    )


    print(
        "NPZ shards :",
        f"{len(shard_files):,}"
    )


    if len(shard_files) == 0:

        print(
            "❌ No NPZ files found"
        )

        global_pass = False

        continue


    actual_shard_names = {
        p.name
        for p in shard_files
    }


    # ==========================================================================
    # 6.7 METADATA → NPZ EXISTENCE CHECK
    # ==========================================================================

    missing_shards = sorted(
        set(metadata_shard)
        - actual_shard_names
    )


    if missing_shards:

        print(
            "❌ Metadata references missing NPZ shards:",
            len(missing_shards)
        )

        for name in missing_shards[:10]:

            print(
                "   ",
                name
            )

        global_pass = False

    else:

        print(
            "Metadata → NPZ existence : PASS"
        )


    # ==========================================================================
    # 6.8 VALIDATE EVERY NPZ
    # ==========================================================================

    print()
    print(
        "Validating NPZ files..."
    )


    shard_info = {}

    shard_errors = []


    for index, shard_path in enumerate(
        shard_files,
        start=1
    ):

        try:

            info = detect_clip_count_from_npz(
                shard_path
            )

            shard_info[
                shard_path.name
            ] = info


            print(
                f"[{index:>3}/{len(shard_files):<3}] "
                f"{shard_path.name:<24} "
                f"clips={info['count']:,} "
                f"array={info['key']}"
            )


        except Exception as exc:

            shard_errors.append(
                (
                    shard_path.name,
                    str(exc)
                )
            )


            print(
                f"[{index:>3}/{len(shard_files):<3}] "
                f"{shard_path.name:<24} "
                f"❌ ERROR"
            )


    # ==========================================================================
    # 6.9 NPZ OPEN CHECK
    # ==========================================================================

    if shard_errors:

        print()
        print(
            "❌ NPZ open/read errors :",
            f"{len(shard_errors):,}"
        )

        for shard_name, error in shard_errors[:10]:

            print(
                "   ",
                shard_name,
                "->",
                error
            )

        global_pass = False

    else:

        print()
        print(
            "NPZ open/read : PASS"
        )


    # ==========================================================================
    # 6.10 METADATA SHARD INDEX RANGE
    # ==========================================================================

    out_of_range = 0


    for shard_name, capacity_info in shard_info.items():

        capacity = capacity_info["count"]


        mask = (
            metadata_shard
            == shard_name
        )


        if not mask.any():
            continue


        indices = (
            metadata_shard_index[mask]
        )


        bad = (
            (indices < 0)
            |
            (indices >= capacity)
        )


        out_of_range += int(
            bad.sum()
        )


    print(
        "shard_index range :",
        "PASS"
        if out_of_range == 0
        else f"FAIL ({out_of_range:,})"
    )


    if out_of_range:

        global_pass = False


    # ==========================================================================
    # 6.11 DUPLICATE SHARD + INDEX MAPPING
    # ==========================================================================

    mapping_df = pd.DataFrame({
        "shard": metadata_shard,
        "shard_index": metadata_shard_index,
    })


    duplicate_mapping = int(
        mapping_df.duplicated(
            subset=[
                "shard",
                "shard_index",
            ]
        ).sum()
    )


    print(
        "Duplicate shard mapping :",
        "PASS"
        if duplicate_mapping == 0
        else f"FAIL ({duplicate_mapping:,})"
    )


    if duplicate_mapping:

        global_pass = False


    # ==========================================================================
    # 6.12 METADATA ROW COUNT
    # ==========================================================================

    metadata_count = len(df)

    expected_count = (
        EXPECTED_CLIPS[video_id]
    )


    count_pass = (
        metadata_count
        == expected_count
    )


    print(
        "Metadata clip count :",
        "PASS"
        if count_pass
        else
        (
            f"FAIL "
            f"(actual={metadata_count:,}, "
            f"expected={expected_count:,})"
        )
    )


    if not count_pass:

        global_pass = False


    # ==========================================================================
    # 6.13 SUM NPZ CLIP COUNT
    # ==========================================================================

    npz_total = sum(
        info["count"]
        for info in shard_info.values()
    )


    npz_count_pass = (
        npz_total
        == expected_count
    )


    print(
        "NPZ total clip count :",
        "PASS"
        if npz_count_pass
        else
        (
            f"FAIL "
            f"(actual={npz_total:,}, "
            f"expected={expected_count:,})"
        )
    )


    if not npz_count_pass:

        global_pass = False


    # ==========================================================================
    # 6.14 METADATA → NPZ COUNT CONSISTENCY
    # ==========================================================================

    metadata_mapping_counts = (
        metadata_shard
        .value_counts()
        .to_dict()
    )


    count_mismatches = []


    for shard_name, info in shard_info.items():

        metadata_n = int(
            metadata_mapping_counts.get(
                shard_name,
                0
            )
        )

        npz_n = int(
            info["count"]
        )


        if metadata_n != npz_n:

            count_mismatches.append({
                "shard": shard_name,
                "metadata": metadata_n,
                "npz": npz_n,
            })


    print(
        "Metadata ↔ NPZ per-shard count :",
        "PASS"
        if not count_mismatches
        else
        f"FAIL ({len(count_mismatches):,} shards)"
    )


    if count_mismatches:

        global_pass = False

        for item in count_mismatches[:10]:

            print(
                "   ",
                item
            )


    # ==========================================================================
    # 6.15 VIDEO CONSISTENCY
    # ==========================================================================

    video_values = (
        df["video"]
        .astype(str)
        .str.strip()
    )


    wrong_video = int(
        (
            video_values
            != video_id
        ).sum()
    )


    print(
        "Video consistency :",
        "PASS"
        if wrong_video == 0
        else f"FAIL ({wrong_video:,})"
    )


    if wrong_video:

        global_pass = False


    # ==========================================================================
    # 6.16 CLIP ID UNIQUENESS
    # ==========================================================================

    duplicate_clip_ids = int(
        df["clip_id"]
        .duplicated()
        .sum()
    )


    print(
        "Clip ID uniqueness :",
        "PASS"
        if duplicate_clip_ids == 0
        else f"FAIL ({duplicate_clip_ids:,})"
    )


    if duplicate_clip_ids:

        global_pass = False


    # ==========================================================================
    # 6.17 VIDEO RESULT
    # ==========================================================================

    video_pass = (
        count_pass
        and npz_count_pass
        and not shard_errors
        and out_of_range == 0
        and duplicate_mapping == 0
        and not count_mismatches
        and wrong_video == 0
        and duplicate_clip_ids == 0
        and invalid_shard_index == 0
        and not missing_shards
    )


    print()
    print(
        "=" * 78
    )

    if video_pass:

        print(
            f"✅ {video_id} : PASS"
        )

    else:

        print(
            f"❌ {video_id} : FAIL"
        )

        global_pass = False


    print(
        "=" * 78
    )


    # ==========================================================================
    # 6.18 STORE RESULT
    # ==========================================================================

    all_results.append({
        "video_id": video_id,
        "metadata_rows": metadata_count,
        "expected_rows": expected_count,
        "npz_shards": len(shard_files),
        "npz_total_clips": npz_total,
        "missing_shards": len(missing_shards),
        "npz_read_errors": len(shard_errors),
        "invalid_shard_index": invalid_shard_index,
        "out_of_range": out_of_range,
        "duplicate_mapping": duplicate_mapping,
        "count_mismatches": len(count_mismatches),
        "wrong_video": wrong_video,
        "duplicate_clip_ids": duplicate_clip_ids,
        "status": (
            "PASS"
            if video_pass
            else "FAIL"
        ),
    })


# ==============================================================================
# 7. GLOBAL SUMMARY
# ==============================================================================

print()
print("=" * 78)
print("PHASE 6.5 — CELL 9 GLOBAL SUMMARY")
print("=" * 78)


results_df = pd.DataFrame(
    all_results
)


if len(results_df):

    print(
        results_df.to_string(
            index=False
        )
    )


# ==============================================================================
# 8. TOTAL CLIPS
# ==============================================================================

actual_total = int(
    results_df["metadata_rows"].sum()
) if len(results_df) else 0


expected_total = sum(
    EXPECTED_CLIPS.values()
)


print()
print(
    "Expected total clips :",
    f"{expected_total:,}"
)

print(
    "Metadata total clips :",
    f"{actual_total:,}"
)


total_pass = (
    actual_total
    == expected_total
)


print(
    "Total clip count     :",
    "PASS"
    if total_pass
    else "FAIL"
)


# ==============================================================================
# 9. FINAL RESULT
# ==============================================================================

print()
print("=" * 78)
print("CELL 9 FINAL RESULT")
print("=" * 78)


if global_pass and total_pass:

    print(
        "✅ CELL 9 — NPZ SHARD VALIDATION : PASS"
    )

    print()
    print(
        "All Phase 6 v4 NPZ shards are readable."
    )

    print(
        "Metadata → shard → shard_index mapping is valid."
    )

    print(
        "video001 + video002 + video003 are present."
    )

    print(
        f"Total clips : {actual_total:,}"
    )

else:

    print(
        "❌ CELL 9 — NPZ SHARD VALIDATION : FAIL"
    )

    print()
    print(
        "Review the errors above."
    )

    print(
        "No files were modified."
    )


print()
print("=" * 78)
print("CELL 9 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 9
VALIDATE EVERY NPZ SHARD — PHASE 6 v4
==============================================================================

==============================================================================
VIDEO : video001
==============================================================================
Metadata : C:\LipReadingSSL\output\video001\clip_metadata.csv
Shard dir: C:\LipReadingSSL\output\video001\clip_npy
Metadata rows : 40,076
Schema : PASS
shard_index : PASS
NPZ shards : 79
Metadata → NPZ existence : PASS

Validating NPZ files...
[  1/79 ] shard_000000.npz         clips=512 array=clips
[  2/79 ] shard_000001.npz         clips=512 array=clips
[  3/79 ] shard_000002.npz         clips=512 array=clips
[  4/79 ] shard_000003.npz         clips=512 array=clips
[  5/79 ] shard_000004.npz         clips=512 array=clips
[  6/79 ] shard_000005.npz         clips=512 array=clips
[  7/79 ] shard_000006.npz         clips=512 array=clips
[  8/79 ] shard_000007.npz         clips=512 array=clips
[  9/79 ] shard_000008.npz         clips=512 array=clips
[ 10/79 ] shard_000009.npz         clips=512 array=clips
[ 11/79 ] shard_000010.npz         clips=512 array=clips
[ 12/79 ] shard_000011.npz         clips=512 array=clips
[ 13/79 ] shard_000012.npz         clips=512 array=clips
[ 14/79 ] shard_000013.npz         clips=512 array=clips
[ 15/79 ] shard_000014.npz         clips=512 array=clips
[ 16/79 ] shard_000015.npz         clips=512 array=clips
[ 17/79 ] shard_000016.npz         clips=512 array=clips
[ 18/79 ] shard_000017.npz         clips=512 array=clips
[ 19/79 ] shard_000018.npz         clips=512 array=clips
[ 20/79 ] shard_000019.npz         clips=512 array=clips
[ 21/79 ] shard_000020.npz         clips=512 array=clips
[ 22/79 ] shard_000021.npz         clips=512 array=clips
[ 23/79 ] shard_000022.npz         clips=512 array=clips
[ 24/79 ] shard_000023.npz         clips=512 array=clips
[ 25/79 ] shard_000024.npz         clips=512 array=clips
[ 26/79 ] shard_000025.npz         clips=512 array=clips
[ 27/79 ] shard_000026.npz         clips=512 array=clips
[ 28/79 ] shard_000027.npz         clips=512 array=clips
[ 29/79 ] shard_000028.npz         clips=512 array=clips
[ 30/79 ] shard_000029.npz         clips=512 array=clips
[ 31/79 ] shard_000030.npz         clips=512 array=clips
[ 32/79 ] shard_000031.npz         clips=512 array=clips
[ 33/79 ] shard_000032.npz         clips=512 array=clips
[ 34/79 ] shard_000033.npz         clips=512 array=clips
[ 35/79 ] shard_000034.npz         clips=512 array=clips
[ 36/79 ] shard_000035.npz         clips=512 array=clips
[ 37/79 ] shard_000036.npz         clips=512 array=clips
[ 38/79 ] shard_000037.npz         clips=512 array=clips
[ 39/79 ] shard_000038.npz         clips=512 array=clips
[ 40/79 ] shard_000039.npz         clips=512 array=clips
[ 41/79 ] shard_000040.npz         clips=512 array=clips
[ 42/79 ] shard_000041.npz         clips=512 array=clips
[ 43/79 ] shard_000042.npz         clips=512 array=clips
[ 44/79 ] shard_000043.npz         clips=512 array=clips
[ 45/79 ] shard_000044.npz         clips=512 array=clips
[ 46/79 ] shard_000045.npz         clips=512 array=clips
[ 47/79 ] shard_000046.npz         clips=512 array=clips
[ 48/79 ] shard_000047.npz         clips=512 array=clips
[ 49/79 ] shard_000048.npz         clips=512 array=clips
[ 50/79 ] shard_000049.npz         clips=512 array=clips
[ 51/79 ] shard_000050.npz         clips=512 array=clips
[ 52/79 ] shard_000051.npz         clips=512 array=clips
[ 53/79 ] shard_000052.npz         clips=512 array=clips
[ 54/79 ] shard_000053.npz         clips=512 array=clips
[ 55/79 ] shard_000054.npz         clips=512 array=clips
[ 56/79 ] shard_000055.npz         clips=512 array=clips
[ 57/79 ] shard_000056.npz         clips=512 array=clips
[ 58/79 ] shard_000057.npz         clips=512 array=clips
[ 59/79 ] shard_000058.npz         clips=512 array=clips
[ 60/79 ] shard_000059.npz         clips=512 array=clips
[ 61/79 ] shard_000060.npz         clips=512 array=clips
[ 62/79 ] shard_000061.npz         clips=512 array=clips
[ 63/79 ] shard_000062.npz         clips=512 array=clips
[ 64/79 ] shard_000063.npz         clips=512 array=clips
[ 65/79 ] shard_000064.npz         clips=512 array=clips
[ 66/79 ] shard_000065.npz         clips=512 array=clips
[ 67/79 ] shard_000066.npz         clips=512 array=clips
[ 68/79 ] shard_000067.npz         clips=512 array=clips
[ 69/79 ] shard_000068.npz         clips=512 array=clips
[ 70/79 ] shard_000069.npz         clips=512 array=clips
[ 71/79 ] shard_000070.npz         clips=512 array=clips
[ 72/79 ] shard_000071.npz         clips=512 array=clips
[ 73/79 ] shard_000072.npz         clips=512 array=clips
[ 74/79 ] shard_000073.npz         clips=512 array=clips
[ 75/79 ] shard_000074.npz         clips=512 array=clips
[ 76/79 ] shard_000075.npz         clips=512 array=clips
[ 77/79 ] shard_000076.npz         clips=512 array=clips
[ 78/79 ] shard_000077.npz         clips=512 array=clips
[ 79/79 ] shard_000078.npz         clips=140 array=clips

NPZ open/read : PASS
shard_index range : PASS
Duplicate shard mapping : PASS
Metadata clip count : PASS
NPZ total clip count : PASS
Metadata ↔ NPZ per-shard count : PASS
Video consistency : PASS
Clip ID uniqueness : PASS

==============================================================================
✅ video001 : PASS
==============================================================================

==============================================================================
VIDEO : video002
==============================================================================
Metadata : C:\LipReadingSSL\output\video002\clip_metadata.csv
Shard dir: C:\LipReadingSSL\output\video002\clip_npy
Metadata rows : 31,662
Schema : PASS
shard_index : PASS
NPZ shards : 62
Metadata → NPZ existence : PASS

Validating NPZ files...
[  1/62 ] shard_000000.npz         clips=512 array=clips
[  2/62 ] shard_000001.npz         clips=512 array=clips
[  3/62 ] shard_000002.npz         clips=512 array=clips
[  4/62 ] shard_000003.npz         clips=512 array=clips
[  5/62 ] shard_000004.npz         clips=512 array=clips
[  6/62 ] shard_000005.npz         clips=512 array=clips
[  7/62 ] shard_000006.npz         clips=512 array=clips
[  8/62 ] shard_000007.npz         clips=512 array=clips
[  9/62 ] shard_000008.npz         clips=512 array=clips
[ 10/62 ] shard_000009.npz         clips=512 array=clips
[ 11/62 ] shard_000010.npz         clips=512 array=clips
[ 12/62 ] shard_000011.npz         clips=512 array=clips
[ 13/62 ] shard_000012.npz         clips=512 array=clips
[ 14/62 ] shard_000013.npz         clips=512 array=clips
[ 15/62 ] shard_000014.npz         clips=512 array=clips
[ 16/62 ] shard_000015.npz         clips=512 array=clips
[ 17/62 ] shard_000016.npz         clips=512 array=clips
[ 18/62 ] shard_000017.npz         clips=512 array=clips
[ 19/62 ] shard_000018.npz         clips=512 array=clips
[ 20/62 ] shard_000019.npz         clips=512 array=clips
[ 21/62 ] shard_000020.npz         clips=512 array=clips
[ 22/62 ] shard_000021.npz         clips=512 array=clips
[ 23/62 ] shard_000022.npz         clips=512 array=clips
[ 24/62 ] shard_000023.npz         clips=512 array=clips
[ 25/62 ] shard_000024.npz         clips=512 array=clips
[ 26/62 ] shard_000025.npz         clips=512 array=clips
[ 27/62 ] shard_000026.npz         clips=512 array=clips
[ 28/62 ] shard_000027.npz         clips=512 array=clips
[ 29/62 ] shard_000028.npz         clips=512 array=clips
[ 30/62 ] shard_000029.npz         clips=512 array=clips
[ 31/62 ] shard_000030.npz         clips=512 array=clips
[ 32/62 ] shard_000031.npz         clips=512 array=clips
[ 33/62 ] shard_000032.npz         clips=512 array=clips
[ 34/62 ] shard_000033.npz         clips=512 array=clips
[ 35/62 ] shard_000034.npz         clips=512 array=clips
[ 36/62 ] shard_000035.npz         clips=512 array=clips
[ 37/62 ] shard_000036.npz         clips=512 array=clips
[ 38/62 ] shard_000037.npz         clips=512 array=clips
[ 39/62 ] shard_000038.npz         clips=512 array=clips
[ 40/62 ] shard_000039.npz         clips=512 array=clips
[ 41/62 ] shard_000040.npz         clips=512 array=clips
[ 42/62 ] shard_000041.npz         clips=512 array=clips
[ 43/62 ] shard_000042.npz         clips=512 array=clips
[ 44/62 ] shard_000043.npz         clips=512 array=clips
[ 45/62 ] shard_000044.npz         clips=512 array=clips
[ 46/62 ] shard_000045.npz         clips=512 array=clips
[ 47/62 ] shard_000046.npz         clips=512 array=clips
[ 48/62 ] shard_000047.npz         clips=512 array=clips
[ 49/62 ] shard_000048.npz         clips=512 array=clips
[ 50/62 ] shard_000049.npz         clips=512 array=clips
[ 51/62 ] shard_000050.npz         clips=512 array=clips
[ 52/62 ] shard_000051.npz         clips=512 array=clips
[ 53/62 ] shard_000052.npz         clips=512 array=clips
[ 54/62 ] shard_000053.npz         clips=512 array=clips
[ 55/62 ] shard_000054.npz         clips=512 array=clips
[ 56/62 ] shard_000055.npz         clips=512 array=clips
[ 57/62 ] shard_000056.npz         clips=512 array=clips
[ 58/62 ] shard_000057.npz         clips=512 array=clips
[ 59/62 ] shard_000058.npz         clips=512 array=clips
[ 60/62 ] shard_000059.npz         clips=512 array=clips
[ 61/62 ] shard_000060.npz         clips=512 array=clips
[ 62/62 ] shard_000061.npz         clips=430 array=clips

NPZ open/read : PASS
shard_index range : PASS
Duplicate shard mapping : PASS
Metadata clip count : PASS
NPZ total clip count : PASS
Metadata ↔ NPZ per-shard count : PASS
Video consistency : PASS
Clip ID uniqueness : PASS

==============================================================================
✅ video002 : PASS
==============================================================================

==============================================================================
VIDEO : video003
==============================================================================
Metadata : C:\LipReadingSSL\output\video003\clip_metadata.csv
Shard dir: C:\LipReadingSSL\output\video003\clip_npy
Metadata rows : 26,273
Schema : PASS
shard_index : PASS
NPZ shards : 52
Metadata → NPZ existence : PASS

Validating NPZ files...
[  1/52 ] shard_000000.npz         clips=512 array=clips
[  2/52 ] shard_000001.npz         clips=512 array=clips
[  3/52 ] shard_000002.npz         clips=512 array=clips
[  4/52 ] shard_000003.npz         clips=512 array=clips
[  5/52 ] shard_000004.npz         clips=512 array=clips
[  6/52 ] shard_000005.npz         clips=512 array=clips
[  7/52 ] shard_000006.npz         clips=512 array=clips
[  8/52 ] shard_000007.npz         clips=512 array=clips
[  9/52 ] shard_000008.npz         clips=512 array=clips
[ 10/52 ] shard_000009.npz         clips=512 array=clips
[ 11/52 ] shard_000010.npz         clips=512 array=clips
[ 12/52 ] shard_000011.npz         clips=512 array=clips
[ 13/52 ] shard_000012.npz         clips=512 array=clips
[ 14/52 ] shard_000013.npz         clips=512 array=clips
[ 15/52 ] shard_000014.npz         clips=512 array=clips
[ 16/52 ] shard_000015.npz         clips=512 array=clips
[ 17/52 ] shard_000016.npz         clips=512 array=clips
[ 18/52 ] shard_000017.npz         clips=512 array=clips
[ 19/52 ] shard_000018.npz         clips=512 array=clips
[ 20/52 ] shard_000019.npz         clips=512 array=clips
[ 21/52 ] shard_000020.npz         clips=512 array=clips
[ 22/52 ] shard_000021.npz         clips=512 array=clips
[ 23/52 ] shard_000022.npz         clips=512 array=clips
[ 24/52 ] shard_000023.npz         clips=512 array=clips
[ 25/52 ] shard_000024.npz         clips=512 array=clips
[ 26/52 ] shard_000025.npz         clips=512 array=clips
[ 27/52 ] shard_000026.npz         clips=512 array=clips
[ 28/52 ] shard_000027.npz         clips=512 array=clips
[ 29/52 ] shard_000028.npz         clips=512 array=clips
[ 30/52 ] shard_000029.npz         clips=512 array=clips
[ 31/52 ] shard_000030.npz         clips=512 array=clips
[ 32/52 ] shard_000031.npz         clips=512 array=clips
[ 33/52 ] shard_000032.npz         clips=512 array=clips
[ 34/52 ] shard_000033.npz         clips=512 array=clips
[ 35/52 ] shard_000034.npz         clips=512 array=clips
[ 36/52 ] shard_000035.npz         clips=512 array=clips
[ 37/52 ] shard_000036.npz         clips=512 array=clips
[ 38/52 ] shard_000037.npz         clips=512 array=clips
[ 39/52 ] shard_000038.npz         clips=512 array=clips
[ 40/52 ] shard_000039.npz         clips=512 array=clips
[ 41/52 ] shard_000040.npz         clips=512 array=clips
[ 42/52 ] shard_000041.npz         clips=512 array=clips
[ 43/52 ] shard_000042.npz         clips=512 array=clips
[ 44/52 ] shard_000043.npz         clips=512 array=clips
[ 45/52 ] shard_000044.npz         clips=512 array=clips
[ 46/52 ] shard_000045.npz         clips=512 array=clips
[ 47/52 ] shard_000046.npz         clips=512 array=clips
[ 48/52 ] shard_000047.npz         clips=512 array=clips
[ 49/52 ] shard_000048.npz         clips=512 array=clips
[ 50/52 ] shard_000049.npz         clips=512 array=clips
[ 51/52 ] shard_000050.npz         clips=512 array=clips
[ 52/52 ] shard_000051.npz         clips=161 array=clips

NPZ open/read : PASS
shard_index range : PASS
Duplicate shard mapping : PASS
Metadata clip count : PASS
NPZ total clip count : PASS
Metadata ↔ NPZ per-shard count : PASS
Video consistency : PASS
Clip ID uniqueness : PASS

==============================================================================
✅ video003 : PASS
==============================================================================

==============================================================================
PHASE 6.5 — CELL 9 GLOBAL SUMMARY
==============================================================================
video_id  metadata_rows  expected_rows  npz_shards  npz_total_clips  missing_shards  npz_read_errors  invalid_shard_index  out_of_range  duplicate_mapping  count_mismatches  wrong_video  duplicate_clip_ids status
video001          40076          40076          79            40076               0                0                    0             0                  0                 0            0                   0   PASS
video002          31662          31662          62            31662               0                0                    0             0                  0                 0            0                   0   PASS
video003          26273          26273          52            26273               0                0                    0             0                  0                 0            0                   0   PASS

Expected total clips : 98,011
Metadata total clips : 98,011
Total clip count     : PASS

==============================================================================
CELL 9 FINAL RESULT
==============================================================================
✅ CELL 9 — NPZ SHARD VALIDATION : PASS

All Phase 6 v4 NPZ shards are readable.
Metadata → shard → shard_index mapping is valid.
video001 + video002 + video003 are present.
Total clips : 98,011

==============================================================================
CELL 9 COMPLETE — READ ONLY
==============================================================================

In [16]:
# ==============================================================================
# PHASE 6.5 — CELL 10
# VERIFY GLOBAL CLIP MAPPING — PHASE 6 v4
# READ ONLY
# ==============================================================================

from pathlib import Path
import pandas as pd


print("=" * 78)
print("PHASE 6.5 — CELL 10")
print("VERIFY GLOBAL CLIP MAPPING — PHASE 6 v4")
print("=" * 78)


# ==============================================================================
# 1. CONFIGURATION
# ==============================================================================

PROJECT_ROOT = Path(
    r"C:\LipReadingSSL"
)

OUTPUT_ROOT = PROJECT_ROOT / "output"

VIDEO_IDS = [
    "video001",
    "video002",
    "video003",
]


EXPECTED_CLIPS = {
    "video001": 40076,
    "video002": 31662,
    "video003": 26273,
}


# ==============================================================================
# 2. PHASE 6 v4 SCHEMA
# ==============================================================================

REQUIRED_COLUMNS = [
    "clip_id",
    "video",
    "shard",
    "shard_index",
    "start_frame",
    "end_frame",
]


# ==============================================================================
# 3. LOAD METADATA
# ==============================================================================

PHASE65_METADATA = {}

for video_id in VIDEO_IDS:

    metadata_path = (
        OUTPUT_ROOT
        / video_id
        / "clip_metadata.csv"
    )

    print()
    print("-" * 78)
    print(video_id)
    print("-" * 78)

    print(
        "Metadata:",
        metadata_path
    )

    if not metadata_path.exists():

        raise FileNotFoundError(
            f"{video_id}: metadata not found:\n"
            f"{metadata_path}"
        )

    df = pd.read_csv(
        metadata_path
    )

    missing = [
        col
        for col in REQUIRED_COLUMNS
        if col not in df.columns
    ]

    if missing:

        raise RuntimeError(
            f"{video_id}: "
            f"Missing Phase 6 v4 columns: {missing}"
        )

    PHASE65_METADATA[video_id] = df

    print(
        "Rows:",
        f"{len(df):,}"
    )

    print(
        "Schema: PASS"
    )


# ==============================================================================
# 4. GLOBAL CLIP ID UNIQUENESS
# ==============================================================================

print()
print("=" * 78)
print("CHECK GLOBAL CLIP ID UNIQUENESS")
print("=" * 78)


all_clip_ids = []

for video_id in VIDEO_IDS:

    df = PHASE65_METADATA[
        video_id
    ]

    ids = (
        df["clip_id"]
        .astype(str)
        .str.strip()
    )

    all_clip_ids.extend(
        ids.tolist()
    )


total_clip_ids = len(
    all_clip_ids
)

unique_clip_ids = len(
    set(all_clip_ids)
)

duplicate_global = (
    total_clip_ids
    - unique_clip_ids
)


print(
    "Total clip IDs  :",
    f"{total_clip_ids:,}"
)

print(
    "Unique clip IDs :",
    f"{unique_clip_ids:,}"
)

print(
    "Duplicates      :",
    f"{duplicate_global:,}"
)


if duplicate_global:

    print(
        "❌ GLOBAL CLIP ID UNIQUENESS : FAIL"
    )

    global_mapping_pass = False

else:

    print(
        "✅ GLOBAL CLIP ID UNIQUENESS : PASS"
    )

    global_mapping_pass = True


# ==============================================================================
# 5. EXPECTED GLOBAL TOTAL
# ==============================================================================

expected_global_total = sum(
    EXPECTED_CLIPS.values()
)

print()
print("=" * 78)
print("GLOBAL CLIP COUNT")
print("=" * 78)

print(
    "Expected :",
    f"{expected_global_total:,}"
)

print(
    "Actual   :",
    f"{total_clip_ids:,}"
)


if total_clip_ids == expected_global_total:

    print(
        "✅ GLOBAL CLIP COUNT : PASS"
    )

else:

    print(
        "❌ GLOBAL CLIP COUNT : FAIL"
    )

    global_mapping_pass = False


# ==============================================================================
# 6. VERIFY EACH VIDEO
# ==============================================================================

print()
print("=" * 78)
print("VERIFY VIDEO-SPECIFIC GLOBAL MAPPING")
print("=" * 78)


video_results = []


for video_id in VIDEO_IDS:

    print()
    print("=" * 78)
    print(f"VIDEO : {video_id}")
    print("=" * 78)

    df = PHASE65_METADATA[
        video_id
    ].copy()


    # --------------------------------------------------------------------------
    # Expected count
    # --------------------------------------------------------------------------

    expected_count = (
        EXPECTED_CLIPS[video_id]
    )

    actual_count = len(df)

    count_ok = (
        actual_count
        == expected_count
    )

    print(
        "Clip count :",
        "PASS"
        if count_ok
        else
        (
            f"FAIL "
            f"(actual={actual_count:,}, "
            f"expected={expected_count:,})"
        )
    )


    if not count_ok:

        global_mapping_pass = False


    # --------------------------------------------------------------------------
    # Video consistency
    # --------------------------------------------------------------------------

    video_values = (
        df["video"]
        .astype(str)
        .str.strip()
    )

    wrong_video = int(
        (
            video_values
            != video_id
        ).sum()
    )

    print(
        "Video consistency :",
        "PASS"
        if wrong_video == 0
        else f"FAIL ({wrong_video:,})"
    )

    if wrong_video:

        global_mapping_pass = False


    # --------------------------------------------------------------------------
    # Clip ID uniqueness within video
    # --------------------------------------------------------------------------

    duplicate_clip_ids = int(
        df["clip_id"]
        .astype(str)
        .str.strip()
        .duplicated()
        .sum()
    )

    print(
        "Local clip ID uniqueness :",
        "PASS"
        if duplicate_clip_ids == 0
        else f"FAIL ({duplicate_clip_ids:,})"
    )

    if duplicate_clip_ids:

        global_mapping_pass = False


    # --------------------------------------------------------------------------
    # Expected clip ID range
    #
    # Phase 6 v4:
    #
    # video001_clip_000000
    # ...
    # video001_clip_040075
    #
    # --------------------------------------------------------------------------

    expected_prefix = (
        f"{video_id}_clip_"
    )

    clip_ids = (
        df["clip_id"]
        .astype(str)
        .str.strip()
    )


    wrong_prefix = int(
        (
            ~clip_ids.str.startswith(
                expected_prefix
            )
        ).sum()
    )


    print(
        "Clip ID prefix :",
        "PASS"
        if wrong_prefix == 0
        else f"FAIL ({wrong_prefix:,})"
    )


    if wrong_prefix:

        global_mapping_pass = False


    # --------------------------------------------------------------------------
    # Extract numeric clip index
    # --------------------------------------------------------------------------

    numeric_clip_index = pd.to_numeric(
        clip_ids.str.extract(
            r"_clip_(\d+)$",
            expand=False
        ),
        errors="coerce"
    )


    invalid_clip_index = int(
        numeric_clip_index.isna().sum()
    )


    print(
        "Clip ID numeric index :",
        "PASS"
        if invalid_clip_index == 0
        else f"FAIL ({invalid_clip_index:,})"
    )


    if invalid_clip_index:

        global_mapping_pass = False


    # --------------------------------------------------------------------------
    # Verify clip indices form complete range
    # --------------------------------------------------------------------------

    expected_indices = set(
        range(
            expected_count
        )
    )

    actual_indices = set(
        numeric_clip_index.dropna()
        .astype(int)
        .tolist()
    )


    missing_indices = sorted(
        expected_indices
        - actual_indices
    )

    extra_indices = sorted(
        actual_indices
        - expected_indices
    )


    print(
        "Missing clip indices :",
        f"{len(missing_indices):,}"
    )

    print(
        "Extra clip indices   :",
        f"{len(extra_indices):,}"
    )


    range_ok = (
        not missing_indices
        and not extra_indices
        and len(actual_indices)
        == expected_count
    )


    print(
        "Clip index continuity :",
        "PASS"
        if range_ok
        else "FAIL"
    )


    if not range_ok:

        global_mapping_pass = False


        if missing_indices:

            print(
                "First missing:",
                missing_indices[:10]
            )

        if extra_indices:

            print(
                "First extra:",
                extra_indices[:10]
            )


    # --------------------------------------------------------------------------
    # Verify metadata ordering
    #
    # The expected ordering is:
    #
    # clip_000000
    # clip_000001
    # clip_000002
    # ...
    # --------------------------------------------------------------------------

    ordering_ok = (
        numeric_clip_index
        .is_monotonic_increasing
    )


    print(
        "Clip ordering :",
        "PASS"
        if ordering_ok
        else "FAIL"
    )


    if not ordering_ok:

        global_mapping_pass = False


    # --------------------------------------------------------------------------
    # Verify shard_index is numeric
    # --------------------------------------------------------------------------

    shard_index = pd.to_numeric(
        df["shard_index"],
        errors="coerce"
    )


    invalid_shard_index = int(
        shard_index.isna().sum()
    )


    print(
        "Shard index validity :",
        "PASS"
        if invalid_shard_index == 0
        else f"FAIL ({invalid_shard_index:,})"
    )


    if invalid_shard_index:

        global_mapping_pass = False


    # --------------------------------------------------------------------------
    # Verify start/end frame
    # --------------------------------------------------------------------------

    start_frame = pd.to_numeric(
        df["start_frame"],
        errors="coerce"
    )

    end_frame = pd.to_numeric(
        df["end_frame"],
        errors="coerce"
    )


    invalid_frames = int(
        (
            start_frame.isna()
            |
            end_frame.isna()
        ).sum()
    )


    invalid_range = int(
        (
            end_frame
            <= start_frame
        ).sum()
    )


    print(
        "Frame values :",
        "PASS"
        if invalid_frames == 0
        else f"FAIL ({invalid_frames:,})"
    )

    print(
        "Frame ranges :",
        "PASS"
        if invalid_range == 0
        else f"FAIL ({invalid_range:,})"
    )


    if invalid_frames or invalid_range:

        global_mapping_pass = False


    # --------------------------------------------------------------------------
    # Store result
    # --------------------------------------------------------------------------

    video_pass = (
        count_ok
        and wrong_video == 0
        and duplicate_clip_ids == 0
        and wrong_prefix == 0
        and invalid_clip_index == 0
        and range_ok
        and ordering_ok
        and invalid_shard_index == 0
        and invalid_frames == 0
        and invalid_range == 0
    )


    video_results.append({
        "video_id": video_id,
        "actual_clips": actual_count,
        "expected_clips": expected_count,
        "duplicate_clip_ids": duplicate_clip_ids,
        "wrong_video": wrong_video,
        "wrong_prefix": wrong_prefix,
        "invalid_clip_index": invalid_clip_index,
        "missing_indices": len(missing_indices),
        "extra_indices": len(extra_indices),
        "invalid_shard_index": invalid_shard_index,
        "invalid_frames": invalid_frames,
        "invalid_frame_ranges": invalid_range,
        "status": (
            "PASS"
            if video_pass
            else "FAIL"
        ),
    })


# ==============================================================================
# 7. VERIFY GLOBAL CLIP ORDER ACROSS VIDEOS
# ==============================================================================

print()
print("=" * 78)
print("VERIFY GLOBAL VIDEO → CLIP ORDER")
print("=" * 78)


global_order_ok = True


for video_id in VIDEO_IDS:

    df = PHASE65_METADATA[
        video_id
    ]

    clip_ids = (
        df["clip_id"]
        .astype(str)
        .str.strip()
    )


    if len(clip_ids) == 0:

        global_order_ok = False

        print(
            video_id,
            ": ❌ EMPTY"
        )

        continue


    first_id = clip_ids.iloc[0]

    last_id = clip_ids.iloc[-1]


    expected_first = (
        f"{video_id}_clip_000000"
    )

    expected_last = (
        f"{video_id}_clip_{EXPECTED_CLIPS[video_id]-1:06d}"
    )


    first_ok = (
        first_id
        == expected_first
    )

    last_ok = (
        last_id
        == expected_last
    )


    print()
    print(video_id)

    print(
        "First:",
        first_id,
        "→",
        "PASS"
        if first_ok
        else f"FAIL (expected {expected_first})"
    )

    print(
        "Last :",
        last_id,
        "→",
        "PASS"
        if last_ok
        else f"FAIL (expected {expected_last})"
    )


    if not first_ok or not last_ok:

        global_order_ok = False


print()

if global_order_ok:

    print(
        "✅ GLOBAL VIDEO → CLIP ORDER : PASS"
    )

else:

    print(
        "❌ GLOBAL VIDEO → CLIP ORDER : FAIL"
    )

    global_mapping_pass = False


# ==============================================================================
# 8. FINAL RESULT TABLE
# ==============================================================================

print()
print("=" * 78)
print("CELL 10 RESULT TABLE")
print("=" * 78)


results_df = pd.DataFrame(
    video_results
)


if len(results_df):

    print(
        results_df.to_string(
            index=False
        )
    )


# ==============================================================================
# 9. FINAL
# ==============================================================================

print()
print("=" * 78)
print("CELL 10 FINAL RESULT")
print("=" * 78)


if global_mapping_pass:

    print(
        "✅ CELL 10 — GLOBAL CLIP MAPPING : PASS"
    )

    print()
    print(
        "Phase 6 v4 metadata is globally consistent."
    )

    print(
        "video001 + video002 + video003 are present."
    )

    print(
        f"Total clips : {total_clip_ids:,}"
    )

    print(
        "No files were modified."
    )

else:

    print(
        "❌ CELL 10 — GLOBAL CLIP MAPPING : FAIL"
    )

    print()
    print(
        "Review the failed checks above."
    )

    print(
        "No files were modified."
    )


print()
print("=" * 78)
print("CELL 10 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 10
VERIFY GLOBAL CLIP MAPPING — PHASE 6 v4
==============================================================================

------------------------------------------------------------------------------
video001
------------------------------------------------------------------------------
Metadata: C:\LipReadingSSL\output\video001\clip_metadata.csv
Rows: 40,076
Schema: PASS

------------------------------------------------------------------------------
video002
------------------------------------------------------------------------------
Metadata: C:\LipReadingSSL\output\video002\clip_metadata.csv
Rows: 31,662
Schema: PASS

------------------------------------------------------------------------------
video003
------------------------------------------------------------------------------
Metadata: C:\LipReadingSSL\output\video003\clip_metadata.csv
Rows: 26,273
Schema: PASS

==============================================================================
CHECK GLOBAL CLIP ID UNIQUENESS
==============================================================================
Total clip IDs  : 98,011
Unique clip IDs : 40,076
Duplicates      : 57,935
❌ GLOBAL CLIP ID UNIQUENESS : FAIL

==============================================================================
GLOBAL CLIP COUNT
==============================================================================
Expected : 98,011
Actual   : 98,011
✅ GLOBAL CLIP COUNT : PASS

==============================================================================
VERIFY VIDEO-SPECIFIC GLOBAL MAPPING
==============================================================================

==============================================================================
VIDEO : video001
==============================================================================
Clip count : PASS
Video consistency : PASS
Local clip ID uniqueness : PASS
Clip ID prefix : FAIL (40,076)
Clip ID numeric index : FAIL (40,076)
Missing clip indices : 40,076
Extra clip indices   : 0
Clip index continuity : FAIL
First missing: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Clip ordering : FAIL
Shard index validity : PASS
Frame values : PASS
Frame ranges : PASS

==============================================================================
VIDEO : video002
==============================================================================
Clip count : PASS
Video consistency : PASS
Local clip ID uniqueness : PASS
Clip ID prefix : FAIL (31,662)
Clip ID numeric index : FAIL (31,662)
Missing clip indices : 31,662
Extra clip indices   : 0
Clip index continuity : FAIL
First missing: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Clip ordering : FAIL
Shard index validity : PASS
Frame values : PASS
Frame ranges : PASS

==============================================================================
VIDEO : video003
==============================================================================
Clip count : PASS
Video consistency : PASS
Local clip ID uniqueness : PASS
Clip ID prefix : FAIL (26,273)
Clip ID numeric index : FAIL (26,273)
Missing clip indices : 26,273
Extra clip indices   : 0
Clip index continuity : FAIL
First missing: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Clip ordering : FAIL
Shard index validity : PASS
Frame values : PASS
Frame ranges : PASS

==============================================================================
VERIFY GLOBAL VIDEO → CLIP ORDER
==============================================================================

video001
First: 0 → FAIL (expected video001_clip_000000)
Last : 40075 → FAIL (expected video001_clip_040075)

video002
First: 0 → FAIL (expected video002_clip_000000)
Last : 31661 → FAIL (expected video002_clip_031661)

video003
First: 0 → FAIL (expected video003_clip_000000)
Last : 26272 → FAIL (expected video003_clip_026272)

❌ GLOBAL VIDEO → CLIP ORDER : FAIL

==============================================================================
CELL 10 RESULT TABLE
==============================================================================
video_id  actual_clips  expected_clips  duplicate_clip_ids  wrong_video  wrong_prefix  invalid_clip_index  missing_indices  extra_indices  invalid_shard_index  invalid_frames  invalid_frame_ranges status
video001         40076           40076                   0            0         40076               40076            40076              0                    0               0                     0   FAIL
video002         31662           31662                   0            0         31662               31662            31662              0                    0               0                     0   FAIL
video003         26273           26273                   0            0         26273               26273            26273              0                    0               0                     0   FAIL

==============================================================================
CELL 10 FINAL RESULT
==============================================================================
❌ CELL 10 — GLOBAL CLIP MAPPING : FAIL

Review the failed checks above.
No files were modified.

==============================================================================
CELL 10 COMPLETE — READ ONLY
==============================================================================

In [17]:
# ============================================================
# PHASE 6.5 — CELL 11
# SAMPLE INSPECTION
#
# READ ONLY
# ============================================================

print("=" * 78)
print("PHASE 6.5 — CELL 11")
print("SAMPLE INSPECTION")
print("=" * 78)


for video_id in VIDEO_IDS:

    df = PHASE65_METADATA[
        video_id
    ]


    print()
    print(
        "=" * 78
    )
    print(
        f"{video_id} — FIRST 5"
    )
    print(
        "=" * 78
    )

    display(
        df.head(5)
    )


    print()
    print(
        f"{video_id} — LAST 5"
    )

    display(
        df.tail(5)
    )


print()
print("=" * 78)
print("CELL 11 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 11
SAMPLE INSPECTION
==============================================================================

==============================================================================
video001 — FIRST 5
==============================================================================

   clip_id     video             shard  shard_index  start_frame  end_frame
0        0  video001  shard_000000.npz            0            0         15
1        1  video001  shard_000000.npz            1            1         16
2        2  video001  shard_000000.npz            2            2         17
3        3  video001  shard_000000.npz            3            3         18
4        4  video001  shard_000000.npz            4            4         19

video001 — LAST 5

,clip_id,video,shard,shard_index,start_frame,end_frame
40071,40071,video001,shard_000078.npz,135,43256,43271
40072,40072,video001,shard_000078.npz,136,43257,43272
40073,40073,video001,shard_000078.npz,137,43258,43273
40074,40074,video001,shard_000078.npz,138,43259,43274
40075,40075,video001,shard_000078.npz,139,43260,43275

==============================================================================
video002 — FIRST 5
==============================================================================

   clip_id     video             shard  shard_index  start_frame  end_frame
0        0  video002  shard_000000.npz            0            0         15
1        1  video002  shard_000000.npz            1            1         16
2        2  video002  shard_000000.npz            2            2         17
3        3  video002  shard_000000.npz            3            3         18
4        4  video002  shard_000000.npz            4            4         19

video002 — LAST 5

,clip_id,video,shard,shard_index,start_frame,end_frame
31657,31657,video002,shard_000061.npz,425,39203,39218
31658,31658,video002,shard_000061.npz,426,39204,39219
31659,31659,video002,shard_000061.npz,427,39205,39220
31660,31660,video002,shard_000061.npz,428,39206,39221
31661,31661,video002,shard_000061.npz,429,39207,39222

==============================================================================
video003 — FIRST 5
==============================================================================

   clip_id     video             shard  shard_index  start_frame  end_frame
0        0  video003  shard_000000.npz            0            0         15
1        1  video003  shard_000000.npz            1            1         16
2        2  video003  shard_000000.npz            2            2         17
3        3  video003  shard_000000.npz            3            3         18
4        4  video003  shard_000000.npz            4            4         19

video003 — LAST 5

,clip_id,video,shard,shard_index,start_frame,end_frame
26268,26268,video003,shard_000051.npz,156,42576,42591
26269,26269,video003,shard_000051.npz,157,42577,42592
26270,26270,video003,shard_000051.npz,158,42578,42593
26271,26271,video003,shard_000051.npz,159,42579,42594
26272,26272,video003,shard_000051.npz,160,42580,42595

==============================================================================
CELL 11 COMPLETE — READ ONLY
==============================================================================

In [18]:
# ============================================================
# PHASE 6.5 — CELL 12
# SEARCH POSSIBLE ANNOTATION / TRANSCRIPT SOURCES
#
# READ ONLY
#
# DOES NOT MODIFY FILES
# ============================================================

print("=" * 78)
print("PHASE 6.5 — CELL 12")
print("SEARCH POSSIBLE ANNOTATION / TRANSCRIPT SOURCES")
print("=" * 78)


ANNOTATION_EXTENSIONS = {
    ".csv",
    ".txt",
    ".tsv",
    ".json",
    ".jsonl",
    ".xml",
    ".vtt",
    ".srt",
    ".pkl",
    ".xlsx",
}


ANNOTATION_KEYWORDS = [
    "annotation",
    "annotat",
    "label",
    "labels",
    "transcript",
    "transcripts",
    "sentence",
    "sentences",
    "subtitle",
    "subtitles",
    "caption",
    "captions",
    "utterance",
    "vocabulary",
    "lexicon",
]


EXCLUDE_PARTS = {
    "venv310",
    ".git",
    "__pycache__",
    "site-packages",
}


possible_files = []


for root in SOURCE_SEARCH_ROOTS:

    if not root.exists():
        continue


    for path in root.rglob("*"):

        if not path.is_file():
            continue


        if path.suffix.lower() not in (
            ANNOTATION_EXTENSIONS
        ):
            continue


        if any(
            excluded.lower()
            in {
                part.lower()
                for part in path.parts
            }
            for excluded in EXCLUDE_PARTS
        ):
            continue


        filename_lower = (
            path.name.lower()
        )


        keyword_hits = [
            keyword
            for keyword in ANNOTATION_KEYWORDS
            if keyword in filename_lower
        ]


        if keyword_hits:

            possible_files.append({
                "path": str(path),
                "extension": path.suffix.lower(),
                "keyword_hits": ", ".join(
                    keyword_hits
                ),
                "size_bytes": path.stat().st_size,
            })


ANNOTATION_CANDIDATES_DF = pd.DataFrame(
    possible_files
)


if ANNOTATION_CANDIDATES_DF.empty:

    print(
        "No filename-based annotation candidates found."
    )

else:

    ANNOTATION_CANDIDATES_DF = (
        ANNOTATION_CANDIDATES_DF
        .sort_values(
            [
                "keyword_hits",
                "path",
            ]
        )
        .reset_index(drop=True)
    )


    print(
        "Potential annotation files :",
        len(
            ANNOTATION_CANDIDATES_DF
        )
    )


    display(
        ANNOTATION_CANDIDATES_DF
    )


print()
print("=" * 78)
print("CELL 12 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 12
SEARCH POSSIBLE ANNOTATION / TRANSCRIPT SOURCES
==============================================================================
Potential annotation files : 14

,path,extension,keyword_hits,size_bytes
0,C:\LipReadingSSL\output\dataset\analysis\label...,.csv,label,13073625
1,C:\LipReadingSSL\output\dataset\labels.csv,.csv,"label, labels",3437915
2,C:\LipReadingSSL\output\dataset\analysis\distr...,.csv,sentence,36
3,C:\LipReadingSSL\output\dataset\vocabulary\sen...,.csv,sentence,25
4,C:\LipReadingSSL\output\dataset\analysis\vocab...,.csv,"sentence, vocabulary",25
5,C:\LipReadingSSL\output\dataset\analysis\vocab...,.csv,vocabulary,22
6,C:\LipReadingSSL\output\dataset\analysis\vocab...,.json,vocabulary,135
7,C:\LipReadingSSL\output\dataset\analysis\vocab...,.csv,vocabulary,134
8,C:\LipReadingSSL\output\dataset\analysis\vocab...,.csv,vocabulary,27
9,C:\LipReadingSSL\output\dataset\analysis\vocab...,.csv,vocabulary,45
10,C:\LipReadingSSL\output\dataset\analysis\vocab...,.csv,vocabulary,52
11,C:\LipReadingSSL\output\dataset\analysis\vocab...,.csv,vocabulary,36
12,C:\LipReadingSSL\output\dataset\analysis\vocab...,.csv,vocabulary,98
13,C:\LipReadingSSL\output\dataset\vocabulary\voc...,.csv,vocabulary,91

==============================================================================
CELL 12 COMPLETE — READ ONLY
==============================================================================

In [19]:
# ============================================================
# PHASE 6.5 — CELL 13
# CONTENT-LEVEL ANNOTATION SOURCE SEARCH
#
# READ ONLY
# ============================================================

print("=" * 78)
print("PHASE 6.5 — CELL 13")
print("CONTENT-LEVEL ANNOTATION SOURCE SEARCH")
print("=" * 78)


CONTENT_SEARCH_EXTENSIONS = {
    ".csv",
    ".txt",
    ".tsv",
    ".json",
    ".jsonl",
    ".xml",
    ".vtt",
    ".srt",
}


SEARCH_TERMS = [
    "video001",
    "video002",
    "video003",
    "transcript",
    "sentence_id",
    "speaker_id",
    "start_frame",
    "end_frame",
    "start_time",
    "end_time",
]


content_results = []


candidate_paths = []


if (
    not ANNOTATION_CANDIDATES_DF.empty
):

    candidate_paths = [
        Path(path)
        for path in
        ANNOTATION_CANDIDATES_DF[
            "path"
        ]
    ]


for path in candidate_paths:

    if not path.exists():
        continue


    if (
        path.suffix.lower()
        not in CONTENT_SEARCH_EXTENSIONS
    ):
        continue


    try:

        if path.stat().st_size > 100_000_000:
            continue


        text = path.read_text(
            encoding="utf-8",
            errors="ignore"
        )


    except Exception:

        continue


    text_lower = text.lower()


    hits = [
        term
        for term in SEARCH_TERMS
        if term.lower()
        in text_lower
    ]


    if hits:

        content_results.append({
            "path": str(path),
            "matched_terms": ", ".join(hits),
            "has_video001": "video001" in text_lower,
            "has_video002": "video002" in text_lower,
            "has_video003": "video003" in text_lower,
            "has_transcript": "transcript" in text_lower,
            "has_sentence_id": "sentence_id" in text_lower,
            "has_speaker_id": "speaker_id" in text_lower,
            "has_frame_alignment": (
                "start_frame" in text_lower
                and "end_frame" in text_lower
            ),
        })


CONTENT_SEARCH_DF = pd.DataFrame(
    content_results
)


if CONTENT_SEARCH_DF.empty:

    print(
        "No content-level annotation candidates found."
    )

else:

    display(
        CONTENT_SEARCH_DF
    )


print()
print("=" * 78)
print("CELL 13 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 13
CONTENT-LEVEL ANNOTATION SOURCE SEARCH
==============================================================================

,path,matched_terms,has_video001,has_video002,has_video003,has_transcript,has_sentence_id,has_speaker_id,has_frame_alignment
0,C:\LipReadingSSL\output\dataset\analysis\label...,"video001, video002, transcript, sentence_id, s...",True,True,False,True,True,True,True
1,C:\LipReadingSSL\output\dataset\labels.csv,"video001, video002, transcript, sentence_id, s...",True,True,False,True,True,True,False
2,C:\LipReadingSSL\output\dataset\vocabulary\sen...,sentence_id,False,False,False,False,True,False,False
3,C:\LipReadingSSL\output\dataset\analysis\vocab...,sentence_id,False,False,False,False,True,False,False
4,C:\LipReadingSSL\output\dataset\analysis\vocab...,"video001, video002",True,True,False,False,False,False,False

==============================================================================
CELL 13 COMPLETE — READ ONLY
==============================================================================

In [20]:
# ==============================================================================
# PHASE 6.5 — CELL 14
# INSPECT POSSIBLE REAL ANNOTATION SOURCE
# READ-ONLY
# ==============================================================================

from pathlib import Path
import pandas as pd

LABEL_QA_PATH = Path(
    r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
)

print("=" * 78)
print("PHASE 6.5 — CELL 14")
print("INSPECT POSSIBLE REAL ANNOTATION SOURCE")
print("=" * 78)

print(f"Path   : {LABEL_QA_PATH}")
print(f"Exists : {LABEL_QA_PATH.exists()}")

if not LABEL_QA_PATH.exists():
    raise FileNotFoundError(
        f"Annotation candidate not found:\n{LABEL_QA_PATH}"
    )

df = pd.read_csv(LABEL_QA_PATH)

print()
print("-" * 78)
print("SCHEMA")
print("-" * 78)

print(f"Rows : {len(df):,}")

print("Columns:")
for col in df.columns:
    print(f" - {col}")

print()
print("-" * 78)
print("FIRST 10 ROWS")
print("-" * 78)

print(df.head(10).to_string(index=False))

print()
print("-" * 78)
print("VIDEO DISTRIBUTION")
print("-" * 78)

for col in ["video", "video_id"]:
    if col in df.columns:
        print(f"\nColumn: {col}")
        print(df[col].value_counts(dropna=False).to_string())

print()
print("-" * 78)
print("TRANSCRIPT SAMPLE")
print("-" * 78)

if "transcript" in df.columns:
    print(
        df["transcript"]
        .dropna()
        .astype(str)
        .head(20)
        .to_string(index=False)
    )
else:
    print("transcript column not found")

print()
print("-" * 78)
print("SENTENCE ID SAMPLE")
print("-" * 78)

if "sentence_id" in df.columns:
    print(
        df["sentence_id"]
        .dropna()
        .head(20)
        .to_string(index=False)
    )
else:
    print("sentence_id column not found")

print()
print("-" * 78)
print("FRAME-RELATED COLUMNS")
print("-" * 78)

frame_cols = [
    c for c in df.columns
    if any(
        key in c.lower()
        for key in [
            "frame",
            "start",
            "end",
            "clip",
            "align",
            "time"
        ]
    )
]

for col in frame_cols:
    print(f" - {col}")

print()
print("=" * 78)
print("CELL 14 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 14
INSPECT POSSIBLE REAL ANNOTATION SOURCE
==============================================================================
Path   : C:\LipReadingSSL\output\dataset\analysis\label_qa.csv
Exists : True

------------------------------------------------------------------------------
SCHEMA
------------------------------------------------------------------------------
Rows : 81,853
Columns:
 - dataset_id
 - video_id
 - clip_id
 - clip_path
 - frame_folder
 - start_frame
 - end_frame
 - num_frames
 - clip_length
 - stride
 - speaker_id
 - sentence_id
 - transcript
 - normalized_text
 - language
 - verified
 - clip_exists
 - frame_exists
 - has_transcript
 - text_length

------------------------------------------------------------------------------
FIRST 10 ROWS
------------------------------------------------------------------------------
 dataset_id video_id     clip_id                         clip_path               frame_folder  start_frame  end_frame  num_frames  clip_length  stride speaker_id  sentence_id  transcript  normalized_text language  verified  clip_exists  frame_exists  has_transcript  text_length
          1 video001 clip_000001 video001\clip_npy\clip_000001.npy video001\clips\clip_000001            0         25          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0
          2 video001 clip_000002 video001\clip_npy\clip_000002.npy video001\clips\clip_000002            0         26          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0
          3 video001 clip_000003 video001\clip_npy\clip_000003.npy video001\clips\clip_000003            1         27          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0
          4 video001 clip_000004 video001\clip_npy\clip_000004.npy video001\clips\clip_000004            2         28          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0
          5 video001 clip_000005 video001\clip_npy\clip_000005.npy video001\clips\clip_000005            3         29          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0
          6 video001 clip_000006 video001\clip_npy\clip_000006.npy video001\clips\clip_000006            4         30          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0
          7 video001 clip_000007 video001\clip_npy\clip_000007.npy video001\clips\clip_000007            5         31          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0
          8 video001 clip_000008 video001\clip_npy\clip_000008.npy video001\clips\clip_000008            6         32          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0
          9 video001 clip_000009 video001\clip_npy\clip_000009.npy video001\clips\clip_000009            7         33          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0
         10 video001 clip_000010 video001\clip_npy\clip_000010.npy video001\clips\clip_000010            8         33          29         29.0       1    UNKNOWN          NaN         NaN              NaN       th     False        False         False           False            0

------------------------------------------------------------------------------
VIDEO DISTRIBUTION
------------------------------------------------------------------------------

Column: video_id
video_id
video001    42993
video002    38860

------------------------------------------------------------------------------
TRANSCRIPT SAMPLE
------------------------------------------------------------------------------
Series([], )

------------------------------------------------------------------------------
SENTENCE ID SAMPLE
------------------------------------------------------------------------------
Series([], )

------------------------------------------------------------------------------
FRAME-RELATED COLUMNS
------------------------------------------------------------------------------
 - clip_id
 - clip_path
 - frame_folder
 - start_frame
 - end_frame
 - num_frames
 - clip_length
 - clip_exists
 - frame_exists

==============================================================================
CELL 14 COMPLETE — READ ONLY
==============================================================================

In [21]:
# ==============================================================================
# PHASE 6.5 — CELL 15
# ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4
# READ-ONLY
# ==============================================================================

import pandas as pd
from pathlib import Path

LABEL_QA_PATH = Path(
    r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
)

EXPECTED_CLIPS = {
    "video001": 40076,
    "video002": 31662,
    "video003": 26273,
}

df = pd.read_csv(LABEL_QA_PATH)

print("=" * 78)
print("PHASE 6.5 — CELL 15")
print("ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4")
print("=" * 78)

print()
print("Total label_qa rows :", f"{len(df):,}")

# ------------------------------------------------------------------------------
# VIDEO DISTRIBUTION
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("VIDEO DISTRIBUTION")
print("-" * 78)

video_counts = (
    df["video_id"]
    .astype(str)
    .value_counts()
)

for video_id, expected in EXPECTED_CLIPS.items():

    actual = int(
        video_counts.get(video_id, 0)
    )

    print(
        f"{video_id}: "
        f"label_qa={actual:,} | "
        f"phase6={expected:,} | "
        f"difference={actual - expected:+,}"
    )

# ------------------------------------------------------------------------------
# CLIP ID SAMPLE
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("CLIP ID SAMPLE")
print("-" * 78)

print(
    df[
        [
            "video_id",
            "clip_id",
            "start_frame",
            "end_frame",
            "speaker_id",
            "sentence_id",
            "transcript",
        ]
    ]
    .head(20)
    .to_string(index=False)
)

# ------------------------------------------------------------------------------
# CLIP ID FORMAT
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("CLIP ID FORMAT")
print("-" * 78)

clip_ids = (
    df["clip_id"]
    .astype(str)
    .str.strip()
)

print("First 20 clip IDs:")
for x in clip_ids.head(20):
    print(" ", x)

# ------------------------------------------------------------------------------
# VIDEO003
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("VIDEO003 CHECK")
print("-" * 78)

video003 = df[
    df["video_id"].astype(str).str.strip()
    == "video003"
]

print(
    "video003 rows :",
    f"{len(video003):,}"
)

if len(video003) == 0:
    print(
        "❌ label_qa has NO video003"
    )
else:
    print(
        "✅ label_qa contains video003"
    )

# ------------------------------------------------------------------------------
# TRANSCRIPT
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("TRANSCRIPT STATUS")
print("-" * 78)

transcript = df["transcript"]

non_empty = (
    transcript
    .notna()
    &
    transcript.astype(str).str.strip().ne("")
)

print(
    "Non-empty :",
    f"{int(non_empty.sum()):,}"
)

print(
    "Empty     :",
    f"{int((~non_empty).sum()):,}"
)

print(
    "Unique    :",
    f"{transcript[non_empty].astype(str).nunique():,}"
)

# ------------------------------------------------------------------------------
# SPEAKER
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("SPEAKER STATUS")
print("-" * 78)

speaker = (
    df["speaker_id"]
    .astype(str)
    .str.strip()
)

print(
    "Unique speakers:",
    speaker.nunique()
)

print(
    speaker.value_counts().head(20).to_string()
)

# ------------------------------------------------------------------------------
# SENTENCE
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("SENTENCE STATUS")
print("-" * 78)

sentence = (
    df["sentence_id"]
    .astype(str)
    .str.strip()
)

valid_sentence = (
    sentence
    .ne("")
    &
    sentence
    .ne("nan")
)

print(
    "Non-empty sentence_id:",
    f"{int(valid_sentence.sum()):,}"
)

print(
    "Unique sentence_id:",
    f"{sentence[valid_sentence].nunique():,}"
)

# ------------------------------------------------------------------------------
# FRAME RANGE
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("FRAME RANGE STATUS")
print("-" * 78)

start = pd.to_numeric(
    df["start_frame"],
    errors="coerce"
)

end = pd.to_numeric(
    df["end_frame"],
    errors="coerce"
)

print(
    "Invalid start_frame:",
    f"{int(start.isna().sum()):,}"
)

print(
    "Invalid end_frame:",
    f"{int(end.isna().sum()):,}"
)

print(
    "Invalid frame range:",
    f"{int((end <= start).sum()):,}"
)

# ------------------------------------------------------------------------------
# DUPLICATE CLIP IDs
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("DUPLICATE CLIP IDs")
print("-" * 78)

duplicate_ids = (
    clip_ids
    .duplicated()
)

print(
    "Duplicate rows:",
    f"{int(duplicate_ids.sum()):,}"
)

# ------------------------------------------------------------------------------
# FINAL
# ------------------------------------------------------------------------------

print()
print("=" * 78)
print("CELL 15 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 15
ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4
==============================================================================

Total label_qa rows : 81,853

------------------------------------------------------------------------------
VIDEO DISTRIBUTION
------------------------------------------------------------------------------
video001: label_qa=42,993 | phase6=40,076 | difference=+2,917
video002: label_qa=38,860 | phase6=31,662 | difference=+7,198
video003: label_qa=0 | phase6=26,273 | difference=-26,273

------------------------------------------------------------------------------
CLIP ID SAMPLE
------------------------------------------------------------------------------
video_id     clip_id  start_frame  end_frame speaker_id  sentence_id  transcript
video001 clip_000001            0         25    UNKNOWN          NaN         NaN
video001 clip_000002            0         26    UNKNOWN          NaN         NaN
video001 clip_000003            1         27    UNKNOWN          NaN         NaN
video001 clip_000004            2         28    UNKNOWN          NaN         NaN
video001 clip_000005            3         29    UNKNOWN          NaN         NaN
video001 clip_000006            4         30    UNKNOWN          NaN         NaN
video001 clip_000007            5         31    UNKNOWN          NaN         NaN
video001 clip_000008            6         32    UNKNOWN          NaN         NaN
video001 clip_000009            7         33    UNKNOWN          NaN         NaN
video001 clip_000010            8         33    UNKNOWN          NaN         NaN
video001 clip_000011            9         34    UNKNOWN          NaN         NaN
video001 clip_000012           10         35    UNKNOWN          NaN         NaN
video001 clip_000013           11         36    UNKNOWN          NaN         NaN
video001 clip_000014           11         37    UNKNOWN          NaN         NaN
video001 clip_000015           12         38    UNKNOWN          NaN         NaN
video001 clip_000016           13         39    UNKNOWN          NaN         NaN
video001 clip_000017           14         40    UNKNOWN          NaN         NaN
video001 clip_000018           15         41    UNKNOWN          NaN         NaN
video001 clip_000019           16         42    UNKNOWN          NaN         NaN
video001 clip_000020           17         43    UNKNOWN          NaN         NaN

------------------------------------------------------------------------------
CLIP ID FORMAT
------------------------------------------------------------------------------
First 20 clip IDs:
  clip_000001
  clip_000002
  clip_000003
  clip_000004
  clip_000005
  clip_000006
  clip_000007
  clip_000008
  clip_000009
  clip_000010
  clip_000011
  clip_000012
  clip_000013
  clip_000014
  clip_000015
  clip_000016
  clip_000017
  clip_000018
  clip_000019
  clip_000020

------------------------------------------------------------------------------
VIDEO003 CHECK
------------------------------------------------------------------------------
video003 rows : 0
❌ label_qa has NO video003

------------------------------------------------------------------------------
TRANSCRIPT STATUS
------------------------------------------------------------------------------
Non-empty : 0
Empty     : 81,853
Unique    : 0

------------------------------------------------------------------------------
SPEAKER STATUS
------------------------------------------------------------------------------
Unique speakers: 1
speaker_id
UNKNOWN    81853

------------------------------------------------------------------------------
SENTENCE STATUS
------------------------------------------------------------------------------
Non-empty sentence_id: 0
Unique sentence_id: 0

------------------------------------------------------------------------------
FRAME RANGE STATUS
------------------------------------------------------------------------------
Invalid start_frame: 0
Invalid end_frame: 0
Invalid frame range: 0

------------------------------------------------------------------------------
DUPLICATE CLIP IDs
------------------------------------------------------------------------------
Duplicate rows: 38,860

==============================================================================
CELL 15 COMPLETE — READ ONLY
==============================================================================

In [22]:
# ==============================================================================
# PHASE 6.5 — CELL 16
# TRACE LABEL_QA CREATION SOURCE
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json
import re

PROJECT_ROOT = Path(r"C:\LipReadingSSL")
NOTEBOOK_DIR = PROJECT_ROOT / "notebooks"

SEARCH_TERMS = [
    "label_qa",
    "labels.csv",
    "transcript",
    "sentence_id",
    "speaker_id",
    "start_frame",
    "end_frame",
    "to_csv",
    "label",
    "annotation",
]

print("=" * 78)
print("PHASE 6.5 — CELL 16")
print("TRACE LABEL_QA CREATION SOURCE")
print("=" * 78)

print()
print("Notebook directory:")
print(NOTEBOOK_DIR)

notebooks = sorted(
    NOTEBOOK_DIR.glob("*.ipynb")
)

print()
print(f"Notebooks found : {len(notebooks)}")

for nb in notebooks:
    print(f" - {nb.name}")

print()
print("=" * 78)
print("SEARCH RESULTS")
print("=" * 78)

results = []

for nb_path in notebooks:

    try:
        with open(
            nb_path,
            "r",
            encoding="utf-8"
        ) as f:
            nb = json.load(f)

    except Exception as e:

        print()
        print(f"ERROR reading {nb_path.name}: {e}")
        continue

    cells = nb.get("cells", [])

    for cell_index, cell in enumerate(cells):

        source = "".join(
            cell.get("source", [])
        )

        source_lower = source.lower()

        matched_terms = []

        for term in SEARCH_TERMS:

            if term.lower() in source_lower:
                matched_terms.append(term)

        if not matched_terms:
            continue

        results.append({
            "notebook": nb_path.name,
            "cell_index": cell_index,
            "terms": matched_terms,
            "source": source,
        })

        print()
        print("-" * 78)
        print(
            f"NOTEBOOK : {nb_path.name}"
        )
        print(
            f"CELL     : {cell_index}"
        )
        print(
            "MATCHED  :",
            ", ".join(matched_terms)
        )
        print("-" * 78)

        lines = source.splitlines()

        for line_number, line in enumerate(lines, start=1):

            if any(
                term.lower() in line.lower()
                for term in SEARCH_TERMS
            ):

                print(
                    f"{line_number:4d}: {line}"
                )

print()
print("=" * 78)
print("SUMMARY")
print("=" * 78)

print(
    f"Matching notebook cells : {len(results)}"
)

if not results:
    print(
        "❌ No matching code found."
    )
else:

    print()

    for item in results:

        print(
            f"{item['notebook']} "
            f"| Cell {item['cell_index']} "
            f"| {', '.join(item['terms'])}"
        )

print()
print("=" * 78)
print("CELL 16 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 16
TRACE LABEL_QA CREATION SOURCE
==============================================================================

Notebook directory:
C:\LipReadingSSL\notebooks

Notebooks found : 10
 - dataset_master.ipynb
 - phase1_video_preparation.ipynb
 - phase2_face_detection_tracking.ipynb
 - phase3_face_alignment.ipynb
 - phase4_face_crop.ipynb
 - phase5_mouth_crop.ipynb
 - phase6.5_clip_source_alignment.ipynb
 - phase6_clip_Generation.ipynb
 - phase7.5_dataset_QA.ipynb
 - phase7_dataset_builder.ipynb

==============================================================================
SEARCH RESULTS
==============================================================================

------------------------------------------------------------------------------
NOTEBOOK : dataset_master.ipynb
CELL     : 0
MATCHED  : transcript, start_frame, end_frame
------------------------------------------------------------------------------
  11: #   3. ตรวจ transcript / normalized_text
  81:     "start_frame",
  82:     "end_frame",
  84:     "transcript",
 164: # Transcript statistics
 169: print("TRANSCRIPT DIAGNOSIS")
 172: transcript_series_diag = (
 174:         "transcript"
 184: transcript_null_diag = int(
 185:     transcript_series_diag.isna().sum()
 188: transcript_empty_diag = int(
 189:     transcript_series_diag
 211:     f"Transcript NULL       : "
 212:     f"{transcript_null_diag:,}"
 216:     f"Transcript empty      : "
 217:     f"{transcript_empty_diag:,}"
 231:     f"Transcript non-empty  : "
 232:     f"{len(dataset_master_diag) - transcript_empty_diag:,}"
 241: # Transcript by video
 246: print("TRANSCRIPT BY VIDEO")
 249: transcript_by_video_diag = (
 257:         _transcript_nonempty=
 259:                 "transcript"
 273:         transcript_nonempty=(
 274:             "_transcript_nonempty",
 280: transcript_by_video_diag[
 281:     "transcript_empty"
 283:     transcript_by_video_diag[
 287:     transcript_by_video_diag[
 288:         "transcript_nonempty"
 293:     transcript_by_video_diag.to_string()
 331:     "start_frame",
 332:     "end_frame",
 334:     "transcript",

------------------------------------------------------------------------------
NOTEBOOK : dataset_master.ipynb
CELL     : 3
MATCHED  : transcript
------------------------------------------------------------------------------
   8: # Determine whether transcript disappears:
  15: print("PHASE 7 — TRANSCRIPT SOURCE DIAGNOSIS")
  65: # Inspect transcript-bearing CSVs
  68: transcript_sources_diag = []
  97:     has_transcript = (
  98:         "transcript"
 108:         has_transcript
 113:         transcript_sources_diag.append(
 119: print("TRANSCRIPT-BEARING SOURCE FILES")
 122: if not transcript_sources_diag:
 126:         "output/dataset contains transcript "
 132:     for path in transcript_sources_diag:
 142: for csv_path in transcript_sources_diag:
 193:     # Transcript
 196:     if "transcript" in source_df_diag.columns:
 198:         transcript_nonempty = int(
 200:                 "transcript"
 211:             f"Transcript non-empty : "
 212:             f"{transcript_nonempty:,}"

------------------------------------------------------------------------------
NOTEBOOK : dataset_master.ipynb
CELL     : 4
MATCHED  : labels.csv, transcript, label
------------------------------------------------------------------------------
   9: #   Trace video001/video002/video003 and transcript source
  34:     "labels":
  35:         DATASET_DIR_DIAG / "labels.csv",
 213: # 5. Transcript / normalized_text columns
 218: print("TRANSCRIPT COLUMNS BY SOURCE")
 223:     transcript_columns = [
 228:             "transcript",
 232:             "label",
 241:     if not transcript_columns:
 244:             "  ❌ No transcript/text-like column"
 249:     for column in transcript_columns:
 267: # 6. Transcript by video
 272: print("TRANSCRIPT BY VIDEO")
 289:     transcript_column = None
 292:         "transcript",
 296:         "label",
 300:             transcript_column = candidate
 305:         or transcript_column is None
 313:         f"text={transcript_column}"
 325:         temp[transcript_column]

------------------------------------------------------------------------------
NOTEBOOK : dataset_master.ipynb
CELL     : 5
MATCHED  : labels.csv, transcript, label
------------------------------------------------------------------------------
  21:     "labels":
  22:         ROOT / "output" / "dataset" / "labels.csv",
 153: # 4. TRANSCRIPT DISTRIBUTION
 158: print("TRANSCRIPT DISTRIBUTION")
 162:     "transcript",
 166:     "label",
 229: # 5. VIDEO × TRANSCRIPT
 234: print("VIDEO × TRANSCRIPT")
 327: # 6. LABELS — SAMPLE
 330: if "labels" in dfs:
 332:     df = dfs["labels"]
 336:     print("LABELS SAMPLE")

------------------------------------------------------------------------------
NOTEBOOK : phase1_video_preparation.ipynb
CELL     : 0
MATCHED  : to_csv
------------------------------------------------------------------------------
 275: df.to_csv(

------------------------------------------------------------------------------
NOTEBOOK : phase2_face_detection_tracking.ipynb
CELL     : 7
MATCHED  : start_frame
------------------------------------------------------------------------------
 711:             "start_frame":
 741:             "start_frame":
 766:             "start_frame":
 818:             "start_frame":
 868:             "start_frame":
 893:         "start_frame":

------------------------------------------------------------------------------
NOTEBOOK : phase2_face_detection_tracking.ipynb
CELL     : 8
MATCHED  : start_frame, to_csv
------------------------------------------------------------------------------
 439:     empty_df.to_csv(
 816:     df_final.to_csv(
 861:     start_frame
 869:     start_frame = int(
 870:         start_frame
 884:     if start_frame <= 0:
 898:             start_frame
 910:         if position == start_frame:
 937:         f"for frame {start_frame}."
 946:     while current_frame < start_frame:
 956:                 f"{start_frame}."
 971:     start_frame=0
1007:     start_frame = max(
1009:         int(start_frame)
1012:     if start_frame > expected_last_frame:
1017:             f"{start_frame}\n"
1032:         f"{start_frame}"
1055:             start_frame,
1075:         start_frame
1112:         start_frame
1135:         start_frame
1485:                 start_frame,

------------------------------------------------------------------------------
NOTEBOOK : phase2_face_detection_tracking.ipynb
CELL     : 9
MATCHED  : start_frame, to_csv
------------------------------------------------------------------------------
 178:             df.to_csv(
 506:             "start_frame":
 508:                     "start_frame"
 540:             item["start_frame"]
 546:                 f"{item['start_frame']}"
 577:     start_frame = (
 578:         item["start_frame"]
 640:             f"{start_frame}"
 679:                 start_frame = 0
 687:                 start_frame = 0
 695:                 if start_frame is None:
 697:                     start_frame = 0
 702:                     f"frame {start_frame}"
 723:                     start_frame=
 724:                         start_frame

------------------------------------------------------------------------------
NOTEBOOK : phase3_face_alignment.ipynb
CELL     : 12
MATCHED  : to_csv
------------------------------------------------------------------------------
 529:                     old_metadata_df.to_csv(
1201:             combined_df.to_csv(
1222:         skipped_df.to_csv(

------------------------------------------------------------------------------
NOTEBOOK : phase4_face_crop.ipynb
CELL     : 9
MATCHED  : to_csv
------------------------------------------------------------------------------
 464:     result_df.to_csv(

------------------------------------------------------------------------------
NOTEBOOK : phase5_mouth_crop.ipynb
CELL     : 9
MATCHED  : to_csv
------------------------------------------------------------------------------
 638:     metadata_df.to_csv(
 654:     summary_df.to_csv(

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 0
MATCHED  : transcript, label, annotation
------------------------------------------------------------------------------
   8: #   Verify Phase 6 v4 outputs before creating new annotations.
  14: #   - DOES NOT create labels
  15: #   - DOES NOT create transcript
  16: #   - DOES NOT guess annotations

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 4
MATCHED  : start_frame, end_frame, label
------------------------------------------------------------------------------
  11: # - ไม่สร้าง label
  19: #   start_frame
  20: #   end_frame
  58:     "start_frame",
  59:     "end_frame",
 216:         "start_frame",
 217:         "end_frame",
 248:         df["start_frame"],
 253:         df["end_frame"],

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 6
MATCHED  : start_frame, end_frame
------------------------------------------------------------------------------
  12: #   start_frame
  13: #   end_frame
  17: # - คำนวณ num_frames จาก start_frame/end_frame
  68:     "start_frame",
  69:     "end_frame",
 173:         df["start_frame"],
 178:         df["end_frame"],
 213:         "Negative start_frame         :",
 218:         "Negative end_frame           :",
 238:         "end_frame < start_frame      :",
 251:     #     num_frames = end_frame - start_frame + 1
 455:     print("num_frames was calculated from start_frame/end_frame.")

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 7
MATCHED  : start_frame, end_frame
------------------------------------------------------------------------------
  13: #   start_frame
  14: #   end_frame
  71:     "start_frame",
  72:     "end_frame",

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 8
MATCHED  : start_frame, end_frame
------------------------------------------------------------------------------
  23: #   start_frame
  24: #   end_frame
  87:     "start_frame",
  88:     "end_frame",

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 9
MATCHED  : start_frame, end_frame
------------------------------------------------------------------------------
  50:     "start_frame",
  51:     "end_frame",
 553:     start_frame = pd.to_numeric(
 554:         df["start_frame"],
 558:     end_frame = pd.to_numeric(
 559:         df["end_frame"],
 566:             start_frame.isna()
 568:             end_frame.isna()
 575:             end_frame
 576:             <= start_frame

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 11
MATCHED  : transcript, label, annotation
------------------------------------------------------------------------------
   3: # SEARCH POSSIBLE ANNOTATION / TRANSCRIPT SOURCES
  12: print("SEARCH POSSIBLE ANNOTATION / TRANSCRIPT SOURCES")
  16: ANNOTATION_EXTENSIONS = {
  30: ANNOTATION_KEYWORDS = [
  31:     "annotation",
  33:     "label",
  34:     "labels",
  35:     "transcript",
  36:     "transcripts",
  73:             ANNOTATION_EXTENSIONS
  96:             for keyword in ANNOTATION_KEYWORDS
 113: ANNOTATION_CANDIDATES_DF = pd.DataFrame(
 118: if ANNOTATION_CANDIDATES_DF.empty:
 121:         "No filename-based annotation candidates found."
 126:     ANNOTATION_CANDIDATES_DF = (
 127:         ANNOTATION_CANDIDATES_DF
 139:         "Potential annotation files :",
 141:             ANNOTATION_CANDIDATES_DF
 147:         ANNOTATION_CANDIDATES_DF

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 12
MATCHED  : transcript, sentence_id, speaker_id, start_frame, end_frame, annotation
------------------------------------------------------------------------------
   3: # CONTENT-LEVEL ANNOTATION SOURCE SEARCH
  10: print("CONTENT-LEVEL ANNOTATION SOURCE SEARCH")
  30:     "transcript",
  31:     "sentence_id",
  32:     "speaker_id",
  33:     "start_frame",
  34:     "end_frame",
  47:     not ANNOTATION_CANDIDATES_DF.empty
  53:         ANNOTATION_CANDIDATES_DF[
 108:             "has_transcript": "transcript" in text_lower,
 109:             "has_sentence_id": "sentence_id" in text_lower,
 110:             "has_speaker_id": "speaker_id" in text_lower,
 112:                 "start_frame" in text_lower
 113:                 and "end_frame" in text_lower
 126:         "No content-level annotation candidates found."

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 13
MATCHED  : label_qa, transcript, sentence_id, label, annotation
------------------------------------------------------------------------------
   3: # INSPECT POSSIBLE REAL ANNOTATION SOURCE
  10: LABEL_QA_PATH = Path(
  11:     r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
  16: print("INSPECT POSSIBLE REAL ANNOTATION SOURCE")
  19: print(f"Path   : {LABEL_QA_PATH}")
  20: print(f"Exists : {LABEL_QA_PATH.exists()}")
  22: if not LABEL_QA_PATH.exists():
  24:         f"Annotation candidate not found:\n{LABEL_QA_PATH}"
  27: df = pd.read_csv(LABEL_QA_PATH)
  59: print("TRANSCRIPT SAMPLE")
  62: if "transcript" in df.columns:
  64:         df["transcript"]
  71:     print("transcript column not found")
  78: if "sentence_id" in df.columns:
  80:         df["sentence_id"]
  86:     print("sentence_id column not found")

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 14
MATCHED  : label_qa, transcript, sentence_id, speaker_id, start_frame, end_frame, label
------------------------------------------------------------------------------
   3: # ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4
  10: LABEL_QA_PATH = Path(
  11:     r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
  20: df = pd.read_csv(LABEL_QA_PATH)
  24: print("ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4")
  28: print("Total label_qa rows :", f"{len(df):,}")
  53:         f"label_qa={actual:,} | "
  72:             "start_frame",
  73:             "end_frame",
  74:             "speaker_id",
  75:             "sentence_id",
  76:             "transcript",
 123:         "❌ label_qa has NO video003"
 127:         "✅ label_qa contains video003"
 131: # TRANSCRIPT
 136: print("TRANSCRIPT STATUS")
 139: transcript = df["transcript"]
 142:     transcript
 145:     transcript.astype(str).str.strip().ne("")
 160:     f"{transcript[non_empty].astype(str).nunique():,}"
 173:     df["speaker_id"]
 197:     df["sentence_id"]
 211:     "Non-empty sentence_id:",
 216:     "Unique sentence_id:",
 230:     df["start_frame"],
 235:     df["end_frame"],
 240:     "Invalid start_frame:",
 245:     "Invalid end_frame:",

------------------------------------------------------------------------------
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
CELL     : 15
MATCHED  : label_qa, labels.csv, transcript, sentence_id, speaker_id, start_frame, end_frame, to_csv, label, annotation
------------------------------------------------------------------------------
   3: # TRACE LABEL_QA CREATION SOURCE
  15:     "label_qa",
  16:     "labels.csv",
  17:     "transcript",
  18:     "sentence_id",
  19:     "speaker_id",
  20:     "start_frame",
  21:     "end_frame",
  22:     "to_csv",
  23:     "label",
  24:     "annotation",
  29: print("TRACE LABEL_QA CREATION SOURCE")

------------------------------------------------------------------------------
NOTEBOOK : phase6_clip_Generation.ipynb
CELL     : 9
MATCHED  : start_frame, end_frame
------------------------------------------------------------------------------
  28:             record["start_frame"]
  36:             record["end_frame"]
  52:             start_frames=starts,
  53:             end_frames=ends,
  62:             start_frames=starts,
  63:             end_frames=ends,

------------------------------------------------------------------------------
NOTEBOOK : phase6_clip_Generation.ipynb
CELL     : 10
MATCHED  : start_frame, end_frame, to_csv
------------------------------------------------------------------------------
 160:             int(r["start_frame"]),
 161:             int(r["end_frame"])
 165:         "start_frame" in r
 167:         "end_frame" in r
 230:         start_frame = int(
 234:         end_frame = int(
 239:             start_frame,
 240:             end_frame
 260:                 f"{start_frame}-{end_frame}: "
 275:             "start_frame":
 276:                 start_frame,
 278:             "end_frame":
 279:                 end_frame,
 375:                     "start_frame",
 376:                     "end_frame"
 383:                     "start_frame"
 398:         result_df.to_csv(

------------------------------------------------------------------------------
NOTEBOOK : phase6_clip_Generation.ipynb
CELL     : 13
MATCHED  : start_frame, end_frame
------------------------------------------------------------------------------
 156:         "start_frame",
 157:         "end_frame",
 193:             "start_frame",
 194:             "end_frame"
 230:                 "start_frame"
 237:                 "end_frame"

------------------------------------------------------------------------------
NOTEBOOK : phase6_clip_Generation.ipynb
CELL     : 16
MATCHED  : start_frame, end_frame, to_csv
------------------------------------------------------------------------------
 197:                     "start_frames",
 198:                     "end_frames",
 226:                 start_frames = data[
 227:                     "start_frames"
 230:                 end_frames = data[
 231:                     "end_frames"
 256:                 if len(start_frames) != n_clips:
 259:                         "start_frames count mismatch"
 262:                 if len(end_frames) != n_clips:
 265:                         "end_frames count mismatch"
 282:                     start_frame = int(
 283:                         start_frames[
 288:                     end_frame = int(
 289:                         end_frames[
 303:                         start_frame < 0
 304:                         or end_frame < start_frame
 327:                         "start_frame":
 328:                             start_frame,
 330:                         "end_frame":
 331:                             end_frame,
 334:                             end_frame
 335:                             - start_frame
 596:     repaired_df.to_csv(

------------------------------------------------------------------------------
NOTEBOOK : phase6_clip_Generation.ipynb
CELL     : 18
MATCHED  : start_frame, end_frame, to_csv
------------------------------------------------------------------------------
 240:                     "start_frames",
 241:                     "end_frames",
 267:                 start_frames = np.asarray(
 269:                         "start_frames"
 273:                 end_frames = np.asarray(
 275:                         "end_frames"
 297:                 if len(start_frames) != n_clips:
 300:                         f"start_frames length "
 301:                         f"{len(start_frames)} != "
 306:                 if len(end_frames) != n_clips:
 309:                         f"end_frames length "

In [23]:
# ==============================================================================
# PHASE 6.5 — CELL 17
# DEEP TRACE DATASET / ANNOTATION CREATION CODE
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json

PROJECT_ROOT = Path(r"C:\LipReadingSSL")
NOTEBOOK_DIR = PROJECT_ROOT / "notebooks"

SEARCH_TERMS = [
    "to_csv",
    "read_csv",
    "transcript",
    "sentence",
    "speaker",
    "start_frame",
    "end_frame",
    "clip_id",
    "dataset_id",
    "annotation",
    "label",
]

print("=" * 78)
print("PHASE 6.5 — CELL 17")
print("DEEP TRACE DATASET / ANNOTATION CREATION CODE")
print("READ-ONLY")
print("=" * 78)

matches = []

for nb_path in sorted(NOTEBOOK_DIR.glob("*.ipynb")):

    try:
        with open(
            nb_path,
            "r",
            encoding="utf-8"
        ) as f:
            notebook = json.load(f)

    except Exception as e:
        print(f"\n❌ Cannot read {nb_path.name}: {e}")
        continue

    for cell_index, cell in enumerate(
        notebook.get("cells", [])
    ):

        source = "".join(
            cell.get("source", [])
        )

        if not source.strip():
            continue

        lines = source.splitlines()

        for line_index, line in enumerate(lines):

            matched = [
                term
                for term in SEARCH_TERMS
                if term.lower() in line.lower()
            ]

            if not matched:
                continue

            matches.append({
                "notebook": nb_path.name,
                "cell": cell_index,
                "line": line_index + 1,
                "terms": matched,
            })

            print()
            print("=" * 78)
            print(
                f"NOTEBOOK : {nb_path.name}"
            )
            print(
                f"CELL     : {cell_index}"
            )
            print(
                f"LINE     : {line_index + 1}"
            )
            print(
                "MATCHED  : "
                + ", ".join(matched)
            )
            print("-" * 78)

            # --------------------------------------------------------------
            # Show context: 3 lines before + matched line + 3 lines after
            # --------------------------------------------------------------

            start = max(
                0,
                line_index - 3
            )

            end = min(
                len(lines),
                line_index + 4
            )

            for i in range(start, end):

                marker = ">>> " if i == line_index else "    "

                print(
                    f"{marker}{i + 1:4d}: "
                    f"{lines[i]}"
                )

print()
print("=" * 78)
print("SUMMARY")
print("=" * 78)

print(
    f"Total matches : {len(matches):,}"
)

if not matches:

    print()
    print(
        "❌ No matching creation / loading code found."
    )

else:

    print()

    # Count matches per notebook
    notebook_counts = {}

    for item in matches:

        notebook = item["notebook"]

        notebook_counts[notebook] = (
            notebook_counts.get(notebook, 0) + 1
        )

    print("Matches by notebook:")

    for notebook, count in sorted(
        notebook_counts.items(),
        key=lambda x: (-x[1], x[0])
    ):

        print(
            f" - {notebook}: {count}"
        )

print()
print("=" * 78)
print("CELL 17 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 17
DEEP TRACE DATASET / ANNOTATION CREATION CODE
READ-ONLY
==============================================================================

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 11
MATCHED  : transcript
------------------------------------------------------------------------------
       8: # Purpose:
       9: #   1. ตรวจ dataset_master.csv
      10: #   2. ตรวจว่า video003 หายตั้งแต่ master หรือไม่
>>>   11: #   3. ตรวจ transcript / normalized_text
      12: #   4. ตรวจจำนวนข้อมูลราย video
      13: # ============================================================
      14:

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 50
MATCHED  : read_csv
------------------------------------------------------------------------------
      47: # Load
      48: # ------------------------------------------------------------
      49:
>>>   50: dataset_master_diag = pd.read_csv(
      51:     DATASET_MASTER_PATH,
      52:     low_memory=False
      53: )

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 80
MATCHED  : clip_id
------------------------------------------------------------------------------
      77:
      78: required_diag_columns = [
      79:     "video_id",
>>>   80:     "clip_id",
      81:     "start_frame",
      82:     "end_frame",
      83:     "num_frames",

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 81
MATCHED  : start_frame
------------------------------------------------------------------------------
      78: required_diag_columns = [
      79:     "video_id",
      80:     "clip_id",
>>>   81:     "start_frame",
      82:     "end_frame",
      83:     "num_frames",
      84:     "transcript",

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 82
MATCHED  : end_frame
------------------------------------------------------------------------------
      79:     "video_id",
      80:     "clip_id",
      81:     "start_frame",
>>>   82:     "end_frame",
      83:     "num_frames",
      84:     "transcript",
      85:     "normalized_text",

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 84
MATCHED  : transcript
------------------------------------------------------------------------------
      81:     "start_frame",
      82:     "end_frame",
      83:     "num_frames",
>>>   84:     "transcript",
      85:     "normalized_text",
      86:     "split",
      87: ]

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 164
MATCHED  : transcript
------------------------------------------------------------------------------
     161:         )
     162:
     163: # ------------------------------------------------------------
>>>  164: # Transcript statistics
     165: # ------------------------------------------------------------
     166:
     167: print()

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 169
MATCHED  : transcript
------------------------------------------------------------------------------
     166:
     167: print()
     168: print("=" * 80)
>>>  169: print("TRANSCRIPT DIAGNOSIS")
     170: print("=" * 80)
     171:
     172: transcript_series_diag = (

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 172
MATCHED  : transcript
------------------------------------------------------------------------------
     169: print("TRANSCRIPT DIAGNOSIS")
     170: print("=" * 80)
     171:
>>>  172: transcript_series_diag = (
     173:     dataset_master_diag[
     174:         "transcript"
     175:     ]

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 174
MATCHED  : transcript
------------------------------------------------------------------------------
     171:
     172: transcript_series_diag = (
     173:     dataset_master_diag[
>>>  174:         "transcript"
     175:     ]
     176: )
     177:

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 184
MATCHED  : transcript
------------------------------------------------------------------------------
     181:     ]
     182: )
     183:
>>>  184: transcript_null_diag = int(
     185:     transcript_series_diag.isna().sum()
     186: )
     187:

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 185
MATCHED  : transcript
------------------------------------------------------------------------------
     182: )
     183:
     184: transcript_null_diag = int(
>>>  185:     transcript_series_diag.isna().sum()
     186: )
     187:
     188: transcript_empty_diag = int(

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 188
MATCHED  : transcript
------------------------------------------------------------------------------
     185:     transcript_series_diag.isna().sum()
     186: )
     187:
>>>  188: transcript_empty_diag = int(
     189:     transcript_series_diag
     190:     .fillna("")
     191:     .astype(str)

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 189
MATCHED  : transcript
------------------------------------------------------------------------------
     186: )
     187:
     188: transcript_empty_diag = int(
>>>  189:     transcript_series_diag
     190:     .fillna("")
     191:     .astype(str)
     192:     .str.strip()

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 211
MATCHED  : transcript
------------------------------------------------------------------------------
     208: )
     209:
     210: print(
>>>  211:     f"Transcript NULL       : "
     212:     f"{transcript_null_diag:,}"
     213: )
     214:

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 212
MATCHED  : transcript
------------------------------------------------------------------------------
     209:
     210: print(
     211:     f"Transcript NULL       : "
>>>  212:     f"{transcript_null_diag:,}"
     213: )
     214:
     215: print(

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 216
MATCHED  : transcript
------------------------------------------------------------------------------
     213: )
     214:
     215: print(
>>>  216:     f"Transcript empty      : "
     217:     f"{transcript_empty_diag:,}"
     218: )
     219:

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 217
MATCHED  : transcript
------------------------------------------------------------------------------
     214:
     215: print(
     216:     f"Transcript empty      : "
>>>  217:     f"{transcript_empty_diag:,}"
     218: )
     219:
     220: print(

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 231
MATCHED  : transcript
------------------------------------------------------------------------------
     228: )
     229:
     230: print(
>>>  231:     f"Transcript non-empty  : "
     232:     f"{len(dataset_master_diag) - transcript_empty_diag:,}"
     233: )
     234:

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 232
MATCHED  : transcript
------------------------------------------------------------------------------
     229:
     230: print(
     231:     f"Transcript non-empty  : "
>>>  232:     f"{len(dataset_master_diag) - transcript_empty_diag:,}"
     233: )
     234:
     235: print(

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 241
MATCHED  : transcript
------------------------------------------------------------------------------
     238: )
     239:
     240: # ------------------------------------------------------------
>>>  241: # Transcript by video
     242: # ------------------------------------------------------------
     243:
     244: print()

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 246
MATCHED  : transcript
------------------------------------------------------------------------------
     243:
     244: print()
     245: print("=" * 80)
>>>  246: print("TRANSCRIPT BY VIDEO")
     247: print("=" * 80)
     248:
     249: transcript_by_video_diag = (

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 249
MATCHED  : transcript
------------------------------------------------------------------------------
     246: print("TRANSCRIPT BY VIDEO")
     247: print("=" * 80)
     248:
>>>  249: transcript_by_video_diag = (
     250:     dataset_master_diag
     251:     .assign(
     252:         _video=

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 257
MATCHED  : transcript
------------------------------------------------------------------------------
     254:                 "video_id"
     255:             ].astype(str),
     256:
>>>  257:         _transcript_nonempty=
     258:             dataset_master_diag[
     259:                 "transcript"
     260:             ]

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 259
MATCHED  : transcript
------------------------------------------------------------------------------
     256:
     257:         _transcript_nonempty=
     258:             dataset_master_diag[
>>>  259:                 "transcript"
     260:             ]
     261:             .fillna("")
     262:             .astype(str)

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 273
MATCHED  : transcript
------------------------------------------------------------------------------
     270:             "size"
     271:         ),
     272:
>>>  273:         transcript_nonempty=(
     274:             "_transcript_nonempty",
     275:             "sum"
     276:         ),

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 274
MATCHED  : transcript
------------------------------------------------------------------------------
     271:         ),
     272:
     273:         transcript_nonempty=(
>>>  274:             "_transcript_nonempty",
     275:             "sum"
     276:         ),
     277:     )

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 280
MATCHED  : transcript
------------------------------------------------------------------------------
     277:     )
     278: )
     279:
>>>  280: transcript_by_video_diag[
     281:     "transcript_empty"
     282: ] = (
     283:     transcript_by_video_diag[

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 281
MATCHED  : transcript
------------------------------------------------------------------------------
     278: )
     279:
     280: transcript_by_video_diag[
>>>  281:     "transcript_empty"
     282: ] = (
     283:     transcript_by_video_diag[
     284:         "samples"

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 283
MATCHED  : transcript
------------------------------------------------------------------------------
     280: transcript_by_video_diag[
     281:     "transcript_empty"
     282: ] = (
>>>  283:     transcript_by_video_diag[
     284:         "samples"
     285:     ]
     286:     -

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 287
MATCHED  : transcript
------------------------------------------------------------------------------
     284:         "samples"
     285:     ]
     286:     -
>>>  287:     transcript_by_video_diag[
     288:         "transcript_nonempty"
     289:     ]
     290: )

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 288
MATCHED  : transcript
------------------------------------------------------------------------------
     285:     ]
     286:     -
     287:     transcript_by_video_diag[
>>>  288:         "transcript_nonempty"
     289:     ]
     290: )
     291:

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 293
MATCHED  : transcript
------------------------------------------------------------------------------
     290: )
     291:
     292: print(
>>>  293:     transcript_by_video_diag.to_string()
     294: )
     295:
     296: # ------------------------------------------------------------

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 330
MATCHED  : clip_id
------------------------------------------------------------------------------
     327:
     328: sample_columns_diag = [
     329:     "video_id",
>>>  330:     "clip_id",
     331:     "start_frame",
     332:     "end_frame",
     333:     "num_frames",

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 331
MATCHED  : start_frame
------------------------------------------------------------------------------
     328: sample_columns_diag = [
     329:     "video_id",
     330:     "clip_id",
>>>  331:     "start_frame",
     332:     "end_frame",
     333:     "num_frames",
     334:     "transcript",

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 332
MATCHED  : end_frame
------------------------------------------------------------------------------
     329:     "video_id",
     330:     "clip_id",
     331:     "start_frame",
>>>  332:     "end_frame",
     333:     "num_frames",
     334:     "transcript",
     335:     "normalized_text",

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 0
LINE     : 334
MATCHED  : transcript
------------------------------------------------------------------------------
     331:     "start_frame",
     332:     "end_frame",
     333:     "num_frames",
>>>  334:     "transcript",
     335:     "normalized_text",
     336:     "split",
     337: ]

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 2
LINE     : 58
MATCHED  : read_csv
------------------------------------------------------------------------------
      55:
      56:         try:
      57:
>>>   58:             mouth_df = pd.read_csv(
      59:                 mouth_metadata_path,
      60:                 low_memory=False
      61:             )

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 2
LINE     : 83
MATCHED  : read_csv
------------------------------------------------------------------------------
      80:
      81:         try:
      82:
>>>   83:             clip_df = pd.read_csv(
      84:                 clip_metadata_path,
      85:                 low_memory=False
      86:             )

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 3
LINE     : 8
MATCHED  : transcript
------------------------------------------------------------------------------
       5: # READ ONLY
       6: # DOES NOT MODIFY ANY FILE
       7: #
>>>    8: # Determine whether transcript disappears:
       9: #   A) before dataset_master
      10: #   B) during dataset_master construction
      11: #   C) only normalized_text is missing

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 3
LINE     : 15
MATCHED  : transcript
------------------------------------------------------------------------------
      12: # ============================================================
      13:
      14: print("=" * 80)
>>>   15: print("PHASE 7 — TRANSCRIPT SOURCE DIAGNOSIS")
      16: print("=" * 80)
      17:
      18: # ------------------------------------------------------------

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 3
LINE     : 65
MATCHED  : transcript
------------------------------------------------------------------------------
      62:     )
      63:
      64: # ------------------------------------------------------------
>>>   65: # Inspect transcript-bearing CSVs
      66: # ------------------------------------------------------------
      67:
      68: transcript_sources_diag = []

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 3
LINE     : 68
MATCHED  : transcript
------------------------------------------------------------------------------
      65: # Inspect transcript-bearing CSVs
      66: # ------------------------------------------------------------
      67:
>>>   68: transcript_sources_diag = []
      69:
      70: for csv_path in csv_files_diag:
      71:

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 3
LINE     : 82
MATCHED  : read_csv
------------------------------------------------------------------------------
      79:
      80:     try:
      81:
>>>   82:         df = pd.read_csv(
      83:             csv_path,
      84:             low_memory=False,
      85:             nrows=5

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 3
LINE     : 97
MATCHED  : transcript
------------------------------------------------------------------------------
      94:         for column in df.columns
      95:     }
      96:
>>>   97:     has_transcript = (
      98:         "transcript"
      99:         in columns_lower
     100:     )

==============================================================================
NOTEBOOK : dataset_master.ipynb
CELL     : 3
LINE     : 98
MATCHED  : transcript
------------------------------------------------------------------------------
      95:     }
      96:

In [24]:
# ==============================================================================
# PHASE 6.5 — CELL 18
# TRACE ACTUAL LABEL / TRANSCRIPT FILE I/O
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json
import re

PROJECT_ROOT = Path(r"C:\LipReadingSSL")
NOTEBOOK_DIR = PROJECT_ROOT / "notebooks"

TARGET_NOTEBOOKS = [
    "phase6_clip_Generation.ipynb",
    "phase6.5_clip_source_alignment.ipynb",
    "phase7_dataset_builder.ipynb",
    "phase7.5_dataset_QA.ipynb",
]

PATTERNS = [
    r"\.read_csv\s*\(",
    r"pd\.read_csv\s*\(",
    r"\.read_table\s*\(",
    r"pd\.read_table\s*\(",
    r"\.read_json\s*\(",
    r"pd\.read_json\s*\(",
    r"\.to_csv\s*\(",
    r"\.to_json\s*\(",
    r"open\s*\(",
]

LABEL_TERMS = [
    "label",
    "labels",
    "annotation",
    "annot",
    "transcript",
    "sentence",
    "speaker",
    "normalized_text",
    "text",
    "start_frame",
    "end_frame",
    "clip_id",
    "dataset_id",
]

print("=" * 78)
print("PHASE 6.5 — CELL 18")
print("TRACE ACTUAL LABEL / TRANSCRIPT FILE I/O")
print("READ-ONLY")
print("=" * 78)

for notebook_name in TARGET_NOTEBOOKS:

    nb_path = NOTEBOOK_DIR / notebook_name

    print()
    print("=" * 78)
    print(f"NOTEBOOK : {notebook_name}")
    print("=" * 78)

    if not nb_path.exists():

        print("❌ Notebook not found")
        continue

    with open(
        nb_path,
        "r",
        encoding="utf-8"
    ) as f:

        notebook = json.load(f)

    found = 0

    for cell_index, cell in enumerate(
        notebook.get("cells", [])
    ):

        source = "".join(
            cell.get("source", [])
        )

        if not source.strip():
            continue

        lines = source.splitlines()

        for line_index, line in enumerate(lines):

            # --------------------------------------------------------------
            # Only inspect actual file I/O statements
            # --------------------------------------------------------------

            is_io = any(
                re.search(
                    pattern,
                    line,
                    flags=re.IGNORECASE
                )
                for pattern in PATTERNS
            )

            if not is_io:
                continue

            # --------------------------------------------------------------
            # Check whether nearby context contains label-related terms
            # --------------------------------------------------------------

            context_start = max(
                0,
                line_index - 5
            )

            context_end = min(
                len(lines),
                line_index + 6
            )

            context = "\n".join(
                lines[context_start:context_end]
            ).lower()

            related_terms = [
                term
                for term in LABEL_TERMS
                if term.lower() in context
            ]

            if not related_terms:
                continue

            found += 1

            print()
            print("-" * 78)
            print(
                f"CELL : {cell_index}"
            )
            print(
                f"LINE : {line_index + 1}"
            )
            print(
                "RELATED TERMS : "
                + ", ".join(
                    sorted(set(related_terms))
                )
            )
            print("-" * 78)

            for i in range(
                context_start,
                context_end
            ):

                marker = (
                    ">>> "
                    if i == line_index
                    else "    "
                )

                print(
                    f"{marker}{i + 1:4d}: "
                    f"{lines[i]}"
                )

    print()
    print(
        f"Relevant file-I/O blocks found : {found}"
    )

print()
print("=" * 78)
print("CELL 18 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 18
TRACE ACTUAL LABEL / TRANSCRIPT FILE I/O
READ-ONLY
==============================================================================

==============================================================================
NOTEBOOK : phase6_clip_Generation.ipynb
==============================================================================

Relevant file-I/O blocks found : 0

==============================================================================
NOTEBOOK : phase6.5_clip_source_alignment.ipynb
==============================================================================

------------------------------------------------------------------------------
CELL : 13
LINE : 27
RELATED TERMS : annot, annotation, label
------------------------------------------------------------------------------
      22: if not LABEL_QA_PATH.exists():
      23:     raise FileNotFoundError(
      24:         f"Annotation candidate not found:\n{LABEL_QA_PATH}"
      25:     )
      26:
>>>   27: df = pd.read_csv(LABEL_QA_PATH)
      28:
      29: print()
      30: print("-" * 78)
      31: print("SCHEMA")
      32: print("-" * 78)

------------------------------------------------------------------------------
CELL : 14
LINE : 20
RELATED TERMS : label
------------------------------------------------------------------------------
      15:     "video001": 40076,
      16:     "video002": 31662,
      17:     "video003": 26273,
      18: }
      19:
>>>   20: df = pd.read_csv(LABEL_QA_PATH)
      21:
      22: print("=" * 78)
      23: print("PHASE 6.5 — CELL 15")
      24: print("ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4")
      25: print("=" * 78)

Relevant file-I/O blocks found : 2

==============================================================================
NOTEBOOK : phase7_dataset_builder.ipynb
==============================================================================

------------------------------------------------------------------------------
CELL : 4
LINE : 81
RELATED TERMS : label
------------------------------------------------------------------------------
      76:     template_rows,
      77:     columns=LABEL_SOURCE_COLUMNS
      78: )
      79:
      80:
>>>   81: label_template_df.to_csv(
      82:     LABEL_SOURCE_TEMPLATE,
      83:     index=False,
      84:     encoding="utf-8-sig"
      85: )
      86:

------------------------------------------------------------------------------
CELL : 5
LINE : 47
RELATED TERMS : label, labels, transcript
------------------------------------------------------------------------------
      42:         "The pipeline will NOT create fake "
      43:         "or empty transcript labels."
      44:     )
      45:
      46:
>>>   47: labels_df = pd.read_csv(
      48:     REAL_LABEL_SOURCE_PATH,
      49:     low_memory=False
      50: )
      51:
      52:

------------------------------------------------------------------------------
CELL : 8
LINE : 266
RELATED TERMS : sentence
------------------------------------------------------------------------------
     261:     REPORT_ROOT
     262:     / "sentence_clip_mapping.csv"
     263: )
     264:
     265:
>>>  266: mapping_df.to_csv(
     267:     mapping_report_path,
     268:     index=False,
     269:     encoding="utf-8-sig"
     270: )
     271:

------------------------------------------------------------------------------
CELL : 9
LINE : 109
RELATED TERMS : transcript
------------------------------------------------------------------------------
     104:         index=False
     105:     )
     106: )
     107:
     108:
>>>  109: video_coverage.to_csv(
     110:     REPORT_ROOT
     111:     / "transcript_coverage.csv",
     112:     index=False,
     113:     encoding="utf-8-sig"
     114: )

Relevant file-I/O blocks found : 4

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
==============================================================================

------------------------------------------------------------------------------
CELL : 6
LINE : 179
RELATED TERMS : text
------------------------------------------------------------------------------
     174:     ANALYSIS_DIR / "vocabulary_distribution.csv",
     175:     index=False,
     176:     encoding="utf-8-sig"
     177: )
     178:
>>>  179: text_split_df.to_csv(
     180:     ANALYSIS_DIR / "vocabulary_by_split.csv",
     181:     encoding="utf-8-sig"
     182: )
     183:
     184: text_video_df.to_csv(

------------------------------------------------------------------------------
CELL : 6
LINE : 184
RELATED TERMS : text
------------------------------------------------------------------------------
     179: text_split_df.to_csv(
     180:     ANALYSIS_DIR / "vocabulary_by_split.csv",
     181:     encoding="utf-8-sig"
     182: )
     183:
>>>  184: text_video_df.to_csv(
     185:     ANALYSIS_DIR / "vocabulary_by_video.csv",
     186:     encoding="utf-8-sig"
     187: )
     188:
     189: vocabulary_summary.to_csv(

------------------------------------------------------------------------------
CELL : 6
LINE : 189
RELATED TERMS : text
------------------------------------------------------------------------------
     184: text_video_df.to_csv(
     185:     ANALYSIS_DIR / "vocabulary_by_video.csv",
     186:     encoding="utf-8-sig"
     187: )
     188:
>>>  189: vocabulary_summary.to_csv(
     190:     ANALYSIS_DIR / "vocabulary_summary.csv",
     191:     index=False,
     192:     encoding="utf-8-sig"
     193: )
     194:

------------------------------------------------------------------------------
CELL : 7
LINE : 216
RELATED TERMS : speaker
------------------------------------------------------------------------------
     211:
     212: # -------------------------------------------------
     213: # 7. Save
     214: # -------------------------------------------------
     215:
>>>  216: speaker_distribution.to_csv(
     217:     ANALYSIS_DIR / "speaker_distribution.csv",
     218:     index=False,
     219:     encoding="utf-8-sig"
     220: )
     221:

------------------------------------------------------------------------------
CELL : 7
LINE : 222
RELATED TERMS : speaker
------------------------------------------------------------------------------
     217:     ANALYSIS_DIR / "speaker_distribution.csv",
     218:     index=False,
     219:     encoding="utf-8-sig"
     220: )
     221:
>>>  222: video_distribution.to_csv(
     223:     ANALYSIS_DIR / "video_distribution.csv",
     224:     index=False,
     225:     encoding="utf-8-sig"
     226: )
     227:

------------------------------------------------------------------------------
CELL : 7
LINE : 228
RELATED TERMS : speaker
------------------------------------------------------------------------------
     223:     ANALYSIS_DIR / "video_distribution.csv",
     224:     index=False,
     225:     encoding="utf-8-sig"
     226: )
     227:
>>>  228: speaker_split.to_csv(
     229:     ANALYSIS_DIR / "speaker_split.csv",
     230:     index=False,
     231:     encoding="utf-8-sig"
     232: )
     233:

------------------------------------------------------------------------------
CELL : 7
LINE : 234
RELATED TERMS : speaker
------------------------------------------------------------------------------
     229:     ANALYSIS_DIR / "speaker_split.csv",
     230:     index=False,
     231:     encoding="utf-8-sig"
     232: )
     233:
>>>  234: video_split.to_csv(
     235:     ANALYSIS_DIR / "video_split.csv",
     236:     index=False,
     237:     encoding="utf-8-sig"
     238: )
     239:

------------------------------------------------------------------------------
CELL : 8
LINE : 302
RELATED TERMS : dataset_id
------------------------------------------------------------------------------
     297:     ANALYSIS_DIR / "duplicate_dataset_clip_keys.csv",
     298:     index=False,
     299:     encoding="utf-8-sig"
     300: )
     301:
>>>  302: duplicate_id_df.to_csv(
     303:     ANALYSIS_DIR / "duplicate_dataset_ids.csv",
     304:     index=False,
     305:     encoding="utf-8-sig"
     306: )
     307:

------------------------------------------------------------------------------
CELL : 8
LINE : 308
RELATED TERMS : dataset_id
------------------------------------------------------------------------------
     303:     ANALYSIS_DIR / "duplicate_dataset_ids.csv",
     304:     index=False,
     305:     encoding="utf-8-sig"
     306: )
     307:
>>>  308: frame_outlier_df.to_csv(
     309:     ANALYSIS_DIR / "frame_outliers.csv",
     310:     index=False,
     311:     encoding="utf-8-sig"
     312: )
     313:

------------------------------------------------------------------------------
CELL : 9
LINE : 324
RELATED TERMS : speaker
------------------------------------------------------------------------------
     319:     ANALYSIS_DIR / "distribution_video.csv",
     320:     index=False,
     321:     encoding="utf-8-sig"
     322: )
     323:
>>>  324: speaker_distribution.to_csv(
     325:     ANALYSIS_DIR / "distribution_speaker.csv",
     326:     index=False,
     327:     encoding="utf-8-sig"
     328: )
     329:

------------------------------------------------------------------------------
CELL : 9
LINE : 330
RELATED TERMS : sentence, speaker
------------------------------------------------------------------------------
     325:     ANALYSIS_DIR / "distribution_speaker.csv",
     326:     index=False,
     327:     encoding="utf-8-sig"
     328: )
     329:
>>>  330: sentence_distribution.to_csv(
     331:     ANALYSIS_DIR / "distribution_sentence.csv",
     332:     index=False,
     333:     encoding="utf-8-sig"
     334: )
     335:

------------------------------------------------------------------------------
CELL : 9
LINE : 336
RELATED TERMS : sentence
------------------------------------------------------------------------------
     331:     ANALYSIS_DIR / "distribution_sentence.csv",
     332:     index=False,
     333:     encoding="utf-8-sig"
     334: )
     335:
>>>  336: frame_statistics.to_csv(
     337:     ANALYSIS_DIR / "frame_statistics.csv",
     338:     index=False,
     339:     encoding="utf-8-sig"
     340: )
     341:

Relevant file-I/O blocks found : 12

==============================================================================
CELL 18 COMPLETE — READ ONLY
==============================================================================

In [25]:
# ==============================================================================
# PHASE 6.5 — CELL 19
# TRACE LABEL_QA_PATH DEFINITION AND USAGE
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json

NOTEBOOK_PATH = Path(
    r"C:\LipReadingSSL\notebooks\phase6.5_clip_source_alignment.ipynb"
)

SEARCH_TERMS = [
    "LABEL_QA_PATH",
    "label_qa.csv",
    "label_qa",
]

print("=" * 78)
print("PHASE 6.5 — CELL 19")
print("TRACE LABEL_QA_PATH DEFINITION AND USAGE")
print("READ-ONLY")
print("=" * 78)

if not NOTEBOOK_PATH.exists():
    raise FileNotFoundError(
        f"Notebook not found:\n{NOTEBOOK_PATH}"
    )

with open(
    NOTEBOOK_PATH,
    "r",
    encoding="utf-8"
) as f:

    notebook = json.load(f)

total_matches = 0

for cell_index, cell in enumerate(
    notebook.get("cells", [])
):

    source = "".join(
        cell.get("source", [])
    )

    if not source.strip():
        continue

    lines = source.splitlines()

    for line_index, line in enumerate(lines):

        matched_terms = [
            term
            for term in SEARCH_TERMS
            if term.lower() in line.lower()
        ]

        if not matched_terms:
            continue

        total_matches += 1

        print()
        print("=" * 78)
        print(
            f"CELL : {cell_index}"
        )
        print(
            f"LINE : {line_index + 1}"
        )
        print(
            "MATCH : "
            + ", ".join(matched_terms)
        )
        print("=" * 78)

        # --------------------------------------------------------------
        # Show context around the matched line
        # --------------------------------------------------------------

        context_start = max(
            0,
            line_index - 8
        )

        context_end = min(
            len(lines),
            line_index + 9
        )

        for i in range(
            context_start,
            context_end
        ):

            marker = (
                ">>> "
                if i == line_index
                else "    "
            )

            print(
                f"{marker}{i + 1:4d}: "
                f"{lines[i]}"
            )

print()
print("=" * 78)
print(
    f"TOTAL MATCHES : {total_matches}"
)
print("=" * 78)

print()
print("CELL 19 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 19
TRACE LABEL_QA_PATH DEFINITION AND USAGE
READ-ONLY
==============================================================================

==============================================================================
CELL : 13
LINE : 10
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
       2: # PHASE 6.5 — CELL 14
       3: # INSPECT POSSIBLE REAL ANNOTATION SOURCE
       4: # READ-ONLY
       5: # ==============================================================================
       6:
       7: from pathlib import Path
       8: import pandas as pd
       9:
>>>   10: LABEL_QA_PATH = Path(
      11:     r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
      12: )
      13:
      14: print("=" * 78)
      15: print("PHASE 6.5 — CELL 14")
      16: print("INSPECT POSSIBLE REAL ANNOTATION SOURCE")
      17: print("=" * 78)
      18:

==============================================================================
CELL : 13
LINE : 11
MATCH : label_qa.csv, label_qa
==============================================================================
       3: # INSPECT POSSIBLE REAL ANNOTATION SOURCE
       4: # READ-ONLY
       5: # ==============================================================================
       6:
       7: from pathlib import Path
       8: import pandas as pd
       9:
      10: LABEL_QA_PATH = Path(
>>>   11:     r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
      12: )
      13:
      14: print("=" * 78)
      15: print("PHASE 6.5 — CELL 14")
      16: print("INSPECT POSSIBLE REAL ANNOTATION SOURCE")
      17: print("=" * 78)
      18:
      19: print(f"Path   : {LABEL_QA_PATH}")

==============================================================================
CELL : 13
LINE : 19
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
      11:     r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
      12: )
      13:
      14: print("=" * 78)
      15: print("PHASE 6.5 — CELL 14")
      16: print("INSPECT POSSIBLE REAL ANNOTATION SOURCE")
      17: print("=" * 78)
      18:
>>>   19: print(f"Path   : {LABEL_QA_PATH}")
      20: print(f"Exists : {LABEL_QA_PATH.exists()}")
      21:
      22: if not LABEL_QA_PATH.exists():
      23:     raise FileNotFoundError(
      24:         f"Annotation candidate not found:\n{LABEL_QA_PATH}"
      25:     )
      26:
      27: df = pd.read_csv(LABEL_QA_PATH)

==============================================================================
CELL : 13
LINE : 20
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
      12: )
      13:
      14: print("=" * 78)
      15: print("PHASE 6.5 — CELL 14")
      16: print("INSPECT POSSIBLE REAL ANNOTATION SOURCE")
      17: print("=" * 78)
      18:
      19: print(f"Path   : {LABEL_QA_PATH}")
>>>   20: print(f"Exists : {LABEL_QA_PATH.exists()}")
      21:
      22: if not LABEL_QA_PATH.exists():
      23:     raise FileNotFoundError(
      24:         f"Annotation candidate not found:\n{LABEL_QA_PATH}"
      25:     )
      26:
      27: df = pd.read_csv(LABEL_QA_PATH)
      28:

==============================================================================
CELL : 13
LINE : 22
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
      14: print("=" * 78)
      15: print("PHASE 6.5 — CELL 14")
      16: print("INSPECT POSSIBLE REAL ANNOTATION SOURCE")
      17: print("=" * 78)
      18:
      19: print(f"Path   : {LABEL_QA_PATH}")
      20: print(f"Exists : {LABEL_QA_PATH.exists()}")
      21:
>>>   22: if not LABEL_QA_PATH.exists():
      23:     raise FileNotFoundError(
      24:         f"Annotation candidate not found:\n{LABEL_QA_PATH}"
      25:     )
      26:
      27: df = pd.read_csv(LABEL_QA_PATH)
      28:
      29: print()
      30: print("-" * 78)

==============================================================================
CELL : 13
LINE : 24
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
      16: print("INSPECT POSSIBLE REAL ANNOTATION SOURCE")
      17: print("=" * 78)
      18:
      19: print(f"Path   : {LABEL_QA_PATH}")
      20: print(f"Exists : {LABEL_QA_PATH.exists()}")
      21:
      22: if not LABEL_QA_PATH.exists():
      23:     raise FileNotFoundError(
>>>   24:         f"Annotation candidate not found:\n{LABEL_QA_PATH}"
      25:     )
      26:
      27: df = pd.read_csv(LABEL_QA_PATH)
      28:
      29: print()
      30: print("-" * 78)
      31: print("SCHEMA")
      32: print("-" * 78)

==============================================================================
CELL : 13
LINE : 27
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
      19: print(f"Path   : {LABEL_QA_PATH}")
      20: print(f"Exists : {LABEL_QA_PATH.exists()}")
      21:
      22: if not LABEL_QA_PATH.exists():
      23:     raise FileNotFoundError(
      24:         f"Annotation candidate not found:\n{LABEL_QA_PATH}"
      25:     )
      26:
>>>   27: df = pd.read_csv(LABEL_QA_PATH)
      28:
      29: print()
      30: print("-" * 78)
      31: print("SCHEMA")
      32: print("-" * 78)
      33:
      34: print(f"Rows : {len(df):,}")
      35:

==============================================================================
CELL : 14
LINE : 3
MATCH : label_qa
==============================================================================
       1: # ==============================================================================
       2: # PHASE 6.5 — CELL 15
>>>    3: # ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4
       4: # READ-ONLY
       5: # ==============================================================================
       6:
       7: import pandas as pd
       8: from pathlib import Path
       9:
      10: LABEL_QA_PATH = Path(
      11:     r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"

==============================================================================
CELL : 14
LINE : 10
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
       2: # PHASE 6.5 — CELL 15
       3: # ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4
       4: # READ-ONLY
       5: # ==============================================================================
       6:
       7: import pandas as pd
       8: from pathlib import Path
       9:
>>>   10: LABEL_QA_PATH = Path(
      11:     r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
      12: )
      13:
      14: EXPECTED_CLIPS = {
      15:     "video001": 40076,
      16:     "video002": 31662,
      17:     "video003": 26273,
      18: }

==============================================================================
CELL : 14
LINE : 11
MATCH : label_qa.csv, label_qa
==============================================================================
       3: # ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4
       4: # READ-ONLY
       5: # ==============================================================================
       6:
       7: import pandas as pd
       8: from pathlib import Path
       9:
      10: LABEL_QA_PATH = Path(
>>>   11:     r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
      12: )
      13:
      14: EXPECTED_CLIPS = {
      15:     "video001": 40076,
      16:     "video002": 31662,
      17:     "video003": 26273,
      18: }
      19:

==============================================================================
CELL : 14
LINE : 20
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
      12: )
      13:
      14: EXPECTED_CLIPS = {
      15:     "video001": 40076,
      16:     "video002": 31662,
      17:     "video003": 26273,
      18: }
      19:
>>>   20: df = pd.read_csv(LABEL_QA_PATH)
      21:
      22: print("=" * 78)
      23: print("PHASE 6.5 — CELL 15")
      24: print("ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4")
      25: print("=" * 78)
      26:
      27: print()
      28: print("Total label_qa rows :", f"{len(df):,}")

==============================================================================
CELL : 14
LINE : 24
MATCH : label_qa
==============================================================================
      16:     "video002": 31662,
      17:     "video003": 26273,
      18: }
      19:
      20: df = pd.read_csv(LABEL_QA_PATH)
      21:
      22: print("=" * 78)
      23: print("PHASE 6.5 — CELL 15")
>>>   24: print("ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4")
      25: print("=" * 78)
      26:
      27: print()
      28: print("Total label_qa rows :", f"{len(df):,}")
      29:
      30: # ------------------------------------------------------------------------------
      31: # VIDEO DISTRIBUTION
      32: # ------------------------------------------------------------------------------

==============================================================================
CELL : 14
LINE : 28
MATCH : label_qa
==============================================================================
      20: df = pd.read_csv(LABEL_QA_PATH)
      21:
      22: print("=" * 78)
      23: print("PHASE 6.5 — CELL 15")
      24: print("ANALYZE LABEL_QA COVERAGE AGAINST PHASE 6 v4")
      25: print("=" * 78)
      26:
      27: print()
>>>   28: print("Total label_qa rows :", f"{len(df):,}")
      29:
      30: # ------------------------------------------------------------------------------
      31: # VIDEO DISTRIBUTION
      32: # ------------------------------------------------------------------------------
      33:
      34: print()
      35: print("-" * 78)
      36: print("VIDEO DISTRIBUTION")

==============================================================================
CELL : 14
LINE : 53
MATCH : label_qa
==============================================================================
      45: for video_id, expected in EXPECTED_CLIPS.items():
      46:
      47:     actual = int(
      48:         video_counts.get(video_id, 0)
      49:     )
      50:
      51:     print(
      52:         f"{video_id}: "
>>>   53:         f"label_qa={actual:,} | "
      54:         f"phase6={expected:,} | "
      55:         f"difference={actual - expected:+,}"
      56:     )
      57:
      58: # ------------------------------------------------------------------------------
      59: # CLIP ID SAMPLE
      60: # ------------------------------------------------------------------------------
      61:

==============================================================================
CELL : 14
LINE : 123
MATCH : label_qa
==============================================================================
     115:
     116: print(
     117:     "video003 rows :",
     118:     f"{len(video003):,}"
     119: )
     120:
     121: if len(video003) == 0:
     122:     print(
>>>  123:         "❌ label_qa has NO video003"
     124:     )
     125: else:
     126:     print(
     127:         "✅ label_qa contains video003"
     128:     )
     129:
     130: # ------------------------------------------------------------------------------
     131: # TRANSCRIPT

==============================================================================
CELL : 14
LINE : 127
MATCH : label_qa
==============================================================================
     119: )
     120:
     121: if len(video003) == 0:
     122:     print(
     123:         "❌ label_qa has NO video003"
     124:     )
     125: else:
     126:     print(
>>>  127:         "✅ label_qa contains video003"
     128:     )
     129:
     130: # ------------------------------------------------------------------------------
     131: # TRANSCRIPT
     132: # ------------------------------------------------------------------------------
     133:
     134: print()
     135: print("-" * 78)

==============================================================================
CELL : 15
LINE : 3
MATCH : label_qa
==============================================================================
       1: # ==============================================================================
       2: # PHASE 6.5 — CELL 16
>>>    3: # TRACE LABEL_QA CREATION SOURCE
       4: # READ-ONLY
       5: # ==============================================================================
       6:
       7: from pathlib import Path
       8: import json
       9: import re
      10:
      11: PROJECT_ROOT = Path(r"C:\LipReadingSSL")

==============================================================================
CELL : 15
LINE : 15
MATCH : label_qa
==============================================================================
       7: from pathlib import Path
       8: import json
       9: import re
      10:
      11: PROJECT_ROOT = Path(r"C:\LipReadingSSL")
      12: NOTEBOOK_DIR = PROJECT_ROOT / "notebooks"
      13:
      14: SEARCH_TERMS = [
>>>   15:     "label_qa",
      16:     "labels.csv",
      17:     "transcript",
      18:     "sentence_id",
      19:     "speaker_id",
      20:     "start_frame",
      21:     "end_frame",
      22:     "to_csv",
      23:     "label",

==============================================================================
CELL : 15
LINE : 29
MATCH : label_qa
==============================================================================
      21:     "end_frame",
      22:     "to_csv",
      23:     "label",
      24:     "annotation",
      25: ]
      26:
      27: print("=" * 78)
      28: print("PHASE 6.5 — CELL 16")
>>>   29: print("TRACE LABEL_QA CREATION SOURCE")
      30: print("=" * 78)
      31:
      32: print()
      33: print("Notebook directory:")
      34: print(NOTEBOOK_DIR)
      35:
      36: notebooks = sorted(
      37:     NOTEBOOK_DIR.glob("*.ipynb")

==============================================================================
CELL : 18
LINE : 3
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
       1: # ==============================================================================
       2: # PHASE 6.5 — CELL 19
>>>    3: # TRACE LABEL_QA_PATH DEFINITION AND USAGE
       4: # READ-ONLY
       5: # ==============================================================================
       6:
       7: from pathlib import Path
       8: import json
       9:
      10: NOTEBOOK_PATH = Path(
      11:     r"C:\LipReadingSSL\notebooks\phase6.5_clip_source_alignment.ipynb"

==============================================================================
CELL : 18
LINE : 15
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
       7: from pathlib import Path
       8: import json
       9:
      10: NOTEBOOK_PATH = Path(
      11:     r"C:\LipReadingSSL\notebooks\phase6.5_clip_source_alignment.ipynb"
      12: )
      13:
      14: SEARCH_TERMS = [
>>>   15:     "LABEL_QA_PATH",
      16:     "label_qa.csv",
      17:     "label_qa",
      18: ]
      19:
      20: print("=" * 78)
      21: print("PHASE 6.5 — CELL 19")
      22: print("TRACE LABEL_QA_PATH DEFINITION AND USAGE")
      23: print("READ-ONLY")

==============================================================================
CELL : 18
LINE : 16
MATCH : label_qa.csv, label_qa
==============================================================================
       8: import json
       9:
      10: NOTEBOOK_PATH = Path(
      11:     r"C:\LipReadingSSL\notebooks\phase6.5_clip_source_alignment.ipynb"
      12: )
      13:
      14: SEARCH_TERMS = [
      15:     "LABEL_QA_PATH",
>>>   16:     "label_qa.csv",
      17:     "label_qa",
      18: ]
      19:
      20: print("=" * 78)
      21: print("PHASE 6.5 — CELL 19")
      22: print("TRACE LABEL_QA_PATH DEFINITION AND USAGE")
      23: print("READ-ONLY")
      24: print("=" * 78)

==============================================================================
CELL : 18
LINE : 17
MATCH : label_qa
==============================================================================
       9:
      10: NOTEBOOK_PATH = Path(
      11:     r"C:\LipReadingSSL\notebooks\phase6.5_clip_source_alignment.ipynb"
      12: )
      13:
      14: SEARCH_TERMS = [
      15:     "LABEL_QA_PATH",
      16:     "label_qa.csv",
>>>   17:     "label_qa",
      18: ]
      19:
      20: print("=" * 78)
      21: print("PHASE 6.5 — CELL 19")
      22: print("TRACE LABEL_QA_PATH DEFINITION AND USAGE")
      23: print("READ-ONLY")
      24: print("=" * 78)
      25:

==============================================================================
CELL : 18
LINE : 22
MATCH : LABEL_QA_PATH, label_qa
==============================================================================
      14: SEARCH_TERMS = [
      15:     "LABEL_QA_PATH",
      16:     "label_qa.csv",
      17:     "label_qa",
      18: ]
      19:
      20: print("=" * 78)
      21: print("PHASE 6.5 — CELL 19")
>>>   22: print("TRACE LABEL_QA_PATH DEFINITION AND USAGE")
      23: print("READ-ONLY")
      24: print("=" * 78)
      25:
      26: if not NOTEBOOK_PATH.exists():
      27:     raise FileNotFoundError(
      28:         f"Notebook not found:\n{NOTEBOOK_PATH}"
      29:     )
      30:

==============================================================================
TOTAL MATCHES : 24
==============================================================================

CELL 19 COMPLETE — READ ONLY
==============================================================================

In [26]:
# ==============================================================================
# PHASE 6.5 — CELL 20
# FIND ALL CODE THAT WRITES CSV / LABEL / ANNOTATION OUTPUT
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json
import re

PROJECT_ROOT = Path(
    r"C:\LipReadingSSL"
)

NOTEBOOK_DIR = PROJECT_ROOT / "notebooks"

print("=" * 78)
print("PHASE 6.5 — CELL 20")
print("FIND ALL CODE THAT WRITES CSV / LABEL / ANNOTATION OUTPUT")
print("READ-ONLY")
print("=" * 78)

NOTEBOOKS = sorted(
    NOTEBOOK_DIR.glob("*.ipynb")
)

# ----------------------------------------------------------------------
# Patterns that indicate file creation / writing
# ----------------------------------------------------------------------

WRITE_PATTERNS = [
    r"\.to_csv\s*\(",
    r"\.to_json\s*\(",
    r"\.to_excel\s*\(",
    r"open\s*\([^)]*,\s*[\"']w",
    r"open\s*\([^)]*,\s*[\"']a",
    r"json\.dump\s*\(",
    r"csv\.writer",
]

# ----------------------------------------------------------------------
# Terms strongly related to annotation / labeling
# ----------------------------------------------------------------------

LABEL_TERMS = [
    "label",
    "labels",
    "annotation",
    "annot",
    "transcript",
    "sentence",
    "speaker",
    "normalized_text",
    "text",
    "start_frame",
    "end_frame",
    "clip_id",
    "dataset_id",
]

total_matches = 0

for notebook_path in NOTEBOOKS:

    try:
        with open(
            notebook_path,
            "r",
            encoding="utf-8"
        ) as f:
            notebook = json.load(f)

    except Exception as e:

        print()
        print(
            f"⚠️ Cannot read: {notebook_path.name}"
        )
        print(e)
        continue

    notebook_matches = 0

    for cell_index, cell in enumerate(
        notebook.get("cells", [])
    ):

        source = "".join(
            cell.get("source", [])
        )

        if not source.strip():
            continue

        lines = source.splitlines()

        for line_index, line in enumerate(lines):

            # ----------------------------------------------------------
            # Is this a write operation?
            # ----------------------------------------------------------

            is_write = any(
                re.search(
                    pattern,
                    line,
                    flags=re.IGNORECASE
                )
                for pattern in WRITE_PATTERNS
            )

            if not is_write:
                continue

            # ----------------------------------------------------------
            # Inspect nearby context
            # ----------------------------------------------------------

            context_start = max(
                0,
                line_index - 8
            )

            context_end = min(
                len(lines),
                line_index + 9
            )

            context = "\n".join(
                lines[
                    context_start:context_end
                ]
            ).lower()

            related_terms = [
                term
                for term in LABEL_TERMS
                if term.lower() in context
            ]

            # ----------------------------------------------------------
            # Only show writes related to labeling/data metadata
            # ----------------------------------------------------------

            if not related_terms:
                continue

            total_matches += 1
            notebook_matches += 1

            print()
            print("=" * 78)
            print(
                f"NOTEBOOK : {notebook_path.name}"
            )
            print(
                f"CELL     : {cell_index}"
            )
            print(
                f"LINE     : {line_index + 1}"
            )
            print(
                "RELATED  : "
                + ", ".join(
                    sorted(set(related_terms))
                )
            )
            print("=" * 78)

            for i in range(
                context_start,
                context_end
            ):

                marker = (
                    ">>> "
                    if i == line_index
                    else "    "
                )

                print(
                    f"{marker}{i + 1:4d}: "
                    f"{lines[i]}"
                )

    print()
    print(
        f"{notebook_path.name} "
        f"→ {notebook_matches} relevant write blocks"
    )

print()
print("=" * 78)
print(
    f"TOTAL RELEVANT WRITE BLOCKS : {total_matches}"
)
print("=" * 78)

print()
print("CELL 20 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 20
FIND ALL CODE THAT WRITES CSV / LABEL / ANNOTATION OUTPUT
READ-ONLY
==============================================================================

dataset_master.ipynb → 0 relevant write blocks

phase1_video_preparation.ipynb → 0 relevant write blocks

phase2_face_detection_tracking.ipynb → 0 relevant write blocks

phase3_face_alignment.ipynb → 0 relevant write blocks

phase4_face_crop.ipynb → 0 relevant write blocks

phase5_mouth_crop.ipynb → 0 relevant write blocks

phase6.5_clip_source_alignment.ipynb → 0 relevant write blocks

phase6_clip_Generation.ipynb → 0 relevant write blocks

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 6
LINE     : 173
RELATED  : text
==============================================================================
     165:     vocabulary_summary
     166: )
     167:
     168:
     169: # -------------------------------------------------
     170: # 8. Save
     171: # -------------------------------------------------
     172:
>>>  173: vocabulary_df.to_csv(
     174:     ANALYSIS_DIR / "vocabulary_distribution.csv",
     175:     index=False,
     176:     encoding="utf-8-sig"
     177: )
     178:
     179: text_split_df.to_csv(
     180:     ANALYSIS_DIR / "vocabulary_by_split.csv",
     181:     encoding="utf-8-sig"

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 6
LINE     : 179
RELATED  : text
==============================================================================
     171: # -------------------------------------------------
     172:
     173: vocabulary_df.to_csv(
     174:     ANALYSIS_DIR / "vocabulary_distribution.csv",
     175:     index=False,
     176:     encoding="utf-8-sig"
     177: )
     178:
>>>  179: text_split_df.to_csv(
     180:     ANALYSIS_DIR / "vocabulary_by_split.csv",
     181:     encoding="utf-8-sig"
     182: )
     183:
     184: text_video_df.to_csv(
     185:     ANALYSIS_DIR / "vocabulary_by_video.csv",
     186:     encoding="utf-8-sig"
     187: )

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 6
LINE     : 184
RELATED  : text
==============================================================================
     176:     encoding="utf-8-sig"
     177: )
     178:
     179: text_split_df.to_csv(
     180:     ANALYSIS_DIR / "vocabulary_by_split.csv",
     181:     encoding="utf-8-sig"
     182: )
     183:
>>>  184: text_video_df.to_csv(
     185:     ANALYSIS_DIR / "vocabulary_by_video.csv",
     186:     encoding="utf-8-sig"
     187: )
     188:
     189: vocabulary_summary.to_csv(
     190:     ANALYSIS_DIR / "vocabulary_summary.csv",
     191:     index=False,
     192:     encoding="utf-8-sig"

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 6
LINE     : 189
RELATED  : text
==============================================================================
     181:     encoding="utf-8-sig"
     182: )
     183:
     184: text_video_df.to_csv(
     185:     ANALYSIS_DIR / "vocabulary_by_video.csv",
     186:     encoding="utf-8-sig"
     187: )
     188:
>>>  189: vocabulary_summary.to_csv(
     190:     ANALYSIS_DIR / "vocabulary_summary.csv",
     191:     index=False,
     192:     encoding="utf-8-sig"
     193: )
     194:
     195:
     196: # -------------------------------------------------
     197: # 9. Final

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 7
LINE     : 216
RELATED  : speaker
==============================================================================
     208:     video_split
     209: )
     210:
     211:
     212: # -------------------------------------------------
     213: # 7. Save
     214: # -------------------------------------------------
     215:
>>>  216: speaker_distribution.to_csv(
     217:     ANALYSIS_DIR / "speaker_distribution.csv",
     218:     index=False,
     219:     encoding="utf-8-sig"
     220: )
     221:
     222: video_distribution.to_csv(
     223:     ANALYSIS_DIR / "video_distribution.csv",
     224:     index=False,

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 7
LINE     : 222
RELATED  : speaker
==============================================================================
     214: # -------------------------------------------------
     215:
     216: speaker_distribution.to_csv(
     217:     ANALYSIS_DIR / "speaker_distribution.csv",
     218:     index=False,
     219:     encoding="utf-8-sig"
     220: )
     221:
>>>  222: video_distribution.to_csv(
     223:     ANALYSIS_DIR / "video_distribution.csv",
     224:     index=False,
     225:     encoding="utf-8-sig"
     226: )
     227:
     228: speaker_split.to_csv(
     229:     ANALYSIS_DIR / "speaker_split.csv",
     230:     index=False,

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 7
LINE     : 228
RELATED  : speaker
==============================================================================
     220: )
     221:
     222: video_distribution.to_csv(
     223:     ANALYSIS_DIR / "video_distribution.csv",
     224:     index=False,
     225:     encoding="utf-8-sig"
     226: )
     227:
>>>  228: speaker_split.to_csv(
     229:     ANALYSIS_DIR / "speaker_split.csv",
     230:     index=False,
     231:     encoding="utf-8-sig"
     232: )
     233:
     234: video_split.to_csv(
     235:     ANALYSIS_DIR / "video_split.csv",
     236:     index=False,

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 7
LINE     : 234
RELATED  : speaker
==============================================================================
     226: )
     227:
     228: speaker_split.to_csv(
     229:     ANALYSIS_DIR / "speaker_split.csv",
     230:     index=False,
     231:     encoding="utf-8-sig"
     232: )
     233:
>>>  234: video_split.to_csv(
     235:     ANALYSIS_DIR / "video_split.csv",
     236:     index=False,
     237:     encoding="utf-8-sig"
     238: )
     239:
     240:
     241: # -------------------------------------------------
     242: # 8. Basic QA

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 8
LINE     : 296
RELATED  : dataset_id
==============================================================================
     288:     f"{len(metadata_issue_df):,}"
     289: )
     290:
     291:
     292: # -------------------------------------------------
     293: # 10. Save
     294: # -------------------------------------------------
     295:
>>>  296: duplicate_key_df.to_csv(
     297:     ANALYSIS_DIR / "duplicate_dataset_clip_keys.csv",
     298:     index=False,
     299:     encoding="utf-8-sig"
     300: )
     301:
     302: duplicate_id_df.to_csv(
     303:     ANALYSIS_DIR / "duplicate_dataset_ids.csv",
     304:     index=False,

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 8
LINE     : 302
RELATED  : dataset_id
==============================================================================
     294: # -------------------------------------------------
     295:
     296: duplicate_key_df.to_csv(
     297:     ANALYSIS_DIR / "duplicate_dataset_clip_keys.csv",
     298:     index=False,
     299:     encoding="utf-8-sig"
     300: )
     301:
>>>  302: duplicate_id_df.to_csv(
     303:     ANALYSIS_DIR / "duplicate_dataset_ids.csv",
     304:     index=False,
     305:     encoding="utf-8-sig"
     306: )
     307:
     308: frame_outlier_df.to_csv(
     309:     ANALYSIS_DIR / "frame_outliers.csv",
     310:     index=False,

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 8
LINE     : 308
RELATED  : dataset_id
==============================================================================
     300: )
     301:
     302: duplicate_id_df.to_csv(
     303:     ANALYSIS_DIR / "duplicate_dataset_ids.csv",
     304:     index=False,
     305:     encoding="utf-8-sig"
     306: )
     307:
>>>  308: frame_outlier_df.to_csv(
     309:     ANALYSIS_DIR / "frame_outliers.csv",
     310:     index=False,
     311:     encoding="utf-8-sig"
     312: )
     313:
     314: short_clip_df.to_csv(
     315:     ANALYSIS_DIR / "short_clips.csv",
     316:     index=False,

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 9
LINE     : 318
RELATED  : speaker
==============================================================================
     310: # -------------------------------------------------
     311:
     312: split_distribution.to_csv(
     313:     ANALYSIS_DIR / "distribution_split.csv",
     314:     index=False,
     315:     encoding="utf-8-sig"
     316: )
     317:
>>>  318: video_distribution.to_csv(
     319:     ANALYSIS_DIR / "distribution_video.csv",
     320:     index=False,
     321:     encoding="utf-8-sig"
     322: )
     323:
     324: speaker_distribution.to_csv(
     325:     ANALYSIS_DIR / "distribution_speaker.csv",
     326:     index=False,

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 9
LINE     : 324
RELATED  : sentence, speaker
==============================================================================
     316: )
     317:
     318: video_distribution.to_csv(
     319:     ANALYSIS_DIR / "distribution_video.csv",
     320:     index=False,
     321:     encoding="utf-8-sig"
     322: )
     323:
>>>  324: speaker_distribution.to_csv(
     325:     ANALYSIS_DIR / "distribution_speaker.csv",
     326:     index=False,
     327:     encoding="utf-8-sig"
     328: )
     329:
     330: sentence_distribution.to_csv(
     331:     ANALYSIS_DIR / "distribution_sentence.csv",
     332:     index=False,

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 9
LINE     : 330
RELATED  : sentence, speaker
==============================================================================
     322: )
     323:
     324: speaker_distribution.to_csv(
     325:     ANALYSIS_DIR / "distribution_speaker.csv",
     326:     index=False,
     327:     encoding="utf-8-sig"
     328: )
     329:
>>>  330: sentence_distribution.to_csv(
     331:     ANALYSIS_DIR / "distribution_sentence.csv",
     332:     index=False,
     333:     encoding="utf-8-sig"
     334: )
     335:
     336: frame_statistics.to_csv(
     337:     ANALYSIS_DIR / "frame_statistics.csv",
     338:     index=False,

==============================================================================
NOTEBOOK : phase7.5_dataset_QA.ipynb
CELL     : 9
LINE     : 336
RELATED  : sentence
==============================================================================
     328: )
     329:
     330: sentence_distribution.to_csv(
     331:     ANALYSIS_DIR / "distribution_sentence.csv",
     332:     index=False,
     333:     encoding="utf-8-sig"
     334: )
     335:
>>>  336: frame_statistics.to_csv(
     337:     ANALYSIS_DIR / "frame_statistics.csv",
     338:     index=False,
     339:     encoding="utf-8-sig"
     340: )
     341:
     342: balance_summary.to_csv(
     343:     ANALYSIS_DIR / "balance_summary.csv",
     344:     index=False,

phase7.5_dataset_QA.ipynb → 15 relevant write blocks

==============================================================================
NOTEBOOK : phase7_dataset_builder.ipynb
CELL     : 4
LINE     : 81
RELATED  : label
==============================================================================
      73:
      74:
      75: label_template_df = pd.DataFrame(
      76:     template_rows,
      77:     columns=LABEL_SOURCE_COLUMNS
      78: )
      79:
      80:
>>>   81: label_template_df.to_csv(
      82:     LABEL_SOURCE_TEMPLATE,
      83:     index=False,
      84:     encoding="utf-8-sig"
      85: )
      86:
      87:
      88: print(
      89:     f"Template saved:"

==============================================================================
NOTEBOOK : phase7_dataset_builder.ipynb
CELL     : 8
LINE     : 266
RELATED  : sentence
==============================================================================
     258:
     259:
     260: mapping_report_path = (
     261:     REPORT_ROOT
     262:     / "sentence_clip_mapping.csv"
     263: )
     264:
     265:
>>>  266: mapping_df.to_csv(
     267:     mapping_report_path,
     268:     index=False,
     269:     encoding="utf-8-sig"
     270: )
     271:
     272:
     273: print()
     274: print(

==============================================================================
NOTEBOOK : phase7_dataset_builder.ipynb
CELL     : 9
LINE     : 109
RELATED  : transcript
==============================================================================
     101:
     102: print(
     103:     video_coverage.to_string(
     104:         index=False
     105:     )
     106: )
     107:
     108:
>>>  109: video_coverage.to_csv(
     110:     REPORT_ROOT
     111:     / "transcript_coverage.csv",
     112:     index=False,
     113:     encoding="utf-8-sig"
     114: )
     115:
     116:
     117: # ============================================================

phase7_dataset_builder.ipynb → 3 relevant write blocks

==============================================================================
TOTAL RELEVANT WRITE BLOCKS : 18
==============================================================================

CELL 20 COMPLETE — READ ONLY
==============================================================================

In [27]:
# ==============================================================================
# PHASE 6.5 — CELL 21
# TRACE PHASE75_DATASET_DF CREATION
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json
import re

NOTEBOOK_PATH = Path(
    r"C:\LipReadingSSL\notebooks\phase7.5_dataset_QA.ipynb"
)

print("=" * 78)
print("PHASE 6.5 — CELL 21")
print("TRACE PHASE75_DATASET_DF CREATION")
print("READ-ONLY")
print("=" * 78)

if not NOTEBOOK_PATH.exists():
    raise FileNotFoundError(
        f"Notebook not found:\n{NOTEBOOK_PATH}"
    )

with open(
    NOTEBOOK_PATH,
    "r",
    encoding="utf-8"
) as f:
    notebook = json.load(f)

cells = notebook.get("cells", [])

print()
print(f"Notebook : {NOTEBOOK_PATH}")
print(f"Cells    : {len(cells):,}")

# ------------------------------------------------------------------------------
# Search terms
# ------------------------------------------------------------------------------

SEARCH_PATTERNS = [
    r"PHASE75_DATASET_DF",
    r"dataset_master",
    r"pd\.read_csv",
    r"read_csv",
    r"dataset_clip_key",
    r"transcript",
    r"sentence_id",
    r"speaker_id",
]

# ------------------------------------------------------------------------------
# Search every cell
# ------------------------------------------------------------------------------

for cell_index, cell in enumerate(cells):

    source = "".join(
        cell.get("source", [])
    )

    if not source.strip():
        continue

    lines = source.splitlines()

    matched_lines = []

    for line_index, line in enumerate(lines):

        matched_terms = []

        for pattern in SEARCH_PATTERNS:

            if re.search(
                pattern,
                line,
                flags=re.IGNORECASE
            ):
                matched_terms.append(pattern)

        if matched_terms:
            matched_lines.append(
                (
                    line_index,
                    matched_terms
                )
            )

    if not matched_lines:
        continue

    print()
    print("=" * 78)
    print(
        f"CELL : {cell_index}"
    )
    print("=" * 78)

    shown = set()

    for line_index, matched_terms in matched_lines:

        # --------------------------------------------------------------
        # Show context around each match
        # --------------------------------------------------------------

        start = max(
            0,
            line_index - 5
        )

        end = min(
            len(lines),
            line_index + 6
        )

        block_key = (
            start,
            end
        )

        if block_key in shown:
            continue

        shown.add(block_key)

        print()
        print(
            f"--- lines {start + 1}–{end} ---"
        )

        for i in range(start, end):

            marker = (
                ">>> "
                if i == line_index
                else "    "
            )

            print(
                f"{marker}{i + 1:4d}: "
                f"{lines[i]}"
            )

        print(
            "MATCHED TERMS : "
            + ", ".join(
                matched_terms
            )
        )

print()
print("=" * 78)
print("CELL 21 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 21
TRACE PHASE75_DATASET_DF CREATION
READ-ONLY
==============================================================================

Notebook : C:\LipReadingSSL\notebooks\phase7.5_dataset_QA.ipynb
Cells    : 15

==============================================================================
CELL : 1
==============================================================================

--- lines 66–76 ---
      66:
      67: # -------------------------------------------------
      68: # Dataset Files
      69: # -------------------------------------------------
      70:
>>>   71: MASTER_FILE = DATASET_DIR / "dataset_master.csv"
      72:
      73: LABEL_FILE = DATASET_DIR / "labels.csv"
      74:
      75: SPLIT_FILE = DATASET_DIR / "split.csv"
      76:
MATCHED TERMS : dataset_master

==============================================================================
CELL : 2
==============================================================================

--- lines 1–11 ---
       1: # ============================================================
       2: # PHASE 7.5 — CELL 3
       3: # LOAD EXISTING PHASE 7 DATASET
       4: #
       5: # Source:
>>>    6: #   C:\LipReadingSSL\output\dataset\dataset_master.csv
       7: #
       8: # IMPORTANT:
       9: # - Uses the REAL Phase 7 dataset_master.csv schema
      10: # - Does NOT require Phase 6 shard columns
      11: # - Does NOT modify the source CSV
MATCHED TERMS : dataset_master

--- lines 4–14 ---
       4: #
       5: # Source:
       6: #   C:\LipReadingSSL\output\dataset\dataset_master.csv
       7: #
       8: # IMPORTANT:
>>>    9: # - Uses the REAL Phase 7 dataset_master.csv schema
      10: # - Does NOT require Phase 6 shard columns
      11: # - Does NOT modify the source CSV
      12: # - Does NOT create fallback IDs
      13: # ============================================================
      14:
MATCHED TERMS : dataset_master

--- lines 28–38 ---
      28:
      29: LIPREADING_ROOT = Path(
      30:     r"C:\LipReadingSSL"
      31: )
      32:
>>>   33: DATASET_MASTER_PATH = (
      34:     LIPREADING_ROOT
      35:     / "output"
      36:     / "dataset"
      37:     / "dataset_master.csv"
      38: )
MATCHED TERMS : dataset_master

--- lines 32–42 ---
      32:
      33: DATASET_MASTER_PATH = (
      34:     LIPREADING_ROOT
      35:     / "output"
      36:     / "dataset"
>>>   37:     / "dataset_master.csv"
      38: )
      39:
      40:
      41: print(
      42:     f"Dataset file : {DATASET_MASTER_PATH}"
MATCHED TERMS : dataset_master

--- lines 37–47 ---
      37:     / "dataset_master.csv"
      38: )
      39:
      40:
      41: print(
>>>   42:     f"Dataset file : {DATASET_MASTER_PATH}"
      43: )
      44:
      45:
      46: # ============================================================
      47: # 2. File check
MATCHED TERMS : dataset_master

--- lines 45–55 ---
      45:
      46: # ============================================================
      47: # 2. File check
      48: # ============================================================
      49:
>>>   50: if not DATASET_MASTER_PATH.exists():
      51:
      52:     raise FileNotFoundError(
      53:         "dataset_master.csv not found:\n"
      54:         f"{DATASET_MASTER_PATH}"
      55:     )
MATCHED TERMS : dataset_master

--- lines 48–58 ---
      48: # ============================================================
      49:
      50: if not DATASET_MASTER_PATH.exists():
      51:
      52:     raise FileNotFoundError(
>>>   53:         "dataset_master.csv not found:\n"
      54:         f"{DATASET_MASTER_PATH}"
      55:     )
      56:
      57:
      58: # ============================================================
MATCHED TERMS : dataset_master

--- lines 49–59 ---
      49:
      50: if not DATASET_MASTER_PATH.exists():
      51:
      52:     raise FileNotFoundError(
      53:         "dataset_master.csv not found:\n"
>>>   54:         f"{DATASET_MASTER_PATH}"
      55:     )
      56:
      57:
      58: # ============================================================
      59: # 3. Load
MATCHED TERMS : dataset_master

--- lines 57–67 ---
      57:
      58: # ============================================================
      59: # 3. Load
      60: # ============================================================
      61:
>>>   62: dataset_df = pd.read_csv(
      63:     DATASET_MASTER_PATH,
      64:     low_memory=False
      65: )
      66:
      67:
MATCHED TERMS : pd\.read_csv, read_csv

--- lines 58–68 ---
      58: # ============================================================
      59: # 3. Load
      60: # ============================================================
      61:
      62: dataset_df = pd.read_csv(
>>>   63:     DATASET_MASTER_PATH,
      64:     low_memory=False
      65: )
      66:
      67:
      68: # ============================================================
MATCHED TERMS : dataset_master

--- lines 66–76 ---
      66:
      67:
      68: # ============================================================
      69: # 4. Real Phase 7 dataset schema
      70: #
>>>   71: # Based on the actual dataset_master.csv inspected by user.
      72: # ============================================================
      73:
      74: EXPECTED_COLUMNS = [
      75:
      76:     "dataset_id",
MATCHED TERMS : dataset_master

--- lines 83–93 ---
      83:     "end_frame",
      84:     "num_frames",
      85:     "clip_length",
      86:     "stride",
      87:
>>>   88:     "speaker_id",
      89:     "sentence_id",
      90:     "transcript",
      91:     "normalized_text",
      92:
      93:     "clip_exists",
MATCHED TERMS : speaker_id

--- lines 84–94 ---
      84:     "num_frames",
      85:     "clip_length",
      86:     "stride",
      87:
      88:     "speaker_id",
>>>   89:     "sentence_id",
      90:     "transcript",
      91:     "normalized_text",
      92:
      93:     "clip_exists",
      94:     "frame_exists",
MATCHED TERMS : sentence_id

--- lines 85–95 ---
      85:     "clip_length",
      86:     "stride",
      87:
      88:     "speaker_id",
      89:     "sentence_id",
>>>   90:     "transcript",
      91:     "normalized_text",
      92:
      93:     "clip_exists",
      94:     "frame_exists",
      95:     "has_transcript",
MATCHED TERMS : transcript

--- lines 90–100 ---
      90:     "transcript",
      91:     "normalized_text",
      92:
      93:     "clip_exists",
      94:     "frame_exists",
>>>   95:     "has_transcript",
      96:     "split",
      97:
      98: ]
      99:
     100:
MATCHED TERMS : transcript

--- lines 139–149 ---
     139:
     140:
     141: if missing_columns:
     142:
     143:     raise RuntimeError(
>>>  144:         "dataset_master.csv schema mismatch.\n\n"
     145:         f"Missing columns:\n"
     146:         + "\n".join(
     147:             f" - {column}"
     148:             for column in missing_columns
     149:         )
MATCHED TERMS : dataset_master

--- lines 184–194 ---
     184:
     185: # ============================================================
     186: # 8. Working copy
     187: # ============================================================
     188:
>>>  189: PHASE75_DATASET_DF = (
     190:     dataset_df.copy()
     191: )
     192:
     193:
     194: # ============================================================
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 200–210 ---
     200:     "clip_id",
     201:     "dataset_id",
     202:     "split",
     203: ]:
     204:
>>>  205:     PHASE75_DATASET_DF[column] = (
     206:         PHASE75_DATASET_DF[column]
     207:         .astype(str)
     208:         .str.strip()
     209:     )
     210:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 201–211 ---
     201:     "dataset_id",
     202:     "split",
     203: ]:
     204:
     205:     PHASE75_DATASET_DF[column] = (
>>>  206:         PHASE75_DATASET_DF[column]
     207:         .astype(str)
     208:         .str.strip()
     209:     )
     210:
     211:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 219–229 ---
     219:     "num_frames",
     220:     "clip_length",
     221:     "stride",
     222: ]:
     223:
>>>  224:     PHASE75_DATASET_DF[column] = pd.to_numeric(
     225:         PHASE75_DATASET_DF[column],
     226:         errors="coerce"
     227:     )
     228:
     229:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 220–230 ---
     220:     "clip_length",
     221:     "stride",
     222: ]:
     223:
     224:     PHASE75_DATASET_DF[column] = pd.to_numeric(
>>>  225:         PHASE75_DATASET_DF[column],
     226:         errors="coerce"
     227:     )
     228:
     229:
     230: # ============================================================
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 232–242 ---
     232: # ============================================================
     233:
     234: BOOLEAN_COLUMNS = [
     235:     "clip_exists",
     236:     "frame_exists",
>>>  237:     "has_transcript",
     238: ]
     239:
     240:
     241: def normalize_bool(series):
     242:
MATCHED TERMS : transcript

--- lines 256–266 ---
     256:     )
     257:
     258:
     259: for column in BOOLEAN_COLUMNS:
     260:
>>>  261:     PHASE75_DATASET_DF[column] = normalize_bool(
     262:         PHASE75_DATASET_DF[column]
     263:     )
     264:
     265:
     266: # ============================================================
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 257–267 ---
     257:
     258:
     259: for column in BOOLEAN_COLUMNS:
     260:
     261:     PHASE75_DATASET_DF[column] = normalize_bool(
>>>  262:         PHASE75_DATASET_DF[column]
     263:     )
     264:
     265:
     266: # ============================================================
     267: # 12. Final Cell 3 status
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 272–282 ---
     272: print("CELL 3 COMPLETE")
     273: print("=" * 80)
     274:
     275: print(
     276:     f"Rows loaded       : "
>>>  277:     f"{len(PHASE75_DATASET_DF):,}"
     278: )
     279:
     280: print(
     281:     f"Columns loaded    : "
     282:     f"{len(PHASE75_DATASET_DF.columns)}"
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 277–287 ---
     277:     f"{len(PHASE75_DATASET_DF):,}"
     278: )
     279:
     280: print(
     281:     f"Columns loaded    : "
>>>  282:     f"{len(PHASE75_DATASET_DF.columns)}"
     283: )
     284:
     285: print(
     286:     "Source modified   : NO"
     287: )
MATCHED TERMS : PHASE75_DATASET_DF

==============================================================================
CELL : 3
==============================================================================

--- lines 4–14 ---
       4: #
       5: # Identity:
       6: #   video_id + clip_id
       7: #
       8: # IMPORTANT:
>>>    9: # - Does NOT modify dataset_master.csv
      10: # - Does NOT use shard_id
      11: # - Does NOT use shard_index
      12: # - Does NOT use clip_index
      13: # - Does NOT create fallback IDs
      14: # ============================================================
MATCHED TERMS : dataset_master

--- lines 29–39 ---
      29:
      30:
      31: missing_identity = [
      32:     column
      33:     for column in IDENTITY_COLUMNS
>>>   34:     if column not in PHASE75_DATASET_DF.columns
      35: ]
      36:
      37:
      38: if missing_identity:
      39:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 36–46 ---
      36:
      37:
      38: if missing_identity:
      39:
      40:     raise RuntimeError(
>>>   41:         "Cannot build dataset_clip_key.\n"
      42:         f"Missing identity columns: {missing_identity}"
      43:     )
      44:
      45:
      46: # ============================================================
MATCHED TERMS : dataset_clip_key

--- lines 46–56 ---
      46: # ============================================================
      47: # 2. Check null identity
      48: # ============================================================
      49:
      50: null_identity_mask = (
>>>   51:     PHASE75_DATASET_DF[
      52:         IDENTITY_COLUMNS
      53:     ]
      54:     .isna()
      55:     .any(axis=1)
      56:     |
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 53–63 ---
      53:     ]
      54:     .isna()
      55:     .any(axis=1)
      56:     |
      57:     (
>>>   58:         PHASE75_DATASET_DF[
      59:             IDENTITY_COLUMNS
      60:         ]
      61:         .astype(str)
      62:         .apply(
      63:             lambda col:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 81–91 ---
      81:
      82: if null_identity_count:
      83:
      84:     print()
      85:     print(
>>>   86:         PHASE75_DATASET_DF.loc[
      87:             null_identity_mask,
      88:             IDENTITY_COLUMNS
      89:         ]
      90:         .head(20)
      91:         .to_string(index=False)
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 91–101 ---
      91:         .to_string(index=False)
      92:     )
      93:
      94:     raise RuntimeError(
      95:         "Invalid identity detected. "
>>>   96:         "dataset_clip_key was NOT created."
      97:     )
      98:
      99:
     100: # ============================================================
     101: # 3. Build canonical key
MATCHED TERMS : dataset_clip_key

--- lines 99–109 ---
      99:
     100: # ============================================================
     101: # 3. Build canonical key
     102: # ============================================================
     103:
>>>  104: PHASE75_DATASET_DF[
     105:     "dataset_clip_key"
     106: ] = (
     107:
     108:     PHASE75_DATASET_DF[
     109:         "video_id"
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 100–110 ---
     100: # ============================================================
     101: # 3. Build canonical key
     102: # ============================================================
     103:
     104: PHASE75_DATASET_DF[
>>>  105:     "dataset_clip_key"
     106: ] = (
     107:
     108:     PHASE75_DATASET_DF[
     109:         "video_id"
     110:     ]
MATCHED TERMS : dataset_clip_key

--- lines 103–113 ---
     103:
     104: PHASE75_DATASET_DF[
     105:     "dataset_clip_key"
     106: ] = (
     107:
>>>  108:     PHASE75_DATASET_DF[
     109:         "video_id"
     110:     ]
     111:     .astype(str)
     112:     .str.strip()
     113:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 111–121 ---
     111:     .astype(str)
     112:     .str.strip()
     113:
     114:     + "::"
     115:
>>>  116:     + PHASE75_DATASET_DF[
     117:         "clip_id"
     118:     ]
     119:     .astype(str)
     120:     .str.strip()
     121: )
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 124–134 ---
     124: # ============================================================
     125: # 4. Duplicate check
     126: # ============================================================
     127:
     128: duplicate_mask = (
>>>  129:     PHASE75_DATASET_DF[
     130:         "dataset_clip_key"
     131:     ]
     132:     .duplicated(
     133:         keep=False
     134:     )
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 125–135 ---
     125: # 4. Duplicate check
     126: # ============================================================
     127:
     128: duplicate_mask = (
     129:     PHASE75_DATASET_DF[
>>>  130:         "dataset_clip_key"
     131:     ]
     132:     .duplicated(
     133:         keep=False
     134:     )
     135: )
MATCHED TERMS : dataset_clip_key

--- lines 138–148 ---
     138: duplicate_rows = int(
     139:     duplicate_mask.sum()
     140: )
     141:
     142: duplicate_keys = int(
>>>  143:     PHASE75_DATASET_DF.loc[
     144:         duplicate_mask,
     145:         "dataset_clip_key"
     146:     ]
     147:     .nunique()
     148: )
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 140–150 ---
     140: )
     141:
     142: duplicate_keys = int(
     143:     PHASE75_DATASET_DF.loc[
     144:         duplicate_mask,
>>>  145:         "dataset_clip_key"
     146:     ]
     147:     .nunique()
     148: )
     149:
     150:
MATCHED TERMS : dataset_clip_key

--- lines 161–171 ---
     161:
     162: if duplicate_keys:
     163:
     164:     print()
     165:     print(
>>>  166:         PHASE75_DATASET_DF.loc[
     167:             duplicate_mask,
     168:             [
     169:                 "video_id",
     170:                 "clip_id",
     171:                 "dataset_clip_key",
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 166–176 ---
     166:         PHASE75_DATASET_DF.loc[
     167:             duplicate_mask,
     168:             [
     169:                 "video_id",
     170:                 "clip_id",
>>>  171:                 "dataset_clip_key",
     172:             ]
     173:         ]
     174:         .head(20)
     175:         .to_string(index=False)
     176:     )
MATCHED TERMS : dataset_clip_key

--- lines 174–184 ---
     174:         .head(20)
     175:         .to_string(index=False)
     176:     )
     177:
     178:     raise RuntimeError(
>>>  179:         "Duplicate dataset_clip_key detected."
     180:     )
     181:
     182:
     183: # ============================================================
     184: # 5. Preview
MATCHED TERMS : dataset_clip_key

--- lines 188–198 ---
     188: print("=" * 80)
     189: print("DATASET CLIP KEY PREVIEW")
     190: print("=" * 80)
     191:
     192: print(
>>>  193:     PHASE75_DATASET_DF[
     194:         [
     195:             "video_id",
     196:             "clip_id",
     197:             "dataset_clip_key",
     198:         ]
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 192–202 ---
     192: print(
     193:     PHASE75_DATASET_DF[
     194:         [
     195:             "video_id",
     196:             "clip_id",
>>>  197:             "dataset_clip_key",
     198:         ]
     199:     ]
     200:     .head(10)
     201:     .to_string(index=False)
     202: )
MATCHED TERMS : dataset_clip_key

--- lines 211–221 ---
     211: print("CELL 4 COMPLETE")
     212: print("=" * 80)
     213:
     214: print(
     215:     f"Dataset rows : "
>>>  216:     f"{len(PHASE75_DATASET_DF):,}"
     217: )
     218:
     219: print(
     220:     f"Unique keys  : "
     221:     f"{PHASE75_DATASET_DF['dataset_clip_key'].nunique():,}"
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 216–226 ---
     216:     f"{len(PHASE75_DATASET_DF):,}"
     217: )
     218:
     219: print(
     220:     f"Unique keys  : "
>>>  221:     f"{PHASE75_DATASET_DF['dataset_clip_key'].nunique():,}"
     222: )
     223:
     224: print(
     225:     "Key identity : video_id + clip_id"
     226: )
MATCHED TERMS : PHASE75_DATASET_DF, dataset_clip_key

==============================================================================
CELL : 4
==============================================================================

--- lines 1–10 ---
       1: # ============================================================
       2: # PHASE 7.5 — CELL 5 v2
       3: # STRUCTURAL DATASET QA
       4: #
>>>    5: # Based on REAL dataset_master.csv schema
       6: #
       7: # IMPORTANT:
       8: # - Do NOT assume:
       9: #       num_frames = end_frame - start_frame + 1
      10: #
MATCHED TERMS : dataset_master

--- lines 10–20 ---
      10: #
      11: # - Phase 7 dataset contains clip metadata whose
      12: #   num_frames / clip_length are dataset-level attributes.
      13: #
      14: # - This cell validates structural consistency only.
>>>   15: # - It does NOT modify dataset_master.csv.
      16: # - It does NOT modify clip_npy.
      17: # ============================================================
      18:
      19: print("=" * 80)
      20: print("PHASE 7.5 — CELL 5 v2 STRUCTURAL DATASET QA")

In [28]:
# ==============================================================================
# PHASE 6.5 — CELL 22
# TRACE PHASE 7.5 DATASET / LABEL LOADING
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json
import re

NOTEBOOK_PATH = Path(
    r"C:\LipReadingSSL\notebooks\phase7.5_dataset_QA.ipynb"
)

print("=" * 78)
print("PHASE 6.5 — CELL 22")
print("TRACE PHASE 7.5 DATASET / LABEL LOADING")
print("READ-ONLY")
print("=" * 78)

with open(
    NOTEBOOK_PATH,
    "r",
    encoding="utf-8"
) as f:
    notebook = json.load(f)

cells = notebook.get("cells", [])

SEARCH_PATTERNS = [
    r"DATASET_DIR",
    r"MASTER_FILE",
    r"LABEL_FILE",
    r"SPLIT_FILE",
    r"PHASE75_DATASET_DF",
    r"pd\.read_csv",
    r"read_csv",
    r"labels\.csv",
    r"dataset_master\.csv",
    r"split\.csv",
]

for cell_index, cell in enumerate(cells):

    source = "".join(
        cell.get("source", [])
    )

    if not source.strip():
        continue

    lines = source.splitlines()

    matches = []

    for line_index, line in enumerate(lines):

        matched_terms = []

        for pattern in SEARCH_PATTERNS:

            if re.search(
                pattern,
                line,
                flags=re.IGNORECASE
            ):
                matched_terms.append(pattern)

        if matched_terms:
            matches.append(
                (line_index, matched_terms)
            )

    if not matches:
        continue

    print()
    print("=" * 78)
    print(f"CELL : {cell_index}")
    print("=" * 78)

    shown_ranges = set()

    for line_index, matched_terms in matches:

        start = max(
            0,
            line_index - 7
        )

        end = min(
            len(lines),
            line_index + 8
        )

        block = (start, end)

        if block in shown_ranges:
            continue

        shown_ranges.add(block)

        print()
        print(
            f"--- lines {start + 1}–{end} ---"
        )

        for i in range(start, end):

            marker = (
                ">>> "
                if i == line_index
                else "    "
            )

            print(
                f"{marker}{i + 1:4d}: "
                f"{lines[i]}"
            )

        print(
            "MATCHED TERMS : "
            + ", ".join(matched_terms)
        )

print()
print("=" * 78)
print("CELL 22 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 22
TRACE PHASE 7.5 DATASET / LABEL LOADING
READ-ONLY
==============================================================================

==============================================================================
CELL : 1
==============================================================================

--- lines 27–41 ---
      27:
      28: # -------------------------------------------------
      29: # Phase 7 Output
      30: # -------------------------------------------------
      31:
      32: VIDEO_DIR = OUTPUT_DIR
      33:
>>>   34: DATASET_DIR = OUTPUT_DIR / "dataset"
      35:
      36: # -------------------------------------------------
      37: # Phase 7.5 Output
      38: # -------------------------------------------------
      39:
      40: ANALYSIS_DIR = DATASET_DIR / "analysis"
      41:
MATCHED TERMS : DATASET_DIR

--- lines 33–47 ---
      33:
      34: DATASET_DIR = OUTPUT_DIR / "dataset"
      35:
      36: # -------------------------------------------------
      37: # Phase 7.5 Output
      38: # -------------------------------------------------
      39:
>>>   40: ANALYSIS_DIR = DATASET_DIR / "analysis"
      41:
      42: GRAPH_DIR = ANALYSIS_DIR / "graphs"
      43:
      44: REPORT_DIR = ANALYSIS_DIR / "reports"
      45:
      46: VOCAB_DIR = ANALYSIS_DIR / "vocabulary"
      47:
MATCHED TERMS : DATASET_DIR

--- lines 48–62 ---
      48: HISTORY_DIR = ANALYSIS_DIR / "history"
      49:
      50: # -------------------------------------------------
      51: # Create directories
      52: # -------------------------------------------------
      53:
      54: for folder in [
>>>   55:     DATASET_DIR,
      56:     ANALYSIS_DIR,
      57:     GRAPH_DIR,
      58:     REPORT_DIR,
      59:     VOCAB_DIR,
      60:     HISTORY_DIR,
      61: ]:
      62:     folder.mkdir(
MATCHED TERMS : DATASET_DIR

--- lines 64–78 ---
      64:         exist_ok=True
      65:     )
      66:
      67: # -------------------------------------------------
      68: # Dataset Files
      69: # -------------------------------------------------
      70:
>>>   71: MASTER_FILE = DATASET_DIR / "dataset_master.csv"
      72:
      73: LABEL_FILE = DATASET_DIR / "labels.csv"
      74:
      75: SPLIT_FILE = DATASET_DIR / "split.csv"
      76:
      77: TRAIN_FILE = DATASET_DIR / "train.csv"
      78:
MATCHED TERMS : DATASET_DIR, MASTER_FILE, dataset_master\.csv

--- lines 66–80 ---
      66:
      67: # -------------------------------------------------
      68: # Dataset Files
      69: # -------------------------------------------------
      70:
      71: MASTER_FILE = DATASET_DIR / "dataset_master.csv"
      72:
>>>   73: LABEL_FILE = DATASET_DIR / "labels.csv"
      74:
      75: SPLIT_FILE = DATASET_DIR / "split.csv"
      76:
      77: TRAIN_FILE = DATASET_DIR / "train.csv"
      78:
      79: VAL_FILE = DATASET_DIR / "val.csv"
      80:
MATCHED TERMS : DATASET_DIR, LABEL_FILE, labels\.csv

--- lines 68–82 ---
      68: # Dataset Files
      69: # -------------------------------------------------
      70:
      71: MASTER_FILE = DATASET_DIR / "dataset_master.csv"
      72:
      73: LABEL_FILE = DATASET_DIR / "labels.csv"
      74:
>>>   75: SPLIT_FILE = DATASET_DIR / "split.csv"
      76:
      77: TRAIN_FILE = DATASET_DIR / "train.csv"
      78:
      79: VAL_FILE = DATASET_DIR / "val.csv"
      80:
      81: TEST_FILE = DATASET_DIR / "test.csv"
      82:
MATCHED TERMS : DATASET_DIR, SPLIT_FILE, split\.csv

--- lines 70–84 ---
      70:
      71: MASTER_FILE = DATASET_DIR / "dataset_master.csv"
      72:
      73: LABEL_FILE = DATASET_DIR / "labels.csv"
      74:
      75: SPLIT_FILE = DATASET_DIR / "split.csv"
      76:
>>>   77: TRAIN_FILE = DATASET_DIR / "train.csv"
      78:
      79: VAL_FILE = DATASET_DIR / "val.csv"
      80:
      81: TEST_FILE = DATASET_DIR / "test.csv"
      82:
      83: # -------------------------------------------------
      84: # QA Files
MATCHED TERMS : DATASET_DIR

--- lines 72–86 ---
      72:
      73: LABEL_FILE = DATASET_DIR / "labels.csv"
      74:
      75: SPLIT_FILE = DATASET_DIR / "split.csv"
      76:
      77: TRAIN_FILE = DATASET_DIR / "train.csv"
      78:
>>>   79: VAL_FILE = DATASET_DIR / "val.csv"
      80:
      81: TEST_FILE = DATASET_DIR / "test.csv"
      82:
      83: # -------------------------------------------------
      84: # QA Files
      85: # -------------------------------------------------
      86:
MATCHED TERMS : DATASET_DIR

--- lines 74–88 ---
      74:
      75: SPLIT_FILE = DATASET_DIR / "split.csv"
      76:
      77: TRAIN_FILE = DATASET_DIR / "train.csv"
      78:
      79: VAL_FILE = DATASET_DIR / "val.csv"
      80:
>>>   81: TEST_FILE = DATASET_DIR / "test.csv"
      82:
      83: # -------------------------------------------------
      84: # QA Files
      85: # -------------------------------------------------
      86:
      87: FINGERPRINT_FILE = (
      88:     ANALYSIS_DIR / "dataset_fingerprint.json"
MATCHED TERMS : DATASET_DIR

--- lines 124–138 ---
     124:
     125: # -------------------------------------------------
     126: # Print
     127: # -------------------------------------------------
     128:
     129: print(f"Project      : {PROJECT_DIR}")
     130: print(f"Output       : {OUTPUT_DIR}")
>>>  131: print(f"Dataset      : {DATASET_DIR}")
     132: print(f"Analysis     : {ANALYSIS_DIR}")
     133: print(f"Graphs       : {GRAPH_DIR}")
     134: print(f"Reports      : {REPORT_DIR}")
     135: print()
     136: print("Split Ratio")
     137: print(f"Train : {TRAIN_RATIO:.0%}")
     138: print(f"Val   : {VAL_RATIO:.0%}")
MATCHED TERMS : DATASET_DIR

==============================================================================
CELL : 2
==============================================================================

--- lines 1–13 ---
       1: # ============================================================
       2: # PHASE 7.5 — CELL 3
       3: # LOAD EXISTING PHASE 7 DATASET
       4: #
       5: # Source:
>>>    6: #   C:\LipReadingSSL\output\dataset\dataset_master.csv
       7: #
       8: # IMPORTANT:
       9: # - Uses the REAL Phase 7 dataset_master.csv schema
      10: # - Does NOT require Phase 6 shard columns
      11: # - Does NOT modify the source CSV
      12: # - Does NOT create fallback IDs
      13: # ============================================================
MATCHED TERMS : dataset_master\.csv

--- lines 2–16 ---
       2: # PHASE 7.5 — CELL 3
       3: # LOAD EXISTING PHASE 7 DATASET
       4: #
       5: # Source:
       6: #   C:\LipReadingSSL\output\dataset\dataset_master.csv
       7: #
       8: # IMPORTANT:
>>>    9: # - Uses the REAL Phase 7 dataset_master.csv schema
      10: # - Does NOT require Phase 6 shard columns
      11: # - Does NOT modify the source CSV
      12: # - Does NOT create fallback IDs
      13: # ============================================================
      14:
      15: from pathlib import Path
      16: import pandas as pd
MATCHED TERMS : dataset_master\.csv

--- lines 30–44 ---
      30:     r"C:\LipReadingSSL"
      31: )
      32:
      33: DATASET_MASTER_PATH = (
      34:     LIPREADING_ROOT
      35:     / "output"
      36:     / "dataset"
>>>   37:     / "dataset_master.csv"
      38: )
      39:
      40:
      41: print(
      42:     f"Dataset file : {DATASET_MASTER_PATH}"
      43: )
      44:
MATCHED TERMS : dataset_master\.csv

--- lines 46–60 ---
      46: # ============================================================
      47: # 2. File check
      48: # ============================================================
      49:
      50: if not DATASET_MASTER_PATH.exists():
      51:
      52:     raise FileNotFoundError(
>>>   53:         "dataset_master.csv not found:\n"
      54:         f"{DATASET_MASTER_PATH}"
      55:     )
      56:
      57:
      58: # ============================================================
      59: # 3. Load
      60: # ============================================================
MATCHED TERMS : dataset_master\.csv

--- lines 55–69 ---
      55:     )
      56:
      57:
      58: # ============================================================
      59: # 3. Load
      60: # ============================================================
      61:
>>>   62: dataset_df = pd.read_csv(
      63:     DATASET_MASTER_PATH,
      64:     low_memory=False
      65: )
      66:
      67:
      68: # ============================================================
      69: # 4. Real Phase 7 dataset schema
MATCHED TERMS : pd\.read_csv, read_csv

--- lines 64–78 ---
      64:     low_memory=False
      65: )
      66:
      67:
      68: # ============================================================
      69: # 4. Real Phase 7 dataset schema
      70: #
>>>   71: # Based on the actual dataset_master.csv inspected by user.
      72: # ============================================================
      73:
      74: EXPECTED_COLUMNS = [
      75:
      76:     "dataset_id",
      77:     "video_id",
      78:     "clip_id",
MATCHED TERMS : dataset_master\.csv

--- lines 137–151 ---
     137:     if column not in dataset_df.columns
     138: ]
     139:
     140:
     141: if missing_columns:
     142:
     143:     raise RuntimeError(
>>>  144:         "dataset_master.csv schema mismatch.\n\n"
     145:         f"Missing columns:\n"
     146:         + "\n".join(
     147:             f" - {column}"
     148:             for column in missing_columns
     149:         )
     150:     )
     151:
MATCHED TERMS : dataset_master\.csv

--- lines 182–196 ---
     182:     )
     183:
     184:
     185: # ============================================================
     186: # 8. Working copy
     187: # ============================================================
     188:
>>>  189: PHASE75_DATASET_DF = (
     190:     dataset_df.copy()
     191: )
     192:
     193:
     194: # ============================================================
     195: # 9. Basic normalization for QA only
     196: # ============================================================
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 198–212 ---
     198: for column in [
     199:     "video_id",
     200:     "clip_id",
     201:     "dataset_id",
     202:     "split",
     203: ]:
     204:
>>>  205:     PHASE75_DATASET_DF[column] = (
     206:         PHASE75_DATASET_DF[column]
     207:         .astype(str)
     208:         .str.strip()
     209:     )
     210:
     211:
     212: # ============================================================
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 199–213 ---
     199:     "video_id",
     200:     "clip_id",
     201:     "dataset_id",
     202:     "split",
     203: ]:
     204:
     205:     PHASE75_DATASET_DF[column] = (
>>>  206:         PHASE75_DATASET_DF[column]
     207:         .astype(str)
     208:         .str.strip()
     209:     )
     210:
     211:
     212: # ============================================================
     213: # 10. Numeric columns
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 217–231 ---
     217:     "start_frame",
     218:     "end_frame",
     219:     "num_frames",
     220:     "clip_length",
     221:     "stride",
     222: ]:
     223:
>>>  224:     PHASE75_DATASET_DF[column] = pd.to_numeric(
     225:         PHASE75_DATASET_DF[column],
     226:         errors="coerce"
     227:     )
     228:
     229:
     230: # ============================================================
     231: # 11. Boolean-like columns
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 218–232 ---
     218:     "end_frame",
     219:     "num_frames",
     220:     "clip_length",
     221:     "stride",
     222: ]:
     223:
     224:     PHASE75_DATASET_DF[column] = pd.to_numeric(
>>>  225:         PHASE75_DATASET_DF[column],
     226:         errors="coerce"
     227:     )
     228:
     229:
     230: # ============================================================
     231: # 11. Boolean-like columns
     232: # ============================================================
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 254–268 ---
     254:             "no": False,
     255:         })
     256:     )
     257:
     258:
     259: for column in BOOLEAN_COLUMNS:
     260:
>>>  261:     PHASE75_DATASET_DF[column] = normalize_bool(
     262:         PHASE75_DATASET_DF[column]
     263:     )
     264:
     265:
     266: # ============================================================
     267: # 12. Final Cell 3 status
     268: # ============================================================
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 255–269 ---
     255:         })
     256:     )
     257:
     258:
     259: for column in BOOLEAN_COLUMNS:
     260:
     261:     PHASE75_DATASET_DF[column] = normalize_bool(
>>>  262:         PHASE75_DATASET_DF[column]
     263:     )
     264:
     265:
     266: # ============================================================
     267: # 12. Final Cell 3 status
     268: # ============================================================
     269:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 270–284 ---
     270: print()
     271: print("=" * 80)
     272: print("CELL 3 COMPLETE")
     273: print("=" * 80)
     274:
     275: print(
     276:     f"Rows loaded       : "
>>>  277:     f"{len(PHASE75_DATASET_DF):,}"
     278: )
     279:
     280: print(
     281:     f"Columns loaded    : "
     282:     f"{len(PHASE75_DATASET_DF.columns)}"
     283: )
     284:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 275–289 ---
     275: print(
     276:     f"Rows loaded       : "
     277:     f"{len(PHASE75_DATASET_DF):,}"
     278: )
     279:
     280: print(
     281:     f"Columns loaded    : "
>>>  282:     f"{len(PHASE75_DATASET_DF.columns)}"
     283: )
     284:
     285: print(
     286:     "Source modified   : NO"
     287: )
     288:
     289: print(
MATCHED TERMS : PHASE75_DATASET_DF

==============================================================================
CELL : 3
==============================================================================

--- lines 2–16 ---
       2: # PHASE 7.5 — CELL 4
       3: # BUILD CANONICAL DATASET CLIP KEY
       4: #
       5: # Identity:
       6: #   video_id + clip_id
       7: #
       8: # IMPORTANT:
>>>    9: # - Does NOT modify dataset_master.csv
      10: # - Does NOT use shard_id
      11: # - Does NOT use shard_index
      12: # - Does NOT use clip_index
      13: # - Does NOT create fallback IDs
      14: # ============================================================
      15:
      16: print("=" * 80)
MATCHED TERMS : dataset_master\.csv

--- lines 27–41 ---
      27:     "clip_id",
      28: ]
      29:
      30:
      31: missing_identity = [
      32:     column
      33:     for column in IDENTITY_COLUMNS
>>>   34:     if column not in PHASE75_DATASET_DF.columns
      35: ]
      36:
      37:
      38: if missing_identity:
      39:
      40:     raise RuntimeError(
      41:         "Cannot build dataset_clip_key.\n"
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 44–58 ---
      44:
      45:
      46: # ============================================================
      47: # 2. Check null identity
      48: # ============================================================
      49:
      50: null_identity_mask = (
>>>   51:     PHASE75_DATASET_DF[
      52:         IDENTITY_COLUMNS
      53:     ]
      54:     .isna()
      55:     .any(axis=1)
      56:     |
      57:     (
      58:         PHASE75_DATASET_DF[
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 51–65 ---
      51:     PHASE75_DATASET_DF[
      52:         IDENTITY_COLUMNS
      53:     ]
      54:     .isna()
      55:     .any(axis=1)
      56:     |
      57:     (
>>>   58:         PHASE75_DATASET_DF[
      59:             IDENTITY_COLUMNS
      60:         ]
      61:         .astype(str)
      62:         .apply(
      63:             lambda col:
      64:             col.str.strip().eq("")
      65:         )
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 79–93 ---
      79: )
      80:
      81:
      82: if null_identity_count:
      83:
      84:     print()
      85:     print(
>>>   86:         PHASE75_DATASET_DF.loc[
      87:             null_identity_mask,
      88:             IDENTITY_COLUMNS
      89:         ]
      90:         .head(20)
      91:         .to_string(index=False)
      92:     )
      93:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 97–111 ---
      97:     )
      98:
      99:
     100: # ============================================================
     101: # 3. Build canonical key
     102: # ============================================================
     103:
>>>  104: PHASE75_DATASET_DF[
     105:     "dataset_clip_key"
     106: ] = (
     107:
     108:     PHASE75_DATASET_DF[
     109:         "video_id"
     110:     ]
     111:     .astype(str)
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 101–115 ---
     101: # 3. Build canonical key
     102: # ============================================================
     103:
     104: PHASE75_DATASET_DF[
     105:     "dataset_clip_key"
     106: ] = (
     107:
>>>  108:     PHASE75_DATASET_DF[
     109:         "video_id"
     110:     ]
     111:     .astype(str)
     112:     .str.strip()
     113:
     114:     + "::"
     115:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 109–123 ---
     109:         "video_id"
     110:     ]
     111:     .astype(str)
     112:     .str.strip()
     113:
     114:     + "::"
     115:
>>>  116:     + PHASE75_DATASET_DF[
     117:         "clip_id"
     118:     ]
     119:     .astype(str)
     120:     .str.strip()
     121: )
     122:
     123:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 122–136 ---
     122:
     123:
     124: # ============================================================
     125: # 4. Duplicate check
     126: # ============================================================
     127:
     128: duplicate_mask = (
>>>  129:     PHASE75_DATASET_DF[
     130:         "dataset_clip_key"
     131:     ]
     132:     .duplicated(
     133:         keep=False
     134:     )
     135: )
     136:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 136–150 ---
     136:
     137:
     138: duplicate_rows = int(
     139:     duplicate_mask.sum()
     140: )
     141:
     142: duplicate_keys = int(
>>>  143:     PHASE75_DATASET_DF.loc[
     144:         duplicate_mask,
     145:         "dataset_clip_key"
     146:     ]
     147:     .nunique()
     148: )
     149:
     150:
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 159–173 ---
     159: )
     160:
     161:
     162: if duplicate_keys:
     163:
     164:     print()
     165:     print(
>>>  166:         PHASE75_DATASET_DF.loc[
     167:             duplicate_mask,
     168:             [
     169:                 "video_id",
     170:                 "clip_id",
     171:                 "dataset_clip_key",
     172:             ]
     173:         ]
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 186–200 ---
     186:
     187: print()
     188: print("=" * 80)
     189: print("DATASET CLIP KEY PREVIEW")
     190: print("=" * 80)
     191:
     192: print(
>>>  193:     PHASE75_DATASET_DF[
     194:         [
     195:             "video_id",
     196:             "clip_id",
     197:             "dataset_clip_key",
     198:         ]
     199:     ]
     200:     .head(10)
MATCHED TERMS : PHASE75_DATASET_DF

--- lines 209–223 ---
     209: print()
     210: print("=" * 80)
     211: print("CELL 4 COMPLETE")
     212: print("=" * 80)
     213:
     214: print(
     215:     f"Dataset rows : "
>>>  216:     f"{len(PHASE75_DATASET_DF):,}"
     217: )
     218:
     219: print(
     220:     f"Unique keys  : "

In [29]:
# ==============================================================================
# PHASE 6.5 — CELL 23
# TRACE EXACT CSV INPUT → PHASE75_DATASET_DF
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json
import re

NOTEBOOK_PATH = Path(
    r"C:\LipReadingSSL\notebooks\phase7.5_dataset_QA.ipynb"
)

print("=" * 78)
print("PHASE 6.5 — CELL 23")
print("TRACE EXACT CSV INPUT → PHASE75_DATASET_DF")
print("READ-ONLY")
print("=" * 78)

with open(
    NOTEBOOK_PATH,
    "r",
    encoding="utf-8"
) as f:
    notebook = json.load(f)

cells = notebook.get("cells", [])

patterns = [
    r"PHASE75_DATASET_DF\s*=",
    r"pd\.read_csv",
    r"read_csv",
    r"LABEL_FILE",
    r"MASTER_FILE",
    r"SPLIT_FILE",
    r"labels\.csv",
    r"dataset_master\.csv",
    r"split\.csv",
]

for cell_index, cell in enumerate(cells):

    source = "".join(
        cell.get("source", [])
    )

    if not source.strip():
        continue

    lines = source.splitlines()

    matches = []

    for line_index, line in enumerate(lines):

        found = []

        for pattern in patterns:
            if re.search(
                pattern,
                line,
                flags=re.IGNORECASE
            ):
                found.append(pattern)

        if found:
            matches.append(
                (line_index, found)
            )

    if not matches:
        continue

    print()
    print("=" * 78)
    print(f"CELL : {cell_index}")
    print("=" * 78)

    # Show each relevant line with enough context
    shown = set()

    for line_index, found in matches:

        start = max(
            0,
            line_index - 4
        )

        end = min(
            len(lines),
            line_index + 5
        )

        key = (start, end)

        if key in shown:
            continue

        shown.add(key)

        print()
        print(
            f"--- lines {start + 1}–{end} ---"
        )

        for i in range(start, end):

            marker = (
                ">>> "
                if i == line_index
                else "    "
            )

            print(
                f"{marker}{i + 1:4d}: "
                f"{lines[i]}"
            )

        print(
            "MATCH : "
            + ", ".join(found)
        )

print()
print("=" * 78)
print("CELL 23 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 23
TRACE EXACT CSV INPUT → PHASE75_DATASET_DF
READ-ONLY
==============================================================================

==============================================================================
CELL : 1
==============================================================================

--- lines 67–75 ---
      67: # -------------------------------------------------
      68: # Dataset Files
      69: # -------------------------------------------------
      70:
>>>   71: MASTER_FILE = DATASET_DIR / "dataset_master.csv"
      72:
      73: LABEL_FILE = DATASET_DIR / "labels.csv"
      74:
      75: SPLIT_FILE = DATASET_DIR / "split.csv"
MATCH : MASTER_FILE, dataset_master\.csv

--- lines 69–77 ---
      69: # -------------------------------------------------
      70:
      71: MASTER_FILE = DATASET_DIR / "dataset_master.csv"
      72:
>>>   73: LABEL_FILE = DATASET_DIR / "labels.csv"
      74:
      75: SPLIT_FILE = DATASET_DIR / "split.csv"
      76:
      77: TRAIN_FILE = DATASET_DIR / "train.csv"
MATCH : LABEL_FILE, labels\.csv

--- lines 71–79 ---
      71: MASTER_FILE = DATASET_DIR / "dataset_master.csv"
      72:
      73: LABEL_FILE = DATASET_DIR / "labels.csv"
      74:
>>>   75: SPLIT_FILE = DATASET_DIR / "split.csv"
      76:
      77: TRAIN_FILE = DATASET_DIR / "train.csv"
      78:
      79: VAL_FILE = DATASET_DIR / "val.csv"
MATCH : SPLIT_FILE, split\.csv

==============================================================================
CELL : 2
==============================================================================

--- lines 2–10 ---
       2: # PHASE 7.5 — CELL 3
       3: # LOAD EXISTING PHASE 7 DATASET
       4: #
       5: # Source:
>>>    6: #   C:\LipReadingSSL\output\dataset\dataset_master.csv
       7: #
       8: # IMPORTANT:
       9: # - Uses the REAL Phase 7 dataset_master.csv schema
      10: # - Does NOT require Phase 6 shard columns
MATCH : dataset_master\.csv

--- lines 5–13 ---
       5: # Source:
       6: #   C:\LipReadingSSL\output\dataset\dataset_master.csv
       7: #
       8: # IMPORTANT:
>>>    9: # - Uses the REAL Phase 7 dataset_master.csv schema
      10: # - Does NOT require Phase 6 shard columns
      11: # - Does NOT modify the source CSV
      12: # - Does NOT create fallback IDs
      13: # ============================================================
MATCH : dataset_master\.csv

--- lines 33–41 ---
      33: DATASET_MASTER_PATH = (
      34:     LIPREADING_ROOT
      35:     / "output"
      36:     / "dataset"
>>>   37:     / "dataset_master.csv"
      38: )
      39:
      40:
      41: print(
MATCH : dataset_master\.csv

--- lines 49–57 ---
      49:
      50: if not DATASET_MASTER_PATH.exists():
      51:
      52:     raise FileNotFoundError(
>>>   53:         "dataset_master.csv not found:\n"
      54:         f"{DATASET_MASTER_PATH}"
      55:     )
      56:
      57:
MATCH : dataset_master\.csv

--- lines 58–66 ---
      58: # ============================================================
      59: # 3. Load
      60: # ============================================================
      61:
>>>   62: dataset_df = pd.read_csv(
      63:     DATASET_MASTER_PATH,
      64:     low_memory=False
      65: )
      66:
MATCH : pd\.read_csv, read_csv

--- lines 67–75 ---
      67:
      68: # ============================================================
      69: # 4. Real Phase 7 dataset schema
      70: #
>>>   71: # Based on the actual dataset_master.csv inspected by user.
      72: # ============================================================
      73:
      74: EXPECTED_COLUMNS = [
      75:
MATCH : dataset_master\.csv

--- lines 140–148 ---
     140:
     141: if missing_columns:
     142:
     143:     raise RuntimeError(
>>>  144:         "dataset_master.csv schema mismatch.\n\n"
     145:         f"Missing columns:\n"
     146:         + "\n".join(
     147:             f" - {column}"
     148:             for column in missing_columns
MATCH : dataset_master\.csv

--- lines 185–193 ---
     185: # ============================================================
     186: # 8. Working copy
     187: # ============================================================
     188:
>>>  189: PHASE75_DATASET_DF = (
     190:     dataset_df.copy()
     191: )
     192:
     193:
MATCH : PHASE75_DATASET_DF\s*=

==============================================================================
CELL : 3
==============================================================================

--- lines 5–13 ---
       5: # Identity:
       6: #   video_id + clip_id
       7: #
       8: # IMPORTANT:
>>>    9: # - Does NOT modify dataset_master.csv
      10: # - Does NOT use shard_id
      11: # - Does NOT use shard_index
      12: # - Does NOT use clip_index
      13: # - Does NOT create fallback IDs
MATCH : dataset_master\.csv

==============================================================================
CELL : 4
==============================================================================

--- lines 1–9 ---
       1: # ============================================================
       2: # PHASE 7.5 — CELL 5 v2
       3: # STRUCTURAL DATASET QA
       4: #
>>>    5: # Based on REAL dataset_master.csv schema
       6: #
       7: # IMPORTANT:
       8: # - Do NOT assume:
       9: #       num_frames = end_frame - start_frame + 1
MATCH : dataset_master\.csv

--- lines 11–19 ---
      11: # - Phase 7 dataset contains clip metadata whose
      12: #   num_frames / clip_length are dataset-level attributes.
      13: #
      14: # - This cell validates structural consistency only.
>>>   15: # - It does NOT modify dataset_master.csv.
      16: # - It does NOT modify clip_npy.
      17: # ============================================================
      18:
      19: print("=" * 80)
MATCH : dataset_master\.csv

==============================================================================
CELL : 6
==============================================================================

--- lines 176–184 ---
     176:     encoding="utf-8-sig"
     177: )
     178:
     179: text_split_df.to_csv(
>>>  180:     ANALYSIS_DIR / "vocabulary_by_split.csv",
     181:     encoding="utf-8-sig"
     182: )
     183:
     184: text_video_df.to_csv(
MATCH : split\.csv

==============================================================================
CELL : 7
==============================================================================

--- lines 225–233 ---
     225:     encoding="utf-8-sig"
     226: )
     227:
     228: speaker_split.to_csv(
>>>  229:     ANALYSIS_DIR / "speaker_split.csv",
     230:     index=False,
     231:     encoding="utf-8-sig"
     232: )
     233:
MATCH : split\.csv

--- lines 231–239 ---
     231:     encoding="utf-8-sig"
     232: )
     233:
     234: video_split.to_csv(
>>>  235:     ANALYSIS_DIR / "video_split.csv",
     236:     index=False,
     237:     encoding="utf-8-sig"
     238: )
     239:
MATCH : split\.csv

==============================================================================
CELL : 9
==============================================================================

--- lines 309–317 ---
     309: # 8. Save
     310: # -------------------------------------------------
     311:
     312: split_distribution.to_csv(
>>>  313:     ANALYSIS_DIR / "distribution_split.csv",
     314:     index=False,
     315:     encoding="utf-8-sig"
     316: )
     317:
MATCH : split\.csv

==============================================================================
CELL : 12
==============================================================================

--- lines 170–178 ---
     170: if HISTORY_FILE.exists():
     171:
     172:     try:
     173:
>>>  174:         history_df = pd.read_csv(
     175:             HISTORY_FILE
     176:         )
     177:
     178:     except Exception:
MATCH : pd\.read_csv, read_csv

==============================================================================
CELL 23 COMPLETE — READ ONLY
==============================================================================

In [30]:
# ==============================================================================
# PHASE 6.5 — CELL 24
# FIND EXACT PHASE75_DATASET_DF ASSIGNMENT
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json
import re

NOTEBOOK_PATH = Path(
    r"C:\LipReadingSSL\notebooks\phase7.5_dataset_QA.ipynb"
)

print("=" * 78)
print("PHASE 6.5 — CELL 24")
print("FIND EXACT PHASE75_DATASET_DF ASSIGNMENT")
print("READ-ONLY")
print("=" * 78)

with open(
    NOTEBOOK_PATH,
    "r",
    encoding="utf-8"
) as f:
    notebook = json.load(f)

cells = notebook.get("cells", [])

patterns = [
    r"PHASE75_DATASET_DF\s*=",
    r"PHASE75_DATASET_DF\s*\[",
    r"PHASE75_DATASET_DF\.",
    r"PHASE75_DATASET_DF\s*$",
]

found_any = False

for cell_index, cell in enumerate(cells):

    source = "".join(
        cell.get("source", [])
    )

    if not source.strip():
        continue

    lines = source.splitlines()

    for line_index, line in enumerate(lines):

        matched = False

        for pattern in patterns:

            if re.search(
                pattern,
                line,
                flags=re.IGNORECASE
            ):
                matched = True
                break

        if not matched:
            continue

        found_any = True

        print()
        print("=" * 78)
        print(f"CELL : {cell_index}")
        print("=" * 78)

        start = max(
            0,
            line_index - 10
        )

        end = min(
            len(lines),
            line_index + 11
        )

        for i in range(start, end):

            marker = (
                ">>> "
                if i == line_index
                else "    "
            )

            print(
                f"{marker}{i + 1:4d}: "
                f"{lines[i]}"
            )

if not found_any:

    print()
    print(
        "❌ No explicit PHASE75_DATASET_DF assignment found."
    )

print()
print("=" * 78)
print("CELL 24 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 24
FIND EXACT PHASE75_DATASET_DF ASSIGNMENT
READ-ONLY
==============================================================================

==============================================================================
CELL : 2
==============================================================================
     179:
     180:     print(
     181:         "Extra columns : None"
     182:     )
     183:
     184:
     185: # ============================================================
     186: # 8. Working copy
     187: # ============================================================
     188:
>>>  189: PHASE75_DATASET_DF = (
     190:     dataset_df.copy()
     191: )
     192:
     193:
     194: # ============================================================
     195: # 9. Basic normalization for QA only
     196: # ============================================================
     197:
     198: for column in [
     199:     "video_id",

==============================================================================
CELL : 2
==============================================================================
     195: # 9. Basic normalization for QA only
     196: # ============================================================
     197:
     198: for column in [
     199:     "video_id",
     200:     "clip_id",
     201:     "dataset_id",
     202:     "split",
     203: ]:
     204:
>>>  205:     PHASE75_DATASET_DF[column] = (
     206:         PHASE75_DATASET_DF[column]
     207:         .astype(str)
     208:         .str.strip()
     209:     )
     210:
     211:
     212: # ============================================================
     213: # 10. Numeric columns
     214: # ============================================================
     215:

==============================================================================
CELL : 2
==============================================================================
     196: # ============================================================
     197:
     198: for column in [
     199:     "video_id",
     200:     "clip_id",
     201:     "dataset_id",
     202:     "split",
     203: ]:
     204:
     205:     PHASE75_DATASET_DF[column] = (
>>>  206:         PHASE75_DATASET_DF[column]
     207:         .astype(str)
     208:         .str.strip()
     209:     )
     210:
     211:
     212: # ============================================================
     213: # 10. Numeric columns
     214: # ============================================================
     215:
     216: for column in [

==============================================================================
CELL : 2
==============================================================================
     214: # ============================================================
     215:
     216: for column in [
     217:     "start_frame",
     218:     "end_frame",
     219:     "num_frames",
     220:     "clip_length",
     221:     "stride",
     222: ]:
     223:
>>>  224:     PHASE75_DATASET_DF[column] = pd.to_numeric(
     225:         PHASE75_DATASET_DF[column],
     226:         errors="coerce"
     227:     )
     228:
     229:
     230: # ============================================================
     231: # 11. Boolean-like columns
     232: # ============================================================
     233:
     234: BOOLEAN_COLUMNS = [

==============================================================================
CELL : 2
==============================================================================
     215:
     216: for column in [
     217:     "start_frame",
     218:     "end_frame",
     219:     "num_frames",
     220:     "clip_length",
     221:     "stride",
     222: ]:
     223:
     224:     PHASE75_DATASET_DF[column] = pd.to_numeric(
>>>  225:         PHASE75_DATASET_DF[column],
     226:         errors="coerce"
     227:     )
     228:
     229:
     230: # ============================================================
     231: # 11. Boolean-like columns
     232: # ============================================================
     233:
     234: BOOLEAN_COLUMNS = [
     235:     "clip_exists",

==============================================================================
CELL : 2
==============================================================================
     251:             "1": True,
     252:             "0": False,
     253:             "yes": True,
     254:             "no": False,
     255:         })
     256:     )
     257:
     258:
     259: for column in BOOLEAN_COLUMNS:
     260:
>>>  261:     PHASE75_DATASET_DF[column] = normalize_bool(
     262:         PHASE75_DATASET_DF[column]
     263:     )
     264:
     265:
     266: # ============================================================
     267: # 12. Final Cell 3 status
     268: # ============================================================
     269:
     270: print()
     271: print("=" * 80)

==============================================================================
CELL : 2
==============================================================================
     252:             "0": False,
     253:             "yes": True,
     254:             "no": False,
     255:         })
     256:     )
     257:
     258:
     259: for column in BOOLEAN_COLUMNS:
     260:
     261:     PHASE75_DATASET_DF[column] = normalize_bool(
>>>  262:         PHASE75_DATASET_DF[column]
     263:     )
     264:
     265:
     266: # ============================================================
     267: # 12. Final Cell 3 status
     268: # ============================================================
     269:
     270: print()
     271: print("=" * 80)
     272: print("CELL 3 COMPLETE")

==============================================================================
CELL : 2
==============================================================================
     272: print("CELL 3 COMPLETE")
     273: print("=" * 80)
     274:
     275: print(
     276:     f"Rows loaded       : "
     277:     f"{len(PHASE75_DATASET_DF):,}"
     278: )
     279:
     280: print(
     281:     f"Columns loaded    : "
>>>  282:     f"{len(PHASE75_DATASET_DF.columns)}"
     283: )
     284:
     285: print(
     286:     "Source modified   : NO"
     287: )
     288:
     289: print(
     290:     "Fallback IDs      : NONE"
     291: )
     292:

==============================================================================
CELL : 3
==============================================================================
      24:
      25: IDENTITY_COLUMNS = [
      26:     "video_id",
      27:     "clip_id",
      28: ]
      29:
      30:
      31: missing_identity = [
      32:     column
      33:     for column in IDENTITY_COLUMNS
>>>   34:     if column not in PHASE75_DATASET_DF.columns
      35: ]
      36:
      37:
      38: if missing_identity:
      39:
      40:     raise RuntimeError(
      41:         "Cannot build dataset_clip_key.\n"
      42:         f"Missing identity columns: {missing_identity}"
      43:     )
      44:

==============================================================================
CELL : 3
==============================================================================
      41:         "Cannot build dataset_clip_key.\n"
      42:         f"Missing identity columns: {missing_identity}"
      43:     )
      44:
      45:
      46: # ============================================================
      47: # 2. Check null identity
      48: # ============================================================
      49:
      50: null_identity_mask = (
>>>   51:     PHASE75_DATASET_DF[
      52:         IDENTITY_COLUMNS
      53:     ]
      54:     .isna()
      55:     .any(axis=1)
      56:     |
      57:     (
      58:         PHASE75_DATASET_DF[
      59:             IDENTITY_COLUMNS
      60:         ]
      61:         .astype(str)

==============================================================================
CELL : 3
==============================================================================
      48: # ============================================================
      49:
      50: null_identity_mask = (
      51:     PHASE75_DATASET_DF[
      52:         IDENTITY_COLUMNS
      53:     ]
      54:     .isna()
      55:     .any(axis=1)
      56:     |
      57:     (
>>>   58:         PHASE75_DATASET_DF[
      59:             IDENTITY_COLUMNS
      60:         ]
      61:         .astype(str)
      62:         .apply(
      63:             lambda col:
      64:             col.str.strip().eq("")
      65:         )
      66:         .any(axis=1)
      67:     )
      68: )

==============================================================================
CELL : 3
==============================================================================
      76: print(
      77:     f"Null/empty identity rows : "
      78:     f"{null_identity_count:,}"
      79: )
      80:
      81:
      82: if null_identity_count:
      83:
      84:     print()
      85:     print(
>>>   86:         PHASE75_DATASET_DF.loc[
      87:             null_identity_mask,
      88:             IDENTITY_COLUMNS
      89:         ]
      90:         .head(20)
      91:         .to_string(index=False)
      92:     )
      93:
      94:     raise RuntimeError(
      95:         "Invalid identity detected. "
      96:         "dataset_clip_key was NOT created."

==============================================================================
CELL : 3
==============================================================================
      94:     raise RuntimeError(
      95:         "Invalid identity detected. "
      96:         "dataset_clip_key was NOT created."
      97:     )
      98:
      99:
     100: # ============================================================
     101: # 3. Build canonical key
     102: # ============================================================
     103:
>>>  104: PHASE75_DATASET_DF[
     105:     "dataset_clip_key"
     106: ] = (
     107:
     108:     PHASE75_DATASET_DF[
     109:         "video_id"
     110:     ]
     111:     .astype(str)
     112:     .str.strip()
     113:
     114:     + "::"

==============================================================================
CELL : 3
==============================================================================
      98:
      99:
     100: # ============================================================
     101: # 3. Build canonical key
     102: # ============================================================
     103:
     104: PHASE75_DATASET_DF[
     105:     "dataset_clip_key"
     106: ] = (
     107:
>>>  108:     PHASE75_DATASET_DF[
     109:         "video_id"
     110:     ]
     111:     .astype(str)
     112:     .str.strip()
     113:
     114:     + "::"
     115:
     116:     + PHASE75_DATASET_DF[
     117:         "clip_id"
     118:     ]

==============================================================================
CELL : 3
==============================================================================
     106: ] = (
     107:
     108:     PHASE75_DATASET_DF[
     109:         "video_id"
     110:     ]
     111:     .astype(str)
     112:     .str.strip()
     113:
     114:     + "::"
     115:
>>>  116:     + PHASE75_DATASET_DF[
     117:         "clip_id"
     118:     ]
     119:     .astype(str)
     120:     .str.strip()
     121: )
     122:
     123:
     124: # ============================================================
     125: # 4. Duplicate check
     126: # ============================================================

==============================================================================
CELL : 3
==============================================================================
     119:     .astype(str)
     120:     .str.strip()
     121: )
     122:
     123:
     124: # ============================================================
     125: # 4. Duplicate check
     126: # ============================================================
     127:
     128: duplicate_mask = (
>>>  129:     PHASE75_DATASET_DF[
     130:         "dataset_clip_key"
     131:     ]
     132:     .duplicated(
     133:         keep=False
     134:     )
     135: )
     136:
     137:
     138: duplicate_rows = int(
     139:     duplicate_mask.sum()

==============================================================================
CELL : 3
==============================================================================
     133:         keep=False
     134:     )
     135: )
     136:
     137:
     138: duplicate_rows = int(
     139:     duplicate_mask.sum()
     140: )
     141:
     142: duplicate_keys = int(
>>>  143:     PHASE75_DATASET_DF.loc[
     144:         duplicate_mask,
     145:         "dataset_clip_key"
     146:     ]
     147:     .nunique()
     148: )
     149:
     150:
     151: print(
     152:     f"Duplicate key rows : "
     153:     f"{duplicate_rows:,}"

==============================================================================
CELL : 3
==============================================================================
     156: print(
     157:     f"Duplicate keys     : "
     158:     f"{duplicate_keys:,}"
     159: )
     160:
     161:
     162: if duplicate_keys:
     163:
     164:     print()
     165:     print(
>>>  166:         PHASE75_DATASET_DF.loc[
     167:             duplicate_mask,
     168:             [
     169:                 "video_id",
     170:                 "clip_id",
     171:                 "dataset_clip_key",
     172:             ]
     173:         ]
     174:         .head(20)
     175:         .to_string(index=False)
     176:     )

==============================================================================
CELL : 3
==============================================================================
     183: # ============================================================
     184: # 5. Preview
     185: # ============================================================
     186:
     187: print()
     188: print("=" * 80)
     189: print("DATASET CLIP KEY PREVIEW")
     190: print("=" * 80)
     191:
     192: print(
>>>  193:     PHASE75_DATASET_DF[
     194:         [
     195:             "video_id",
     196:             "clip_id",
     197:             "dataset_clip_key",
     198:         ]
     199:     ]
     200:     .head(10)
     201:     .to_string(index=False)
     202: )
     203:

==============================================================================
CELL : 3
==============================================================================
     211: print("CELL 4 COMPLETE")
     212: print("=" * 80)
     213:
     214: print(
     215:     f"Dataset rows : "
     216:     f"{len(PHASE75_DATASET_DF):,}"
     217: )
     218:
     219: print(
     220:     f"Unique keys  : "
>>>  221:     f"{PHASE75_DATASET_DF['dataset_clip_key'].nunique():,}"
     222: )
     223:
     224: print(
     225:     "Key identity : video_id + clip_id"
     226: )
     227:
     228: print(
     229:     "Source CSV modified : NO"
     230: )
     231:

==============================================================================
CELL : 4
==============================================================================
      33:     "end_frame",
      34:     "num_frames",
      35:     "clip_length",
      36:     "stride",
      37: ]
      38:
      39:
      40: missing_columns = [
      41:     column
      42:     for column in REQUIRED_COLUMNS
>>>   43:     if column not in PHASE75_DATASET_DF.columns
      44: ]
      45:
      46:
      47: if missing_columns:
      48:
      49:     raise RuntimeError(
      50:         "Cell 5 v2 missing required columns:\n"
      51:         + "\n".join(
      52:             f" - {column}"
      53:             for column in missing_columns

==============================================================================
CELL : 4
==============================================================================
      53:             for column in missing_columns
      54:         )
      55:     )
      56:
      57:
      58: # ============================================================
      59: # 2. Basic information
      60: # ============================================================
      61:
      62: row_count = len(
>>>   63:     PHASE75_DATASET_DF
      64: )
      65:
      66: print(
      67:     f"Rows : {row_count:,}"
      68: )
      69:
      70:
      71: # ============================================================
      72: # 3. Null identity checks
      73: # ============================================================

==============================================================================
CELL : 4
==============================================================================
      76:
      77: null_counts = {}
      78:
      79: for column in [
      80:     "dataset_id",
      81:     "video_id",
      82:     "clip_id",
      83: ]:
      84:
      85:     count = int(
>>>   86:         PHASE75_DATASET_DF[
      87:             column
      88:         ]
      89:         .isna()
      90:         .sum()
      91:     )
      92:
      93:     null_counts[
      94:         column
      95:     ] = count
      96:

==============================================================================
CELL : 4
==============================================================================
     106:
     107: empty_identity_counts = {}
     108:
     109: for column in [
     110:     "dataset_id",
     111:     "video_id",
     112:     "clip_id",
     113: ]:
     114:
     115:     mask = (
>>>  116:         PHASE75_DATASET_DF[
     117:             column
     118:         ]
     119:         .astype(str)
     120:         .str.strip()
     121:         .eq("")
     122:     )
     123:
     124:     count = int(
     125:         mask.sum()
     126:     )

==============================================================================
CELL : 4
==============================================================================
     151: # 5. Duplicate dataset_clip_key
     152: #
     153: # Cell 4 already creates:
     154: #
     155: #   video_id::clip_id
     156: #
     157: # We validate it again here because this is the
     158: # structural QA stage.
     159: # ============================================================
     160:
>>>  161: if "dataset_clip_key" not in PHASE75_DATASET_DF.columns:
     162:
     163:     raise RuntimeError(
     164:         "dataset_clip_key is missing. "
     165:         "Run Cell 4 first."
     166:     )
     167:
     168:
     169: duplicate_key_mask = (
     170:     PHASE75_DATASET_DF[
     171:         "dataset_clip_key"

==============================================================================
CELL : 4
==============================================================================
     160:
     161: if "dataset_clip_key" not in PHASE75_DATASET_DF.columns:
     162:
     163:     raise RuntimeError(
     164:         "dataset_clip_key is missing. "
     165:         "Run Cell 4 first."
     166:     )
     167:
     168:
     169: duplicate_key_mask = (
>>>  170:     PHASE75_DATASET_DF[
     171:         "dataset_clip_key"
     172:     ]
     173:     .duplicated(
     174:         keep=False
     175:     )
     176: )
     177:
     178:
     179: duplicate_key_rows = int(
     180:     duplicate_key_mask.sum()

==============================================================================
CELL : 4
==============================================================================
     174:         keep=False
     175:     )
     176: )
     177:
     178:
     179: duplicate_key_rows = int(

In [32]:
# ==============================================================================
# PHASE 6.5 — CELL 25B
# SHOW DATASET_DF LOAD CODE
# READ-ONLY
# ==============================================================================

from pathlib import Path
import json

NOTEBOOK_PATH = Path(
    r"C:\LipReadingSSL\notebooks\phase7.5_dataset_QA.ipynb"
)

with open(
    NOTEBOOK_PATH,
    "r",
    encoding="utf-8"
) as f:
    notebook = json.load(f)

cells = notebook.get("cells", [])

cell = cells[2]

source = "".join(
    cell.get("source", [])
)

lines = source.splitlines()

print("=" * 78)
print("PHASE 6.5 — CELL 25B")
print("DATASET_DF LOAD CODE")
print("READ-ONLY")
print("=" * 78)

print()
print(f"CELL : 2")
print(f"TOTAL LINES : {len(lines)}")

print()
print("-" * 78)
print("LINES 58–100")
print("-" * 78)

for i in range(
    57,
    min(100, len(lines))
):
    print(
        f"{i + 1:4d}: {lines[i]}"
    )

print()
print("=" * 78)
print("CELL 25B COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 25B
DATASET_DF LOAD CODE
READ-ONLY
==============================================================================

CELL : 2
TOTAL LINES : 293

------------------------------------------------------------------------------
LINES 58–100
------------------------------------------------------------------------------
  58: # ============================================================
  59: # 3. Load
  60: # ============================================================
  61:
  62: dataset_df = pd.read_csv(
  63:     DATASET_MASTER_PATH,
  64:     low_memory=False
  65: )
  66:
  67:
  68: # ============================================================
  69: # 4. Real Phase 7 dataset schema
  70: #
  71: # Based on the actual dataset_master.csv inspected by user.
  72: # ============================================================
  73:
  74: EXPECTED_COLUMNS = [
  75:
  76:     "dataset_id",
  77:     "video_id",
  78:     "clip_id",
  79:     "clip_path",
  80:     "frame_folder",
  81:
  82:     "start_frame",
  83:     "end_frame",
  84:     "num_frames",
  85:     "clip_length",
  86:     "stride",
  87:
  88:     "speaker_id",
  89:     "sentence_id",
  90:     "transcript",
  91:     "normalized_text",
  92:
  93:     "clip_exists",
  94:     "frame_exists",
  95:     "has_transcript",
  96:     "split",
  97:
  98: ]
  99:
 100:

==============================================================================
CELL 25B COMPLETE — READ ONLY
==============================================================================

In [33]:
# ==============================================================================
# PHASE 6.5 — CELL 26
# INSPECT DATASET_MASTER CONTENT
# READ-ONLY
# ==============================================================================

from pathlib import Path
import pandas as pd

print("=" * 78)
print("PHASE 6.5 — CELL 26")
print("INSPECT DATASET_MASTER CONTENT")
print("READ-ONLY")
print("=" * 78)

DATASET_MASTER_PATH = Path(
    r"C:\LipReadingSSL\output\dataset\dataset_master.csv"
)

print()
print("Path   :", DATASET_MASTER_PATH)
print("Exists :", DATASET_MASTER_PATH.exists())

if not DATASET_MASTER_PATH.exists():
    raise FileNotFoundError(
        f"dataset_master.csv not found:\n{DATASET_MASTER_PATH}"
    )

# ------------------------------------------------------------------------------
# Load READ-ONLY
# ------------------------------------------------------------------------------

df_master = pd.read_csv(
    DATASET_MASTER_PATH,
    low_memory=False
)

# ------------------------------------------------------------------------------
# Basic information
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("BASIC INFORMATION")
print("-" * 78)

print(f"Rows    : {len(df_master):,}")
print(f"Columns : {len(df_master.columns):,}")

print()
print("Columns:")
for column in df_master.columns:
    print(f" - {column}")

# ------------------------------------------------------------------------------
# Annotation-related columns
# ------------------------------------------------------------------------------

ANNOTATION_TERMS = [
    "label",
    "transcript",
    "sentence",
    "speaker",
    "text",
    "annotation",
    "target",
    "class",
]

annotation_columns = [
    column
    for column in df_master.columns
    if any(
        term in str(column).lower()
        for term in ANNOTATION_TERMS
    )
]

print()
print("-" * 78)
print("POSSIBLE ANNOTATION COLUMNS")
print("-" * 78)

if annotation_columns:
    for column in annotation_columns:
        print(f" - {column}")
else:
    print("None found")

# ------------------------------------------------------------------------------
# Video distribution
# ------------------------------------------------------------------------------

if "video_id" in df_master.columns:

    print()
    print("-" * 78)
    print("VIDEO DISTRIBUTION")
    print("-" * 78)

    counts = (
        df_master["video_id"]
        .value_counts(dropna=False)
        .sort_index()
    )

    for video_id, count in counts.items():
        print(
            f"{str(video_id):<15} "
            f"{int(count):,} rows"
        )

# ------------------------------------------------------------------------------
# Sample
# ------------------------------------------------------------------------------

print()
print("-" * 78)
print("SAMPLE ROWS")
print("-" * 78)

print(
    df_master
    .head(10)
    .to_string(index=False)
)

print()
print("=" * 78)
print("CELL 26 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 26
INSPECT DATASET_MASTER CONTENT
READ-ONLY
==============================================================================

Path   : C:\LipReadingSSL\output\dataset\dataset_master.csv
Exists : True

------------------------------------------------------------------------------
BASIC INFORMATION
------------------------------------------------------------------------------
Rows    : 98,011
Columns : 26

Columns:
 - dataset_id
 - video_id
 - clip_id
 - clip_path
 - frame_folder
 - start_frame
 - end_frame
 - num_frames
 - clip_length
 - stride
 - speaker_id
 - sentence_id
 - transcript
 - normalized_text
 - language
 - verified
 - shard_id
 - shard_index
 - dtype
 - height
 - width
 - storage
 - clip_exists
 - frame_exists
 - has_transcript
 - split

------------------------------------------------------------------------------
POSSIBLE ANNOTATION COLUMNS
------------------------------------------------------------------------------
 - speaker_id
 - sentence_id
 - transcript
 - normalized_text
 - has_transcript

------------------------------------------------------------------------------
VIDEO DISTRIBUTION
------------------------------------------------------------------------------
video001        40,076 rows
video002        31,662 rows
video003        26,273 rows

------------------------------------------------------------------------------
SAMPLE ROWS
------------------------------------------------------------------------------
          dataset_id video_id     clip_id                                                  clip_path  frame_folder  start_frame  end_frame  num_frames  clip_length  stride  speaker_id  sentence_id  transcript  normalized_text language  verified         shard_id  shard_index dtype  height  width   storage  clip_exists  frame_exists  has_transcript  split
video001_clip_000000 video001 clip_000000 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            0         15          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            0 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000001 video001 clip_000001 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            1         16          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            1 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000002 video001 clip_000002 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            2         17          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            2 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000003 video001 clip_000003 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            3         18          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            3 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000004 video001 clip_000004 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            4         19          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            4 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000005 video001 clip_000005 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            5         20          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            5 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000006 video001 clip_000006 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            6         21          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            6 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000007 video001 clip_000007 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            7         22          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            7 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000008 video001 clip_000008 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            8         23          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            8 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000009 video001 clip_000009 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            9         24          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            9 uint8      96     96 shard_npz         True          True           False    NaN

==============================================================================
CELL 26 COMPLETE — READ ONLY
==============================================================================

In [35]:
# ==============================================================================
# PHASE 6.5 — CELL 27
# INSPECT COMPLETE DATASET_MASTER SCHEMA
# READ-ONLY / SELF-CONTAINED
# ==============================================================================

from pathlib import Path
import pandas as pd

print("=" * 78)
print("PHASE 6.5 — CELL 27")
print("INSPECT COMPLETE DATASET_MASTER SCHEMA")
print("READ-ONLY / SELF-CONTAINED")
print("=" * 78)

# ==============================================================================
# 1. Dataset path
# ==============================================================================

DATASET_MASTER_PATH = Path(
    r"C:\LipReadingSSL\output\dataset\dataset_master.csv"
)

print()
print("=" * 78)
print("DATASET")
print("=" * 78)

print(
    f"Path : {DATASET_MASTER_PATH}"
)

print(
    f"Exists : {DATASET_MASTER_PATH.exists()}"
)

if not DATASET_MASTER_PATH.exists():
    raise FileNotFoundError(
        f"dataset_master.csv not found:\n"
        f"{DATASET_MASTER_PATH}"
    )

# ==============================================================================
# 2. Load dataset_master.csv
# ==============================================================================

dataset_df = pd.read_csv(
    DATASET_MASTER_PATH,
    low_memory=False
)

# ==============================================================================
# 3. Basic information
# ==============================================================================

print()

print(
    f"Rows : {len(dataset_df):,}"
)

print(
    f"Columns : {len(dataset_df.columns)}"
)

# ==============================================================================
# 4. All columns
# ==============================================================================

print()
print("=" * 78)
print("ALL COLUMNS")
print("=" * 78)

for index, column in enumerate(
    dataset_df.columns,
    start=1
):

    print(
        f"{index:02d}. {column}"
    )

# ==============================================================================
# 5. Column details
# ==============================================================================

print()
print("=" * 78)
print("COLUMN DETAILS")
print("=" * 78)

for column in dataset_df.columns:

    series = dataset_df[column]

    non_null = int(
        series.notna().sum()
    )

    null_count = int(
        series.isna().sum()
    )

    unique_count = int(
        series.nunique(
            dropna=True
        )
    )

    print(
        f"{column:<25} "
        f"non-null={non_null:,} | "
        f"null={null_count:,} | "
        f"unique={unique_count:,}"
    )

# ==============================================================================
# 6. Possible annotation columns
# ==============================================================================

print()
print("=" * 78)
print("POSSIBLE ANNOTATION / TRANSCRIPT COLUMNS")
print("=" * 78)

annotation_terms = [
    "label",
    "transcript",
    "sentence",
    "speaker",
    "text",
    "annotation",
    "target",
    "class",
]

annotation_columns = [
    column
    for column in dataset_df.columns
    if any(
        term in str(column).lower()
        for term in annotation_terms
    )
]

if annotation_columns:

    for column in annotation_columns:
        print(
            f" - {column}"
        )

else:

    print(
        "None found"
    )

# ==============================================================================
# 7. Video distribution
# ==============================================================================

print()
print("=" * 78)
print("VIDEO DISTRIBUTION")
print("=" * 78)

if "video_id" in dataset_df.columns:

    video_counts = (
        dataset_df[
            "video_id"
        ]
        .value_counts(
            dropna=False
        )
        .sort_index()
    )

    for video_id, count in video_counts.items():

        print(
            f"{str(video_id):<15} "
            f"{int(count):,} clips"
        )

else:

    print(
        "⚠️ video_id column not found"
    )

# ==============================================================================
# 8. Split distribution
# ==============================================================================

print()
print("=" * 78)
print("SPLIT DISTRIBUTION")
print("=" * 78)

if "split" in dataset_df.columns:

    split_counts = (
        dataset_df[
            "split"
        ]
        .value_counts(
            dropna=False
        )
    )

    for split_name, count in split_counts.items():

        print(
            f"{str(split_name):<15} "
            f"{int(count):,} clips"
        )

else:

    print(
        "⚠️ split column not found"
    )

# ==============================================================================
# 9. First rows
# ==============================================================================

print()
print("=" * 78)
print("FIRST 10 ROWS")
print("=" * 78)

print(
    dataset_df
    .head(10)
    .to_string(index=False)
)

# ==============================================================================
# 10. Final
# ==============================================================================

print()
print("=" * 78)
print("CELL 27 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 27
INSPECT COMPLETE DATASET_MASTER SCHEMA
READ-ONLY / SELF-CONTAINED
==============================================================================

==============================================================================
DATASET
==============================================================================
Path : C:\LipReadingSSL\output\dataset\dataset_master.csv
Exists : True

Rows : 98,011
Columns : 26

==============================================================================
ALL COLUMNS
==============================================================================
01. dataset_id
02. video_id
03. clip_id
04. clip_path
05. frame_folder
06. start_frame
07. end_frame
08. num_frames
09. clip_length
10. stride
11. speaker_id
12. sentence_id
13. transcript
14. normalized_text
15. language
16. verified
17. shard_id
18. shard_index
19. dtype
20. height
21. width
22. storage
23. clip_exists
24. frame_exists
25. has_transcript
26. split

==============================================================================
COLUMN DETAILS
==============================================================================
dataset_id                non-null=98,011 | null=0 | unique=98,011
video_id                  non-null=98,011 | null=0 | unique=3
clip_id                   non-null=98,011 | null=0 | unique=40,076
clip_path                 non-null=98,011 | null=0 | unique=193
frame_folder              non-null=0 | null=98,011 | unique=0
start_frame               non-null=98,011 | null=0 | unique=42,515
end_frame                 non-null=98,011 | null=0 | unique=42,515
num_frames                non-null=98,011 | null=0 | unique=1
clip_length               non-null=98,011 | null=0 | unique=1
stride                    non-null=98,011 | null=0 | unique=1
speaker_id                non-null=0 | null=98,011 | unique=0
sentence_id               non-null=0 | null=98,011 | unique=0
transcript                non-null=0 | null=98,011 | unique=0
normalized_text           non-null=0 | null=98,011 | unique=0
language                  non-null=98,011 | null=0 | unique=1
verified                  non-null=98,011 | null=0 | unique=1
shard_id                  non-null=98,011 | null=0 | unique=79
shard_index               non-null=98,011 | null=0 | unique=512
dtype                     non-null=98,011 | null=0 | unique=1
height                    non-null=98,011 | null=0 | unique=1
width                     non-null=98,011 | null=0 | unique=1
storage                   non-null=98,011 | null=0 | unique=1
clip_exists               non-null=98,011 | null=0 | unique=1
frame_exists              non-null=98,011 | null=0 | unique=1
has_transcript            non-null=98,011 | null=0 | unique=1
split                     non-null=0 | null=98,011 | unique=0

==============================================================================
POSSIBLE ANNOTATION / TRANSCRIPT COLUMNS
==============================================================================
 - speaker_id
 - sentence_id
 - transcript
 - normalized_text
 - has_transcript

==============================================================================
VIDEO DISTRIBUTION
==============================================================================
video001        40,076 clips
video002        31,662 clips
video003        26,273 clips

==============================================================================
SPLIT DISTRIBUTION
==============================================================================
nan             98,011 clips

==============================================================================
FIRST 10 ROWS
==============================================================================
          dataset_id video_id     clip_id                                                  clip_path  frame_folder  start_frame  end_frame  num_frames  clip_length  stride  speaker_id  sentence_id  transcript  normalized_text language  verified         shard_id  shard_index dtype  height  width   storage  clip_exists  frame_exists  has_transcript  split
video001_clip_000000 video001 clip_000000 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            0         15          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            0 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000001 video001 clip_000001 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            1         16          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            1 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000002 video001 clip_000002 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            2         17          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            2 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000003 video001 clip_000003 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            3         18          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            3 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000004 video001 clip_000004 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            4         19          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            4 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000005 video001 clip_000005 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            5         20          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            5 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000006 video001 clip_000006 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            6         21          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            6 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000007 video001 clip_000007 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            7         22          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            7 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000008 video001 clip_000008 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            8         23          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            8 uint8      96     96 shard_npz         True          True           False    NaN
video001_clip_000009 video001 clip_000009 C:\LipReadingSSL\output\video001\clip_npy\shard_000000.npz           NaN            9         24          16           16       1         NaN          NaN         NaN              NaN       th     False shard_000000.npz            9 uint8      96     96 shard_npz         True          True           False    NaN

==============================================================================
CELL 27 COMPLETE — READ ONLY
==============================================================================

In [36]:
# ==============================================================================
# PHASE 6.5 — CELL 28
# SHOW ALL DATASET_MASTER COLUMNS
# READ-ONLY
# ==============================================================================

print("=" * 78)
print("PHASE 6.5 — CELL 28")
print("SHOW ALL DATASET_MASTER COLUMNS")
print("READ-ONLY")
print("=" * 78)

for i, column in enumerate(
    dataset_df.columns,
    start=1
):
    print(
        f"{i:02d}. {column}"
    )

print()
print("=" * 78)
print("CELL 28 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 28
SHOW ALL DATASET_MASTER COLUMNS
READ-ONLY
==============================================================================
01. dataset_id
02. video_id
03. clip_id
04. clip_path
05. frame_folder
06. start_frame
07. end_frame
08. num_frames
09. clip_length
10. stride
11. speaker_id
12. sentence_id
13. transcript
14. normalized_text
15. language
16. verified
17. shard_id
18. shard_index
19. dtype
20. height
21. width
22. storage
23. clip_exists
24. frame_exists
25. has_transcript
26. split

==============================================================================
CELL 28 COMPLETE — READ ONLY
==============================================================================

In [37]:
# ==============================================================================
# PHASE 6.5 — CELL 29
# SHOW DATASET_MASTER COLUMNS 21–26
# READ-ONLY
# ==============================================================================

print("=" * 78)
print("PHASE 6.5 — CELL 29")
print("DATASET_MASTER COLUMNS 21–26")
print("READ-ONLY")
print("=" * 78)

columns = list(dataset_df.columns)

for i in range(20, len(columns)):
    print(
        f"{i + 1:02d}. {columns[i]}"
    )

print()
print("=" * 78)
print("CELL 29 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 29
DATASET_MASTER COLUMNS 21–26
READ-ONLY
==============================================================================
21. width
22. storage
23. clip_exists
24. frame_exists
25. has_transcript
26. split

==============================================================================
CELL 29 COMPLETE — READ ONLY
==============================================================================

In [38]:
# ==============================================================================
# PHASE 6.5 — CELL 30
# CHECK DATASET_MASTER ANNOTATION COMPLETENESS
# READ-ONLY
# ==============================================================================

from pathlib import Path
import pandas as pd

DATASET_MASTER_PATH = Path(
    r"C:\LipReadingSSL\output\dataset\dataset_master.csv"
)

print("=" * 78)
print("PHASE 6.5 — CELL 30")
print("CHECK DATASET_MASTER ANNOTATION COMPLETENESS")
print("READ-ONLY")
print("=" * 78)

# ------------------------------------------------------------------------------
# 1. Load
# ------------------------------------------------------------------------------

if not DATASET_MASTER_PATH.exists():
    raise FileNotFoundError(
        f"dataset_master.csv not found:\n{DATASET_MASTER_PATH}"
    )

df = pd.read_csv(
    DATASET_MASTER_PATH,
    low_memory=False
)

print()
print(f"Rows    : {len(df):,}")
print(f"Columns : {len(df.columns)}")

# ------------------------------------------------------------------------------
# 2. Annotation columns
# ------------------------------------------------------------------------------

ANNOTATION_COLUMNS = [
    "speaker_id",
    "sentence_id",
    "transcript",
    "normalized_text",
    "language",
    "verified",
]

missing_columns = [
    column
    for column in ANNOTATION_COLUMNS
    if column not in df.columns
]

if missing_columns:
    print()
    print("Missing annotation columns:")
    for column in missing_columns:
        print(f" - {column}")

    raise RuntimeError(
        "Required annotation columns are missing."
    )

# ------------------------------------------------------------------------------
# 3. Completeness
# ------------------------------------------------------------------------------

print()
print("=" * 78)
print("ANNOTATION COMPLETENESS")
print("=" * 78)

for column in ANNOTATION_COLUMNS:

    series = df[column]

    missing_mask = (
        series.isna()
        | series.astype(str).str.strip().isin(
            ["", "nan", "None", "NULL", "UNKNOWN"]
        )
    )

    missing_count = int(missing_mask.sum())
    valid_count = int(len(df) - missing_count)

    percentage = (
        valid_count / len(df) * 100
        if len(df)
        else 0
    )

    print()
    print(f"{column}")
    print(f"  Valid   : {valid_count:,}")
    print(f"  Missing : {missing_count:,}")
    print(f"  Valid % : {percentage:.2f}%")

# ------------------------------------------------------------------------------
# 4. Video distribution
# ------------------------------------------------------------------------------

print()
print("=" * 78)
print("ANNOTATION COVERAGE BY VIDEO")
print("=" * 78)

for video_id, group in df.groupby(
    "video_id",
    dropna=False
):

    print()
    print(f"{video_id}")

    for column in ANNOTATION_COLUMNS:

        series = group[column]

        missing_mask = (
            series.isna()
            | series.astype(str).str.strip().isin(
                ["", "nan", "None", "NULL", "UNKNOWN"]
            )
        )

        valid_count = int(
            (~missing_mask).sum()
        )

        print(
            f"  {column:<20} "
            f"{valid_count:,}/{len(group):,}"
        )

# ------------------------------------------------------------------------------
# 5. Transcript examples
# ------------------------------------------------------------------------------

print()
print("=" * 78)
print("TRANSCRIPT SAMPLE")
print("=" * 78)

sample_columns = [
    "video_id",
    "clip_id",
    "speaker_id",
    "sentence_id",
    "transcript",
    "normalized_text",
]

print(
    df[sample_columns]
    .head(20)
    .to_string(index=False)
)

# ------------------------------------------------------------------------------
# 6. Final
# ------------------------------------------------------------------------------

print()
print("=" * 78)
print("CELL 30 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 30
CHECK DATASET_MASTER ANNOTATION COMPLETENESS
READ-ONLY
==============================================================================

Rows    : 98,011
Columns : 26

==============================================================================
ANNOTATION COMPLETENESS
==============================================================================

speaker_id
  Valid   : 0
  Missing : 98,011
  Valid % : 0.00%

sentence_id
  Valid   : 0
  Missing : 98,011
  Valid % : 0.00%

transcript
  Valid   : 0
  Missing : 98,011
  Valid % : 0.00%

normalized_text
  Valid   : 0
  Missing : 98,011
  Valid % : 0.00%

language
  Valid   : 98,011
  Missing : 0
  Valid % : 100.00%

verified
  Valid   : 98,011
  Missing : 0
  Valid % : 100.00%

==============================================================================
ANNOTATION COVERAGE BY VIDEO
==============================================================================

video001
  speaker_id           0/40,076
  sentence_id          0/40,076
  transcript           0/40,076
  normalized_text      0/40,076
  language             40,076/40,076
  verified             40,076/40,076

video002
  speaker_id           0/31,662
  sentence_id          0/31,662
  transcript           0/31,662
  normalized_text      0/31,662
  language             31,662/31,662
  verified             31,662/31,662

video003
  speaker_id           0/26,273
  sentence_id          0/26,273
  transcript           0/26,273
  normalized_text      0/26,273
  language             26,273/26,273
  verified             26,273/26,273

==============================================================================
TRANSCRIPT SAMPLE
==============================================================================
video_id     clip_id  speaker_id  sentence_id  transcript  normalized_text
video001 clip_000000         NaN          NaN         NaN              NaN
video001 clip_000001         NaN          NaN         NaN              NaN
video001 clip_000002         NaN          NaN         NaN              NaN
video001 clip_000003         NaN          NaN         NaN              NaN
video001 clip_000004         NaN          NaN         NaN              NaN
video001 clip_000005         NaN          NaN         NaN              NaN
video001 clip_000006         NaN          NaN         NaN              NaN
video001 clip_000007         NaN          NaN         NaN              NaN
video001 clip_000008         NaN          NaN         NaN              NaN
video001 clip_000009         NaN          NaN         NaN              NaN
video001 clip_000010         NaN          NaN         NaN              NaN
video001 clip_000011         NaN          NaN         NaN              NaN
video001 clip_000012         NaN          NaN         NaN              NaN
video001 clip_000013         NaN          NaN         NaN              NaN
video001 clip_000014         NaN          NaN         NaN              NaN
video001 clip_000015         NaN          NaN         NaN              NaN
video001 clip_000016         NaN          NaN         NaN              NaN
video001 clip_000017         NaN          NaN         NaN              NaN
video001 clip_000018         NaN          NaN         NaN              NaN
video001 clip_000019         NaN          NaN         NaN              NaN

==============================================================================
CELL 30 COMPLETE — READ ONLY
==============================================================================

In [ ]:
# ==============================================================================
# PHASE 6.5 — CELL 31
# INSPECT EXISTING LABEL_QA ANNOTATION VALUES
# READ-ONLY
# ==============================================================================

from pathlib import Path
import pandas as pd

LABEL_QA_PATH = Path(
    r"C:\LipReadingSSL\output\dataset\analysis\label_qa.csv"
)

print("=" * 78)
print("PHASE 6.5 — CELL 31")
print("INSPECT EXISTING LABEL_QA ANNOTATION VALUES")
print("READ-ONLY")
print("=" * 78)

print()
print("Path   :", LABEL_QA_PATH)
print("Exists :", LABEL_QA_PATH.exists())

if not LABEL_QA_PATH.exists():
    raise FileNotFoundError(
        f"label_qa.csv not found:\n{LABEL_QA_PATH}"
    )

# ------------------------------------------------------------------------------
# Load
# ------------------------------------------------------------------------------

df = pd.read_csv(
    LABEL_QA_PATH,
    low_memory=False
)

print()
print("=" * 78)
print("BASIC INFORMATION")
print("=" * 78)

print(
    f"Rows    : {len(df):,}"
)

print(
    f"Columns : {len(df.columns)}"
)

# ------------------------------------------------------------------------------
# Columns
# ------------------------------------------------------------------------------

print()
print("=" * 78)
print("COLUMNS")
print("=" * 78)

for i, column in enumerate(
    df.columns,
    start=1
):

    print(
        f"{i:02d}. {column}"
    )

# ------------------------------------------------------------------------------
# Annotation fields
# ------------------------------------------------------------------------------

annotation_columns = [
    column
    for column in [
        "video_id",
        "clip_id",
        "speaker_id",
        "sentence_id",
        "transcript",
        "normalized_text",
        "language",
        "verified",
    ]
    if column in df.columns
]

print()
print("=" * 78)
print("ANNOTATION FIELD STATUS")
print("=" * 78)

for column in annotation_columns:

    series = df[column]

    missing = (
        series.isna()
        | series.astype(str).str.strip().isin(
            [
                "",
                "nan",
                "None",
                "NULL",
                "UNKNOWN",
            ]
        )
    )

    valid_count = int(
        (~missing).sum()
    )

    missing_count = int(
        missing.sum()
    )

    unique_count = int(
        series[~missing].nunique()
    )

    print()
    print(column)
    print(
        f"  Valid       : {valid_count:,}"
    )
    print(
        f"  Missing     : {missing_count:,}"
    )
    print(
        f"  Unique      : {unique_count:,}"
    )

# ------------------------------------------------------------------------------
# Video distribution
# ------------------------------------------------------------------------------

print()
print("=" * 78)
print("VIDEO DISTRIBUTION")
print("=" * 78)

if "video_id" in df.columns:

    counts = (
        df["video_id"]
        .value_counts(dropna=False)
        .sort_index()
    )

    for video_id, count in counts.items():

        print(
            f"{str(video_id):<15} "
            f"{int(count):,} rows"
        )

# ------------------------------------------------------------------------------
# Transcript examples
# ------------------------------------------------------------------------------

if "transcript" in df.columns:

    print()
    print("=" * 78)
    print("NON-EMPTY TRANSCRIPT SAMPLE")
    print("=" * 78)

    transcript_mask = (
        df["transcript"].notna()
        & (
            df["transcript"]
            .astype(str)
            .str.strip()
            .ne("")
        )
    )

    sample_columns = [
        column
        for column in [
            "video_id",
            "clip_id",
            "speaker_id",
            "sentence_id",
            "transcript",
            "normalized_text",
            "language",
            "verified",
        ]
        if column in df.columns
    ]

    sample = (
        df.loc[
            transcript_mask,
            sample_columns
        ]
        .head(20)
    )

    if len(sample):

        print(
            sample.to_string(
                index=False
            )
        )

    else:

        print(
            "No non-empty transcript found."
        )

# ------------------------------------------------------------------------------
# Unique transcript sample
# ------------------------------------------------------------------------------

if "transcript" in df.columns:

    print()
    print("=" * 78)
    print("UNIQUE TRANSCRIPT VALUES")
    print("=" * 78)

    values = (
        df["transcript"]
        .dropna()
        .astype(str)
        .str.strip()
    )

    values = values[
        values.ne("")
    ]

    unique_values = (
        values
        .drop_duplicates()
        .head(50)
    )

    if len(unique_values):

        for i, value in enumerate(
            unique_values,
            start=1
        ):

            print(
                f"{i:02d}. {value}"
            )

    else:

        print(
            "No transcript values found."
        )

# ------------------------------------------------------------------------------
# Final
# ------------------------------------------------------------------------------

print()
print("=" * 78)
print("CELL 31 COMPLETE — READ ONLY")
print("=" * 78)

==============================================================================
PHASE 6.5 — CELL 31
INSPECT EXISTING LABEL_QA ANNOTATION VALUES
READ-ONLY
==============================================================================

Path   : C:\LipReadingSSL\output\dataset\analysis\label_qa.csv
Exists : True

==============================================================================
BASIC INFORMATION
==============================================================================
Rows    : 81,853
Columns : 20

==============================================================================
COLUMNS
==============================================================================
01. dataset_id
02. video_id
03. clip_id
04. clip_path
05. frame_folder
06. start_frame
07. end_frame
08. num_frames
09. clip_length
10. stride
11. speaker_id
12. sentence_id
13. transcript
14. normalized_text
15. language
16. verified
17. clip_exists
18. frame_exists
19. has_transcript
20. text_length

==============================================================================
ANNOTATION FIELD STATUS
==============================================================================

video_id
  Valid       : 81,853
  Missing     : 0
  Unique      : 2

clip_id
  Valid       : 81,853
  Missing     : 0
  Unique      : 42,993

speaker_id
  Valid       : 0
  Missing     : 81,853
  Unique      : 0

sentence_id
  Valid       : 0
  Missing     : 81,853
  Unique      : 0

transcript
  Valid       : 0
  Missing     : 81,853
  Unique      : 0

normalized_text
  Valid       : 0
  Missing     : 81,853
  Unique      : 0

language
  Valid       : 81,853
  Missing     : 0
  Unique      : 1

verified
  Valid       : 81,853
  Missing     : 0
  Unique      : 1

==============================================================================
VIDEO DISTRIBUTION
==============================================================================
video001        42,993 rows
video002        38,860 rows

==============================================================================
NON-EMPTY TRANSCRIPT SAMPLE
==============================================================================
No non-empty transcript found.

==============================================================================
UNIQUE TRANSCRIPT VALUES
==============================================================================
No transcript values found.

==============================================================================
CELL 31 COMPLETE — READ ONLY
==============================================================================